### ISSUE TITLE
GSE199850 - Intrarenal Single-Cell Sequencing of Hepatitis B Virus Associated Membranous Nephropathy

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#1001]
GSE199850 - Intrarenal Single-Cell Sequencing of Hepatitis B Virus Associated Membranous Nephropathy

### Project short name:
Xiao-Human-RNAscope

### Primary Wrangler:
Wei

### Secondary Wrangler:
Ida

### Link to Ingest

* https://contribute.data.humancellatlas.org/projects/detail?uuid=5f44a860-d96e-4a99-b67e-24e1b8ccfd26

### Associated files

* Google Drive: https://drive.google.com/drive/folders/1BShYRxDZvG4MpVB7jt6Mz9hHDZ7C5OHQ

### Published study links

* Paper: https://www.frontiersin.org/articles/10.3389/fmed.2022.869284/full#h7

* Accessioned data: [GSE199850](https://0-www-ncbi-nlm-nih-gov.brum.beds.ac.uk/geo/query/acc.cgi?acc=GSE199850)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
1 Hep B patient and 2 healthy controls in paper, but only the Hep B patient sequencing files and analysis files are available. Have emailed asking if the healthy control data / metadata is available.

**Comment by Wkt8** [comment]
Emailed again.

**Comment by idazucchi** [comment]
Hello! I'm done with the secondary review, I have some very small comments, otherwise it looks good!

Project
- you can split the author information into institute and address
- there is no funding information

Donor
- you can remove the age from the description, it makes it easier to address possible future k-anonimity issues

Specimen
- I thought we only used the  experiment field for the sequence file tab?
- same k-anonimity issue

Enrichment
- you can add the cell size selected

Cell suspension
- do you want to add the INSDC sample accession?
- the estimated cell count should have the estimated cells in the CS, not the sequenced cells

Analysis
- you could fill out the computational methods

Analysis file
- the genome version is missing in the spreadsheet

**Comment by Wkt8** [comment]
In Submitted. Still need to fill out the import form.

**Comment by Wkt8** [comment]
Import form filled out.
