### ISSUE TITLE
Single-Cell RNA Sequencing in Multiple Pathologic Types of Renal Cell Carcinoma Revealed Novel Potential Tumor-Specific Markers

### ISSUE THREAD

**Issue by anu-shiva** [ebi-ait/hca-ebi-wrangler-central#1010]
Single-Cell RNA Sequencing in Multiple Pathologic Types of Renal Cell Carcinoma Revealed Novel Potential Tumor-Specific Markers

### Project short name:
Cheng-Human-10x3pv3

### Primary Wrangler:
Anu

### Secondary Wrangler:
Ida

### Associated files

* Google Drive: [Cheng_RCC_GSE152938](https://drive.google.com/drive/folders/1rmuN8Gpmf8loe5tbUJ8nZaiudymPxfyY?usp=share_link)

- [Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=ee166275-f63a-4864-8155-4df86c9de679)

### Published study links

* Paper: [https://www.frontiersin.org/articles/10.3389/fonc.2021.719564/full](https://www.frontiersin.org/articles/10.3389/fonc.2021.719564/full)

* Accessioned data:
[GSE152938](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152938)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [x] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Hi Anu, I'm done with the review! You did a nice job with this project, you filled out all the necessary fields and even some unusual ones :)
I have some suggestions on a few fields you can fill and some based on best practices.

Let me know if you have any questions!

### Project
- add yourself as `data curator` in ingest!
- you can add the grant info from the publication

### Donor
- it's better to leave sex/age out of the donor's description for anonymity purposes - if in the future we have to anonymize some records it will be easier if the information is in one place
- when a disease is available from MONDO and HP the term from MONDO is the preferred option because HP describes phenotypic abnormalities while MONDO aims to harmonize disease definitions across the world
- if the donor are living there's no need to fill out the cause of death

### Collection protocol
- I suggest [`surgical resection`](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009744) for the ontology term

### Specimen
- you could add in the description of the normal sample that it was sampled from a site 2cm away form the tumor site
- unless a specific part of the organ was isolated for the experiment you can skip `organ part` 
- same as the donor, if both MONDO and HP terms are available MONDO terms are the preferred ones
- the experiment accession is only needed in the sequence file tab
- decide if the sample accessions represent better the specimens or the cell suspensions and put them in one of the two tabs, if in doubt cell suspension is a good option

### Dissociation protocol
- this is how I would split the protocols:
>Fresh tumor samples were obtained from the operating room to the laboratory in cold Hank’s balanced salt solution (HBSS) with 5% fatal bovine serum (FBS) and 1% penicillin/streptomycin (P/S). The entire transportation process was within 30 min.

Part of the collection protocol
>After the samples were washed with 4°C Dulbecco’s phosphate-buffered saline (DPBS), they were cut into 2–4 mm pieces with sterile scissors. The tissue pieces were washed by resuspending in pre-cold DPBS two times. 

Mechanical dissociation
>After the supernatant was removed, the tissue species were digested for 30 min at 37°C with gentle agitation in a digestion solution containing 1 mg/mL of collagenase I and 1 mg/mL of DNaseI in HBSS. Then, the digestion was terminated using 10 mL of DMEM with 10% FBS. 

Enzymatic dissociation
>Subsequently, the suspended cells and tissue fragments went through a 70 μm cell strainer, which could filter out large tissue fragments. The cells were washed with pre-cold DPBS containing 300 g of 1% FBS for 5 min two times. Next, red blood cells were removed using 5 mL of RBC lysis buffer (10X diluted to 1X) for 5 min on ice and then the cells were filtered using a 40 μm cell strainer. Subsequently, they were centrifuged at 300 g for 5 min and washed twice with DPBS. Finally, the cells were resuspended in DPBS with 1% FBS

Enrichment protocol, method: cell size selection, min size selected: 40

### Cell suspension
- you can record the percent viability in `percent cell viability` and remove the the percent of necrotic cells
- the estimated cell count captures the estimated number of cells loaded in the library prep machine so it should be 10'000 for all cell suspensions
- the experiment accession is only needed in the sequence file tab

### Library preparation
- `10X v3 sequencing` is an outdated label, please use the [current ontology label](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009922). The ontology label is indexed in the browser and if we use outdated terms we can't group together the library preparation technologies
- please fill in the UMI fields - you can check the [library prep cheatsheet](https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0)

### Sequencing protocol
- `paired end` sequencing is actually no. We use this field to indicate if both R1 and R2 are from the transcript or not

### Sequence file
- when you need to create a process the id is enough, the name and description are optional

### Analysis protocol
- name can have spaces!
- you can add quantification to `derivation process` 

### Analysis files
- for the matrix file `Count matrix` is the preferred term
- for barcode files we use `cell barcode`
