### ISSUE TITLE
E-MTAB-9841 - MammaryLactactingCells

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1023]
### Associated files

* Google Drive: [https://drive.google.com/drive/folders/1k5_XmKEKVrvb5Bm7bsNU3d05htI0oqhH?usp=share_link](https://drive.google.com/drive/folders/1k5_XmKEKVrvb5Bm7bsNU3d05htI0oqhH?usp=share_link)
* Ingest: [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=e956e66a-ac8e-483a-963a-0f92c7e5abfb)

### Published study links

* Paper: [Transcriptional changes in the mammary gland during lactation revealed by single cell sequencing of cells from human milk](https://www.nature.com/articles/s41467-021-27895-0)

* Accessioned data: [arrayexpress_batch1](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-9841)
[arrayexpress_batch2](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-10855)
[arrayexpress_batch3](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-10885)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Hi Arsenios, I'm done with the secondary review! You did a great job with this dataset!
I have some comments on fields you can fill in and a few about best practices, let me know if you have any questions. 

### Project
- some contributors have England listed for the country, it would be better to swap it for United Kingdom because England is a region within the United Kingdom

### Sepcimen from organism
- `NMC1B_L1, NMC1B_L2 , NMC1B_L3` are lane replicates but the original sample is the same for all of them and it was processed in the same way. You can use only `NMC1` to represent the specimen.
- you can add preservation `cryopreservation, other` for all breast specimens
- you can add preservation `cryopreservation, other` for all milk specimens marked as viably frozen
- `LMC2` and LMC2B`  are the same sample but they were stored in two different ways, you can describe that using the storage/processing fields

### Cell suspension
- the milk tissue should have an enrichment protocol applied to it `density gradient centrifugation` to explain how the cells were isolated from their matrix. Dissociation protocols are only applied to a solid tissue that has to be broken down
- the experiment accessions is not needed here, they are only needed for the sequence files to represent the sequencing experiment

### Sequencing protocol 
- you can remove the library preparation form the description
- you can add the fastq creation method and version

### Sequence file
- you could fill in the read length
- files `MUC9105.R1.fastq.gz, MUC9105.R2.fastq.gz` should have v2 library preparation and sequencing
- you can group the file in process based on their experiment accession, the lane parameter can be used to group them 2-by-2 or 3-by-3

### Analysis protocol
- the `computational method` field was used by our pipelines team but they are no longer workinf with us, so the field is now used to capture the software used for analysis, like Seurat, AnnData ...

### Analysis file
- NMC4_cell_suspension doesn't have any barcode file, the file is not available in ArrayExpress. It would be a good idea to get in touch with the authors and ask for the missing file
- for the matrix file `Count matrix` is the preferred term, gene expression matrix is more specific for microarrays
- for feature files we use `feature table` 
- you can add the cell count for the matrices
- the information on reference genome is conflicting: the paper says hg19 (so GRCh37) but the ArrayExpress accession say either GRCh38 or genome ensemble release 94, which [I think is GRCh38 ](http://oct2018.archive.ensembl.org/Homo_sapiens/Info/Annotation)

**Comment by arschat** [comment]
Contacted authors for genome version, and missing NMC4_cell_suspension barcode file.

**Comment by arschat** [comment]
Authors provided the genome version (the arrayExpress) as well as the missing file (although it was sent privately it contains cell barcodes). Will proceed with a new complete submission and export.

**Comment by Wkt8** [comment]
Surgically removed duplicated files in the terra staging area (file descriptor and supplementary files.json)
