### ISSUE TITLE
PRJNA379992 - Single cell RNA sequencing to dissect the molecular heterogeneity in lupus nephritis

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1063]
### Associated files

* Google Drive: [PRJNA379992_Der_LupusNephritis_Hiseq](https://drive.google.com/drive/folders/1VgyhiUYwSIMnHeGh1hFIA1lewp-XdZFw)

### Published study links

* Paper: **Included data** [Single cell RNA sequencing to dissect the molecular heterogeneity in lupus nephritis](https://insight.jci.org/articles/view/93009)

* Accessioned data: [PRJNA379992](https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA379992&o=acc_s%3Aa)

* [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=4627f43e-a43f-44dd-8c4b-7efddb3f296d)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch witht the authors to request it

**Comment by ESapenaVentura** [comment]
Need contributor contact:
- Missing analysis
- Some metadata misinformation

**Comment by idazucchi** [comment]
The dataset is stuck in graph validation - we are waiting on dev fixes

**Comment by arschat** [comment]
@Wkt8 to help graph validate locally

**Comment by Wkt8** [comment]
Assigning self for secondary review

**Comment by Wkt8** [comment]
Donor_Organism:
Under the 'disease' field, enter 'normal' for the donor_organisms that are marked as healthy instead of leaving them blank 

Would be great if we could incorporate the stage of lupus (II/III/IV/V) into the donor_organism description 

Collection_Protocol:
Not necessary, but I would split up the skin collection and renal collection protocols into two different protocols, and use the ontology term for 'biopsy' (https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009120) for the skin collection and EFO:0009293 (percutaneous kidney biopsy) for the kidney collection protocol. 

Specimen_from_organism
There's a specimen for the 'healthy blood' from 'healthy controls' but there is no link to it to a specific organism. I saw that there is a BioSamples accession for the sample Metro_PBMC (SAMN06661569) but there's not really any information attached. Nonetheless, we need to be consistent and have the specimen_from_organism linked to a donor_organism even if the donor_organism has minimal metadata so that the downstream systems are able to parse the data. 

I would recommend creating a 'donor_31_Metro_PBMC' donor, and linking the Metro_PBMC specimen to it.  

Or alternatively, removing the blood specimen all together as it doesn't seem to be linked to any further cell suspension or sequence file. 

Library_preparation
I'm a bit confused about the Fluidigm-C1 based library preparation, but we have a row in the assay cheat sheet ( https://docs.google.com/spreadsheets/d/1H9i1BK-VOXtMgGVv8LJZZZ9rbTG4XCQTBRxErdqMvWk/edit#gid=0) which states that it is 'full length' end bias and only generates 1 fastq per cell, which matches up to the sequence_file tab. Maybe change the end bias to match that? Also not sure where you got the information for the cell barcode and umi barcode lengths, please share as I couldn't find it!
