### ISSUE TITLE
Kylie James Colon Immune cells 10x SS2 VDJ

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#109]
**Primary Wrangler:**
Marion

**Secondary Wrangler:**
Paris

**Update Wrangler:**
Ami
Google Sheet: https://docs.google.com/spreadsheets/d/1xlcZoazYYRHa6s7bJ8CTlUvNzH4VY6Sx/edit#gid=2086383383

original tracking ticket here: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/179

Created this ticket to track updates to make ready for DCP2

**Comment by mshadbolt** [comment]
I have updated the project with relevant accessions and it is almost ready here: 
https://ui.ingest.archive.data.humancellatlas.org/projects/detail?uuid=83f5188e-3bf7-4956-9544-cea4f8997756

Metadata issues is that I could not add some accessions for where biomaterials have a one to many relationship with accessions where the field is not an array. For example, the cell suspensions that were split into gex and vdj, have multiple sample, run and experiment accessions but only one is allowed in the schema.

Blocking issue is that even though I transferred the files to the ingest upload area, the files don't appear to be validating.

**Comment by mshadbolt** [comment]
Re-transferred all files via the hca cli and all files are now valid and ready for export

**Comment by ami-day** [comment]
Updated the spreadsheet to link the multiple experiment accessions and biosample accessions per unique cell suspension subjected to all of gex & vdj_TCR & vdj_Ig.

**Comment by ami-day** [comment]
Made the same updates to the project itself in ingest only for the BioSample accessions list: https://contribute.data.humancellatlas.org/submissions/detail?uuid=52e21998-8500-46db-8f22-ea6b1eaf67c0&project=83f5188e-3bf7-4956-9544-cea4f8997756
For some reason it is not possible to edit the cell suspension experiment accession field, it doesn't appear in the edit options.

The metadata is now invalid, because the metadata schema doesn't yet support arrays for the BioSample and INSDC experiment accession fields. I will create a metadata schema update ticket and link it to this ticket.

**Comment by ofanobilbao** [comment]
@ami-day is there a metadata-update ticket already or even is this still blocked?

**Comment by ami-day** [comment]
Still blocked by this

**Comment by ESapenaVentura** [comment]
How are there multiple accessions associated to the same biomaterial?

**Comment by ami-day** [comment]
Marion was the wrangler who curated this dataset, she had linked a cell suspension to each of: 10x_v2_5p_gex_library_prep_protocol, 10x_v2_5p_vdj_TCR_library_prep_protocol, 10x_v2_5p_vdj_Ig_library_prep_protocol. Each of these 3 were linked to a different experiment accession. I believe it was because this is how it was captured in NCBI/ENA.

10x_v2_5p_gex_library_prep_protocol
--
10x_v2_5p_vdj_TCR_library_prep_protocol
10x_v2_5p_vdj_Ig_library_prep_protocol

**Comment by ofanobilbao** [comment]
This dataset was meant to be discussed at a wrangler catch-up. @ESapenaVentura @Wkt8 @idazucchi was it discussed already?

**Comment by ofanobilbao** [comment]
@ESapenaVentura to summarise discussions for this dataset here

**Comment by ofanobilbao** [comment]
@ofanobilbao to mark stalled in Ingest
