### ISSUE TITLE
GSE128169 - SclerosisHumanLungCITESeq

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1134]
### Primary Wrangler:
Arsenios

### Secondary Wrangler:
Ida

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1P1hQvwpwGHSXu430BwQmEKhKoKc5vgd-?usp=drive_link)
* Ingest: [457d0bfe-79e4-43f1-be5d-83bf080d809e](https://contribute.data.humancellatlas.org/projects/detail?uuid=457d0bfe-79e4-43f1-be5d-83bf080d809e)

### Published study links

* Paper: [pmed free](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7255436/)
[No access in Annals of Rheumatic Diseases](https://ard.bmj.com/content/78/10/1379.long)

* Accessioned data: [GSE128169](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE128169)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Sample to donor mapping is implied but not verified.
It is mentioned in the paper that there are 8 donors, and in [Table 1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7255436/table/T1/?report=objectonly) we see that more samples from the same donor, as they share the same age, sex, mPAP, PVR and Immunosuppression.

Emailed authors for verification but received an out-of-office until next Monday auto-reply.

**Comment by ofanobilbao** [comment]
@idazucchi to potentially secondary review this when ready

**Comment by arschat** [comment]
Uses samples from #891

**Comment by arschat** [comment]
Graph valid & ready for sec review.

**Comment by idazucchi** [comment]
the project looks good!
I have a few comments

### Specimen
- I think storage method should be empty and preservation: fresh, since the lung portion used for scRNAseq was processed immediately
> Sections were allocated for formalin fixation, preservation in RNA Later, and immediate digestion for scRNA-seq.
- `known disease` should be systemic sclerosis + pneumonia, 
-  shouldn't `SSC_11` have usual interstitial pneumonia as known disease?  the description says "_Predominately UIP with sections of NSIP_"
- if available use MONDO terms for pneumonia over HP


### Dissociation
- `scRNA_mechanical_dissociation` description has … in the middle, is something missing?

### Cell suspension
- `SSC_9_CS` and `SSC_10_CS` are cite-seq sample right? they should have the same processing as the other cite-seq samples
