### ISSUE TITLE
E-MTAB-12421 - ArutyunyanHumanPlacenta

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1146]
### Project short name: 
ArutyunyanHumanPlacenta

### Primary Wrangler: 
@arschat 

### Secondary Wrangler:
Ida

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1tZdTm95zOs3tGwn9xPSIy8VtlRGW4xum?usp=drive_link)
* ingest: [aecfd908-674c-4d4e-b36e-0c1ceab02245](https://contribute.data.humancellatlas.org/projects/detail?uuid=aecfd908-674c-4d4e-b36e-0c1ceab02245)

### Published study links

* Paper: [Spatial multiomics map of trophoblast development in early pregnancy](https://www.nature.com/articles/s41586-023-05869-0) *Official HCA publication*

* Accessioned data:
[E-MTAB-12421](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-12421) scRNA-seq and snRNA-seq of primary tissue
[E-MTAB-12595](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-12595) multiome snRNA-seq and snATAC-seq
[E-MTAB-12698](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-12698) Visium
[E-MTAB-12650](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-12650) scRNA-seq and snRNA-seq of PTOs
Available analysis files https://www.reproductivecellatlas.org/mfi.html

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [x] Upload sheet to validate metadata
- [x] Transfer raw files to ingest to validate data files
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
### Notes
- In the Supplementary Table 1, in the spreadsheet "D - Organoids", each sample contains specimens from multiple donors since the data were pooled. Some of the donor_ID that are used however, are not listed in the "F - Donor" spreadsheet. Specifically donor_IDs 1,2,3,4 are not listed while donor_IDs 5,6,7,8 are listed in the "F - Donor" tab.

**Comment by arschat** [comment]
Error in submitting to ingest:
> An error occurred parsing the file: AttributeError.
> 
> sheet=Project - Publications row=0, column=5, value=True, error='bool' object has no attribute 'lower'

**Comment by arschat** [comment]
Graph valid, ready for sec review!

**Comment by idazucchi** [comment]
Hi! You've done a great job on a very complicated dataset!
I have some comments, let me know what you think

Project
- supplementary links need to be on 2 separate lines in the ui or || in the spreadsheet for the links to be formatted correctly
- you can add the SRA project accessions

Donor
- donor 1-8 for organoid experiments are not described in the supplementary table, are tissues from donors 5-8 used for both organoids generation and scRNA-seq?
- fill in gestational age for embryonic and fetal donors
- fetal stage starts at 12 weeks post conception, so most donors are `embryonic human stage`. If the carnegie stages are available (CS) it's good practice to record them in the devolpemntal stage

Specimen
- in the analysis file there are only decidua samples for P14 and P13
- the decidua is the maternal part of the placenta, to be accurate we should model it like the [published project](https://contribute.data.humancellatlas.org/submissions/detail?uuid=46fe8bd7-329b-4f09-b227-5ee48c109c16&project=f83165c5-e2ea-4d15-a5cf-33f3550bffde) 


Cell line
- can add adherent for culture environment for BTS5 + BTS11
- why are BTS5 + BTS11 turned into 1 cell line?
- cell line a, b and c are not needed

Organoid
- add organoid age (D0, D5, D8)
- growth environment is free text but it has the same information as the differentiation protocol. you could fill it in as matrigel instead or even leave it empty
- I would model the TSC organoids with 1 organoid per cell line. The organoids are pooled later on at the analysis cell suspension level
- I would model the PTO organoids using the specimens as input rather than the cell line, one organoid per donor. you can pool them at the cell suspension level

CS
- you can add a dissociation protocol for the organoids


Library
- multiome library protocols have the input nucleic acid swapped

Imaging
- where did you find the magnification factor?

Image file
- scale factors can have `image metadata` as content

analysis file
- differential analysis can have [`differential expression analysis data`](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0002584) as content

**Comment by arschat** [comment]
Thanks for all the comments, Ida! I will incorporate the changes in the following days.

I also write down that in `Cell suspension` tab, the organoids origin should be in `organoid.biomaterial_core.biomaterial_id` not `specimen_from_organism.biomaterial_core.biomaterial_id`.

**Comment by arschat** [comment]
Thanks again, Ida! I added all your comments, and answered some questions, or added comments.


# Project
- [X] you can add the SRA project accessions
	* added EGA accessions as well

# Donor
- [X] donor 1-8 for organoid experiments are not described in the supplementary table, are tissues from donors 5-8 used for both organoids generation and scRNA-seq?
	* You are right, the two are different. Organoids are from [Turco et al. 2018](https://www.nature.com/articles/s41586-018-0753-3) while donors 6-12 for scRNA-seq are from [Vento-Tormo et al. 2018](https://www.nature.com/articles/s41586-018-0698-6). The latter is already in [DCP](https://data.humancellatlas.org/explore/projects/f83165c5-e2ea-4d15-a5cf-33f3550bffde). The age match but initially I didn't do the conversion to gestational age, and that's why I thought they didn't match.
- [X] fill in gestational age for embryonic and fetal donors
	* converted PCW age to gestational age by adding 2 weeks in PCW
- [X] fetal stage starts at 12 weeks post conception, so most donors are embryonic human stage. If the carnegie stages are available (CS) it's good practice to record them in the devolpemntal stage
	* converted the develpemental stage to CS based on [this](https://hdbratlas.org/staging-criteria/carnegie-staging.html) table
	* for the conversion I did add 2 weeks
	* based on the ontology description, fetal stage starts at 56th day i.e. 8th week.

# Specimen
- [X] in the analysis file there are only decidua samples for P14 and P13
	* based on the [adata.obs](https://www.reproductivecellatlas.org/mfi/all-cell-states/)['tissue'] I mapped the samples/cell suspensions to specific tissues. P13_placenta was indeed not added in analysis files input althought it should be. However, P14 has only `decidua_myometrium` tissue. The different organ parts were not torn appart so I thought I should not add another specimen and make this more complicated. I added however, the myometrium to the organ part for decidua specimens of P13 and P14.
- [X] the decidua is the maternal part of the placenta, to be accurate we should model it like the published project
	* Remodel donors & specimens based on the published project.

# CS
* Wrong input specimen for multiome subset
* added input organoid for organoid subset instead of input specimen

# Imaging
- [ ] where did you find the magnification factor?
	* I probably filled the thickness accidentally. I can se no magnification factor given.

**Comment by arschat** [comment]
Still no reply, [ping Anna again](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/yrPn8RlGqns/m/qw0ag_iJAwAJ).

**Comment by arschat** [comment]
Anna Arutyunyan replied:
> Apologies for my very later reply,
> 1. Donors 6,7,8 in Supplementary Table 1 tab "D - Organoids" are different donors without any metadata available (third option in your email) - Roser please correct me if you know otherwise
> 2. Sorry but I am not sure what magnification was used - I am checking this now with a team member and will get back to you hopefully soon.

Gestational age from donors that provided organoids should be removed.
We will have to wait for the magnification.

**Comment by arschat** [comment]
- [X] Exported
- [ ] Import form filled

**Comment by arschat** [comment]
dropped from release 32 since there were problems and re-export was not succesful. discussed [here](https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1698935190931359)

**Comment by idazucchi** [comment]
to re-export metadata for R34 - currently stuck in exporting

**Comment by idazucchi** [comment]
@arschat to discuss action needed with Enrique

**Comment by arschat** [comment]
- [X] Re-export was completed (delayed)
- [X] Verified that project metadata were there 
> gs://broad-dsp-monster-hca-prod-ebi-storage/prod/aecfd908-674c-4d4e-b36e-0c1ceab02245/metadata/project/aecfd908-674c-4d4e-b36e-0c1ceab02245_2023-09-18T15:47:04.267000Z.json
- [X] Import form sent

**Comment by arschat** [comment]
Verified in browser[.](https://dcp2.data.humancellatlas.org/explore/projects/aecfd908-674c-4d4e-b36e-0c1ceab02245?catalog=dcp35)
