### ISSUE TITLE
GSE128243 - nktpbmcZhou

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#118]
**Primary Wrangler:**
Enrique
**Secondary Wrangler:**
Marion

**Associated files:**

Google Drive: https://drive.google.com/drive/folders/14-OUakV7yCQExJAtNn9VN7u-xazWOoEz

**Published study links**

Paper: https://www.frontiersin.org/articles/10.3389/fcell.2020.00384/full#F1

Accessioned data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE128243

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production

**Comment by ESapenaVentura** [comment]
- Metadata is in the google drive folder and s3 bucket is indicated in a google document in the same folder

- Ingest-graph-validator tool tests were run successfully 
   - Did some extra research and the graph seems valid: 3 donors, each 2 specimens, each specimen a cell suspension and each cell suspension links to 3 files 
![graph](https://user-images.githubusercontent.com/38617863/90510386-ceb8b200-e152-11ea-989f-1d8e4c2c1582.png)


- Data files are valid in ingest: https://ui.ingest.archive.data.humancellatlas.org/submissions/detail?uuid=8d045afd-cebf-4b3f-80df-a06d751a3413&project=2a32d3e2-1cfb-4c15-90bc-689102b1b638

**Comment by ESapenaVentura** [comment]
@mshadbolt has agreed to be the secondary wrangler

**Comment by ESapenaVentura** [comment]
**UPDATE**: 

- I just noticed the cell suspension is missing the `selected_cell_types` (Natural killer cells), will add them after the review

**Comment by ami-day** [comment]
Ami Secondary review:

**Edited version:** https://docs.google.com/spreadsheets/d/1VovZyygCNPI87doP3G0GgcZPdxI_B4Ix/edit#gid=1885177057

**Project**
- The insdc project and study accessions need to be swapped

**Contributors**
- The primary wrangler name is surname,,firstname (Sapena Ventura,,Enrique). It should be firstname,,surname
- There is no primary contact email address. I suggest we search for  the first author's email when this happens.
- The address was given in full in the department column, it needs to be split into the multiple columns.

**Collection protocol**
- I changed the description to "A blood draw was performed on the donors at Henry Ford hospital" as the wording was not quite right.

**Specimen from organism**
- Some of the "specimen_from_organism.biomaterial_core.biomaterial_name" values were switched around (some say "stimulated" as opposed to "unstimulated" according to the 'specimen_from_organism.biomaterial_core.biomaterial_id" and "specimen_from_organism.biomaterial_core.description"
- The first "specimen_from_organism.biomaterial_core.ncbi_taxon_id" says '9605' instead of '9606'

**Cell suspension**
- Compared to the 'specimen from organism' tab, the "unstimulated" samples are listed before the "stimulated" samples. This is not a problem, but it might be worth double checking that associated sample information was not accidentally swapped (e.g. if you pasted any information from the 'specimen from organism' tab.
- I suggest copying the "cell_suspension.biomaterial_core.biomaterial_name" values to the "cell_suspension.biomaterial_core.description" column too

Other than that, **looks good!**

**Comment by ESapenaVentura** [comment]
Thanks for the review Ami!

- I have added the email that appears in GEO and added that as a corresponding contributor
- I have looked at your corrections and applied them!

I think it's good to go!

**Comment by ESapenaVentura** [comment]
Dataset is ready for export. Closing the ticket!

**Comment by ofanobilbao** [comment]
@ESapenaVentura I have moved this to Finished on the Wrangling board as I believe the DCP journey is complete. Please, feel free to amend if I did not get it right. Thanks!
