### ISSUE TITLE
GSE156972 - FetalSkinDevImmune

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1188]
### Project short name:
FetalSkinDevImmune
### Primary Wrangler:
Ida
### Secondary Wrangler:
Anu

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1kkZFYZLlASrhPvLAjZFULudDjM7Fy8-Y?usp=drive_link)

### Published study links

* Paper: [αβγδ T cells play a vital role in fetal human skin development and immunity](https://doi.org/10.1084/jem.20201189)

* Accessioned data: [GSE156972](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156972)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc35f94e-e93b-4dbd-a08c-702978d9046f)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
**Cell suspension**
I've modelled the CS by pooling 2 cell suspension for each donor: T cells + non-enriched skin cells
I did it this way to have 1 cell suspension used to create the library, given the discussions around library id
I'm not sure adding `skin cell` to the enriched cell suspension is correct, maybe it should be empty?

**Comment by anu-shiva** [comment]
Hi Ida! the filled-in data looks great. Just very minor comments/ques-

**Specimen/donor**
Skin of body ontology is accurate but I am curious when is  **embryonic tissue** ontology term favored?

**Analysis protocol** 
The paper says '**without depth normalization**' - could this be removed from the Derivation process if depth normalization was not performed?

 **Analysis file** 

- The matrix file on GEO is in h5 format. I am assuming here that you have uploaded it as **.gz** as you mentioned .gz in the file name and file format.
- Could **cell type identifier** be better over 'cell type name' for ontologising  the cell annotation files- as the files list barcode as identifier for cells- they are not real names
- The content description field for the count matrix could be modified to add processed (the file name says raw!) for a clarification?

**Formatting** 
In some tabs like Enrichment, Library prep etc., the numbers are formatted with **.** instead of **,**  as it was on GEO (continental system). Would it be better to uniformise the numerical format with a **,** instead?

**preservation method** - Only the Immunofluorescence section of the paper mentions that-
Tissue specimens were embedded in an optimal cutting temperature formulation (Tissue Tek), snap frozen in liquid nitrogen, and stored at –80°C until further processing. This doesn't go true for preservation method, does it?

**Comment by idazucchi** [comment]
Amnon exported the dataset, import form filled out

**Comment by idazucchi** [comment]
verified in browser
