### ISSUE TITLE
GSE181764 - DendriticCellActivationHCM

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1227]
### Project short name:
[DendriticCellActivationHCM](https://contribute.data.humancellatlas.org/projects/detail?uuid=e1fda217-7ee1-4c1a-adfa-648279dafac6)
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/10bVbu93jUeVDu7KRZUy2OB2h8ozTVa12?usp=drive_link)

### Published study links

* Paper: [Single Nucleus RNA-sequencing Reveals Altered Intercellular Communication and Dendritic Cell Activation in Nonobstructive Hypertrophic Cardiomyopathy](https://doi.org/10.26502/fccm.92920277)

* Accessioned data: [GSE181764](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE181764)

[**Ingest**](https://contribute.data.humancellatlas.org/projects/detail?uuid=e1fda217-7ee1-4c1a-adfa-648279dafac6&tab=project)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
the accessions contains both healthy donors, described in table 2, and disease donors, described in table 1

the files available are bam --> I'll start the conversion as soon as possible

**Comment by idazucchi** [comment]
I'm having issues syncing the files to ingest - the sync is succesful, the data is the staging bucket but ingest can't see them
discussed this with Enrique and it sounds like faulty communication between the upload api and aws
We're waiting till Monday to see if this resolves, if not I'll test other projects/staging I wonder if it's down to this specific project

**Comment by idazucchi** [comment]
tried again to sync files - both in prod and [staging](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=feb78d3d-6204-499d-82cb-369f8a7f1bf3&project=90df3eb6-bffa-4959-9422-ff77810c27ea) - but ingest can't see the files despite them being in the s3 bucket

**Comment by idazucchi** [comment]
temporarily skipping graph validation due to the issues with HCA-util - the dataset is ready for secondary review

**Comment by arschat** [comment]
Hi Ida! Great work!
It is weird that GEO mentions an extra donor that is never mentioned in the tables and in the manuscript, but I agree with including this.

Also, it's not clear to me if the 4 donors that are mentioned in the healthy Table 2 (2867, 2879, 2880, 2884), (data uploaded here [GSE161921](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE161921)) are used first in this paper or in the [BMC Med Genomics'](https://doi.org/10.1186/s12920-021-01011-z) one or maybe another one. I mention that because I can see that in Figure 2 C there is a mention of those healthy donors.

Everything else it quite great, the only comments I would like to make is:
* `analysis_file.matrix_cell_count` could be included in the metadata
* `sequence_file.read_length`could be included in the metadata
* `analysis_protocol.alignment_software_version` since manuscript and GEO is contradictory (manuscript `v6.0.1`, GEO `v3.0.0`), and given we still cannot get in contact with authors, it is totally up to you which one would you prefer.

**Comment by amnonkhen** [comment]
blocked by ebi-ait/dcp-ingest-central#988

**Comment by idazucchi** [comment]
**hca-util sync**
the issue is fixed, all the files are valid

**Donors**
the 4 donors that are mentioned in the healthy Table 2 (2867, 2879, 2880, 2884) [[GSE161921](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE161921)] were used first the [BMC Med Genomics' paper](https://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-021-01011-z). They were reused here as controls with 2 new additional healthy donors

Thank you for reviewing this so quickly! 
I've made the changes and I'm exporting

**Comment by idazucchi** [comment]
verified in browser
