### ISSUE TITLE
GSE197518 - MacrophagesElicitAF

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1237]
### Project short name:
MacrophagesElicitAF
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1ELBZwFYl5yTlSpyWHhh4NxQu0Wuh_nHZ?usp=drive_link)

### Published study links

* Paper: [Recruited macrophages elicit atrial fibrillation](https://doi.org/10.1126/science.abq3061)

* Accessioned data: [GSE224959](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224959) superseries
      * [GSE197518](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197518) human ~~+ mouse~~
      * ~~[GSE224947](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224947) mouse~~
      * ~~[GSE225671](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE225671) mouse~~
      * DUOS at DUOS-000150

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=9483c664-d546-4b30-9ba3-efbdbf9290b4)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
I've left the mouse data out for now so I only added to the project the GEO accession that contains human data and none of the INSDC ones

Ready for secondary review!

**Comment by idazucchi** [comment]
I've left the mouse data out for now so I only added to the project the GEO accession that contains human data and none of the INSDC ones

Ready for secondary review!

**Comment by anu-shiva** [comment]
Hi Ida, as we spoke, only the donor disease columns needs to be revised :)

**Comment by idazucchi** [comment]
filled in import form

**Comment by idazucchi** [comment]
verified in browser

**Comment by arschat** [comment]
After sharing the published project in DCP with contributors, we received the following email.
> Dear HCA Ingestion and Outreach Team,
I attached a corrected version of the metadata file. Can you please correct accordingly?
Best,
Maarten

The spreadsheet contains corrections:
- contributor names for example `Patrick T,,Ellinor` v/s `Patrick,T,Ellinor`
- added emails for all corresponding authors
- addition of two grand_IDs `19CDA34490005`, `18SFRN34110082` from `AHA`
- assignment of all the cohort level donor metadata, at the specific patient level. In the [Supplementary Table 1](https://www.science.org/doi/suppl/10.1126/science.abq3061/suppl_file/science.abq3061_sm.pdf) we can see that all but one donor is labeled white, all but one donor has Hyperlipidemia. In the corrected spreadsheet, the contributor specifies the one who is not white & who does not have hyperlipidemia. This information specified for each donor was not previously public, and we should be very cautious on how to handle this.
- assignment of the sex metadata at the donor level. This is included in the [GEO accession](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197518) for all the samples.
- syntactical corrections in the specimen name & specimen description & specimen disease & cell suspension description (`heart tissue` instead of `heart`, lowercase for disease text)
- minor and syntactical corrections in protocols descriptions (removal of reference numbers, added fullstop, removal of redundant parts in description

**Comment by arschat** [comment]
After informing contributor about potential dangers of adding metadata, they removed request for updating ethnicity & known diseases. We can now update all other requests for R39.

I will update project on ingestUI, export and fill import form.

**Comment by arschat** [comment]
Exported & import form sent

**Comment by arschat** [comment]
Update verified in [browser](https://explore.data.humancellatlas.org/projects/9483c664-d546-4b30-9ba3-efbdbf9290b4?catalog=dcp39).
