### ISSUE TITLE
GerliAmnioticFluid

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1254]
### Project short name:
GerliAmnioticFluid
### Primary Wrangler:
Ida
### Associated files:

* Google Drive: [folder](https://drive.google.com/drive/folders/1rOEnk6nogF3uGDm42KZpY-G-dfbq5cp9)
* [paper](https://www.nature.com/articles/s41591-024-02807-z#Sec10)
* [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=19037ec9-43a7-4823-b93f-9e59c694d17e) 

### Key Events

- [ ] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [ ] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [ ] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [ ] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by idazucchi** [comment]
we've done the first round of reviews, I'm now checking the revised spreadsheet


To do:
 - [ ] get missing fastq
 - [ ] organoid modelling -> one organoid representing multiple organs?
 - [ ] fix linking
 - [ ]

**Comment by arschat** [comment]
Hi Ida! Nice work on a complex dataset and with collaborating with contributors! Here are my comments.

### Project
- `supplementary link` is the deposit page which is not accessible, while [record page](https://zenodo.org/records/8124205) is

### Project - contributors
- `Contact name`s are not in the correct format `First name,middle name or inital, Last name`
- `Institute` contains also `department` information and we may change `UCL` to `University College London`

### Project - publication
- `publication title` differs from the published one ("single cell-guided" instead of "single-cell guided"). Note that in zenodo and GEO the title with the dash before guide is used.

### Donor
- `sex` on the [supplementary table](https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-024-02807-z/MediaObjects/41591_2024_2807_MOESM1_ESM.pdf), donor's H9680 sex is `F` while in the spreadsheet it's male. In GEO's metadata as well sample 17PCW_680 is listed as male too.

### Specimen
- `collection protocol` for specimen `H0696` is not listed in the [supplementary table](https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-024-02807-z/MediaObjects/41591_2024_2807_MOESM1_ESM.pdf) (marked as /) but we can assume that this was the way it was collected

### Analysis files
- GEO submission contains also seurat rds object. Would the contributors like to include these in the submission? They might not.

### copliments
- Very nice addition the mapping of collection method to ontology while keeping the percise method in the text field
- Very nice addition the length of reads fastqs in the seq_protocol description

**Comment by idazucchi** [comment]
Thanks for reviewing and thanks for the compliments!

### Publication
I kept the publication title as you suggested, so that we avoid issues with matching titles in the future
### Donor
I checked with the authors, this is the explanation for the mismatch
> We double checked for this with our clinical collaborators but unfortunately there is some discrepancy. While according to their scan the fetal sex is female, our bioinformatic analysis based on SNP demultiplexing and XIST and SRY gene expression, the fetal sex is male. Therefore, we would like to keep male consistent with the data analysis.

### Analysis files
I've asked if they were interested in depositing analysis files but they didn't reply, so I assume they are not interested in it

**Comment by idazucchi** [comment]
Contributors have condirmed they are ready to publish - I'm exporting

**Comment by idazucchi** [comment]
project exported correctly, import form filled out for R42

**Comment by idazucchi** [comment]
reviewed in browser
