### ISSUE TITLE
E-MTAB-13687 - MassoniBadosaHumanTonsil

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1255]
### Project short name:
MassoniBadosaHumanTonsil
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1wzanxnKiyBe8CS2lHx4pgc9M7EPRvBOU?usp=sharing) 

### Published study links

* Paper: [An atlas of cells in the human tonsil](https://doi.org/10.1101/2022.06.24.497299)

* Accessioned data: [E-MTAB-13687](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-13687)

[Ingest - preprint](https://contribute.data.humancellatlas.org/projects/detail?uuid=51e54271-89c4-413c-8c07-c88b318d6222)
[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=0cc58d0b-1734-4e1d-9113-b32e52f75e36)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
### Imaging
Unclear microscopy setup, no magnification specified

### Files

#### Visium
I'm not sure if we want to keep the html summary files + the metric_summary
I'm removing:
- tonsil_atlas_donor_metadata.csv - just donor metadata we already have
- V10M16-059.gpr, V19S23-039.gpr - layout file in `gpr` format for the slide spots, [can be obtained from 10x](https://www.10xgenomics.com/support/software/space-ranger/latest/analysis/inputs/image-fiducial-alignment)

**Comment by idazucchi** [comment]
I've swapped the doi of the pre-print for the publication's one
I've created a new project in ingest for the publication, the pre-print is still in ingest as not elegible --> we can revise but we should keep track of the doi since it's an bionetwork paper

**Comment by arschat** [comment]
Very admirable job, Ida! Huge dataset, with many and complex designs.
Excellent work, more power to your elbow!

So, here are my comments.

### Project
- Contributors, move middle name initial between commas instead of first name
- Publications, remove space after double pipe
- Funders, although europePMC has 3 funding entries, in the acknowledgements there are multiple grant IDs
<details><summary>Funding table</summary>

| Grant ID | Funding Organization | 
| -------- | -------------------- |
| 810287 | European Research Council (ERC) under the European Union’s Horizon 2020 Research and Innovation Programme |
| PID2020-115439GB-I00 | Ministerio de Ciencia e Innovación (MCI) |
| PID2020-118167RB-I00 | Ministerio de Ciencia e Innovación (MCI) |
| RTI2018-094274-B-I00 | Ministerio de Ciencia e Innovación (MCI) |
| PI19/01772 | Spanish Instituto de Salud Carlos III, Fondo de Investigaciones Sanitarias, co-funded with ERDF funds |
| unspecified | Spanish Ministry of Science and Innovation through the Instituto de Salud Carlos III and the 2014–2020 Smart Growth Operating Program |
| BIO2015-71792-P | MINECO/FEDER, European Regional Development Fund |
| unspecified | Centro de Excelencia Severo Ochoa and the Generalitat de Catalunya |
| 2021-SGR-1172 | Suport Grups de Recerca AGAUR |
| 2021-SGR-1343 | Suport Grups de Recerca AGAUR |
| unspecified | Accelerator award CRUK/AIRC/AECC joint funder-partnership |
| CB16/12/00225 | CIBERONC |
| CB16/12/00334 | CIBERONC |
| KU1315/14-1 | Deutsche Forschungsgemeinschaft (DFG) |
| HA5354/10-1 | Deutsche Forschungsgemeinschaft (DFG) |
| HA5354/12-1 | Deutsche Forschungsgemeinschaft (DFG) |
| SPP1937 (HA5354/8-2) | Deutsche Forschungsgemeinschaft (DFG) |
| HA5354/13-1 | Deutsche Forschungsgemeinschaft (DFG) |
| 220540/Z/20/A | Wellcome Trust |
| 223092/Z/21/Z | Wellcome Trust Senior Research Fellowship |
| unspecified | NIHR Newcastle Biomedical Research Centre |
| unspecified | Lister Institute for Preventative Medicine |
| BIL KLS-5130-08-2020 | Swiss Cancer League |
| unspecified | Nuovo-Soldati Foundation for Cancer Research |
| unspecified | Institucio Catalana de Recerca i Estudis Avancats (ICREA) of the Generalitat de Catalunya |



</details>

### Donor organism
- Nice catch adding the two extra donors
- `Development stage` in AE is not from HsapDv ontology, although similar stage exists like child stage: [HsapDv:0000081](https://www.ebi.ac.uk/ols4/ontologies/hcao/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHsapDv_0000081) and human adult stage: [HsapDv:0000087](https://www.ebi.ac.uk/ols4/ontologies/hcao/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHsapDv_0000087). We usually add the HsapDv ontology field so this would be a decision between consistency among HCA DCP projects or within project across platforms.

<img width="180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3Y2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e90da14b134c1d02946f86f0a16e0cfc6a5f33a7/image.png" alt="image.png" />

### Specimen from organism
- `PRESERVATION METHOD` for the last two specimens it is mentioned 
> For the final part of the study, cryopreserved cells from tonsil samples of two MCL patients were used (age 64 and 80, both male). MCL samples were obtained from cryopreserved dissociated cells from tonsils, from the ICGC case collection of Hospital Clinic, Barcelona. 

we do not know if the specimen was processed (dissociated) fresh or preserved, but since it was preserved at some point, do you think it is worth adding `cryopreservation, other` here?
- Nice catch specifying the **collection_site** in the location field

### Imaged specimen
- There seems to be an error with the accession numbers. Although I could find the accessions in ENA, it is different from the one listed in AE. For example, for visium_sample_1:
    - [spreadsheet accession](https://www.ebi.ac.uk/ena/browser/view/SAMEA115120914)
    - [ae accession](https://www.ebi.ac.uk/ena/browser/view/SAMEA115537509)

Same problem exists in the cell_suspension accessions and run accessions as well. I would guess that there was an update on the AE submission, and they updated all the accession because the Sample Alias of ENA adds a "_2" in the AE provided accession.

### Enrichment protocol
- `markers` could be filled based on the Fig 6F plot, I think it should be mono_dend: `SLAN+ CD14+ CD16+`, slan: `SLAN+ CD14- CD16- CD11C- CD123-`

### Cell suspension
 - There are 13 cell suspensions that are not referenced in any file tab (`scRNA_Sample_15_hashed`, `scRNA_Sample_16_hashed`, `scRNA_Sample_17_hashed`, `scRNA_Sample_1`, `scRNA_Sample_2`, `scRNA_Sample_3`, `scRNA_Sample_4`, `scRNA_Sample_5`, `scRNA_Sample_6`, `scRNA_Sample_7`, `scRNA_Sample_11`, `scRNA_Sample_12`, `scRNA_Sample_13`). Is that on purpose?
- Problem with accessions, see ### Imaged specimen

### Sequencing protocol
- sequencing method text for "ATAC_NextSeq" vs "multiome_snATACseq_sequencing", in the first is `assay for transposase-accessible chromatin using sequencing` while in the second its `single cell assay for transposase-accessible chromatin using sequencing`. Although they have the same ontology, this might be misleading that the first is bulk ATAC.

### Sequence file
- Read index, for libraries that contain 3 read files (for example `MCL.M102.BCLLATLAS_65.kpi1zxjo_542l3n1f.220596.ATAC.P10.R3.fastq.gz`) have `index1` for R2 files and `read2` for R3 files. We have the option to record the read1 up to read4 in our last [sequence file schema](https://schema.humancellatlas.org/type/file/9.5.0/sequence_file), while AE might not have this. In the methods for scATAC it is mentioned that there are R1 R2 I1 I2 files instead. 
    We could either stick to the AE and leave it R2 as index1 and R3 read2, or stick to the filenames, and change it R2 to read2 and R3 to read3.
- You could add ArrayExpress as FILE SOURCE
- Similarly with ### Imaged specimen and ### Cell suspension, run accessions are outdated, and have been [suspended](https://www.ebi.ac.uk/ena/browser/view/ERR12511611).

### Analysis protocol
- Although the alignment software mentioned for `multiome_matrix_generation` is Cellranger, the version is stated to be v1.0 which did not offer the GRCh38 version ([here](https://www.10xgenomics.com/support/software/cell-ranger/latest/release-notes/cr-reference-release-notes#1.2.0)). The command stated also, is cellranger-arc which might be a hint that they used [`Cellranger ARC`](https://www.10xgenomics.com/support/software/cell-ranger-arc/latest/release-notes/release-notes) for multiome ATAC & GEX.

### Analysis file
- Awesome! We could add MATRIX CELL COUNT for some files (based on the number of lines in their _barcodes.tsv). For convenience I added the file that could be extracted here [MassoniBadosaHumanTonsil_matrix_cell_count.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae15ed004524719996509860cd9b7aa0818db33e/MassoniBadosaHumanTonsil_matrix_cell_count.txt)

### Supplementary file
- all 3 files have only the ontology text field for the content description and id & label is missing (maybe a problem with fill_ontologies script and graph validation?)

**Comment by idazucchi** [comment]
Verified in the browser
Something weird is happening:
1. the donor number displayed in the overview is 17 (wrong) but in the download tab it's 19 (correct)
1. the matrix files for 2 donors are missing from the matrices tab but not from the download tab

In case it helps explain the above: the 2 donors above have no sequence files but do have analysis files
Since the files are not actually missing we can move forward with R39 and aim to resolve this issue with R40/R41
