### ISSUE TITLE
E-MTAB-8813 - EmbryonicHindlimb

### ISSUE THREAD

**Issue by arschat** [ebi-ait/hca-ebi-wrangler-central#1265]
Partial previous wrangling in #163
New ticket created for clean track down of wrangling  with current template.

### Project short name: 
EmbryonicHindlimb

### Primary Wrangler: 
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1eLBC3C1Bb39vBmcBDhf9xS_ADvhe8-oa?usp=drive_link)
    [previously partially wrangled spreadsheet](https://drive.google.com/file/d/18cVLJOL63Ytt471gmQhXmKDliDH-wK1J/view)
* ingest: [b176d756-62d8-4933-83a4-8b026380262f](https://contribute.data.humancellatlas.org/projects/detail?uuid=b176d756-62d8-4933-83a4-8b026380262f)

### Published study links

* Paper: [A human embryonic limb cell atlas resolved in space and time](https://doi.org/10.1038/s41586-023-06806-x)

* Accessioned data:
mouse scRNA: [E-MTAB-10514](http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10514/)
human visium: [E-MTAB-10367](http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10367/)
human scRNA: [E-MTAB-8813](http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8813/)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
#Notes 
* mouse scRNA contains data from [GSE137335](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137335) and [GSE142425](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE142425). Projects are not currently on dcp and will wrangle data as well for consistency.

**Comment by arschat** [comment]
Graph valid & ready for sec review

**Comment by idazucchi** [comment]
Hello!
Nice job on pulling together this sprawling dataset!  
There are a couple things I would do differently, see the comments, but let me know what you think

### Project
- remove ; from supplementary links
- add ERP160032  to project accession
- for the cell count I would put 125,955

### Donor
- human donors gestational age: I disagree with keeping the day as a decimal because it's misleading - no one will know it means days instead of 1/10 of a week. Why not put the age in days instead?
- is GA from supp table 5 the gestational age?
- mouse_litter: I would represent each mouse from the litter as a single donor - maybe we can use the family tab?


### specimen
- I would put the sampled location in the organ part, so it's more clear what's being collected and it’s easy to compare with the paper, even if the ontology term isn’t the same as the free text field.
- can we add the organ part for the leg that's imaged in 4 parts?
- how do we know all human scRNAseq specimens come from Addenbrookes?
- do we have to fill in transplant organ for all specimens?
- human scRNAseq: there are only 4 proximal samples according to the h5ad table, so some of them might be thigh
- C1-FSM-0-SC-1 in the description say it's whole limb bud ? more clear
- mouse_litter: I would represent each mouse sample from the litter as an individual specimen
- mouse_litter: the sampling location can go from the name to organ_part
- most of the mouse descriptions have limp instead of limb


### Dissociation
- I would add a mechanical dissociation step for the human and mouse scRNAseq
- kelly specific dissociation can be added, not sure if it’s worth it

### enrichment
- `RBC_lysis` could be non-enzymatic dissociation - when the ontology is working again we might want to request a new term for sample enrichment that can capture RBC

### imaged specimen
- missing description
- I would represent each imaged specimen as a single entity and pool them at the image and sequence file level instead. This way it would be clearer what is imaged

### imaging protocol
- missing name

### cell suspension
- mouse_litter : missing description, can add cell viability method

### sequence file
- human scRNAseq: where do the library names come from? I thought 5386STDY7537944, FCAImmP7536758 and WSSS_THYst9384954 were library names


### Analysis files
- human scRNAseq: the sequencing for the unified h5ad is both HiSeq and NovaSeq
- for WSSS_THYst9384953.tar.gz
WSSS_THYst9384954.tar.gz
WSSS_THYst9384955.tar.gz
WSSS_THYst9384956.tar.gz
WSSS_THYst9384957.tar.gz
WSSS_THYst9384958.tar.gz
WSSS_THYst8796437.tar.gz
WSSS_THYst8796438.tar.gz
WSSS_THYst8796439.tar.gz
WSSS_THYst8796440.tar.gz
WSSS_THYst8796441.tar.gz
WSSS_THYst8796442.tar.gz
 the sequencing protocol should be NovaSeq
- MouseAllData_annotated_filtered.h5ad 230109MouseAllData_annotated.h5ad: add the HiSeq sequencing for Allou samples

**Comment by arschat** [comment]
Thanks a lot for the extensive review Ida!

# Donor
* human donors gestational age. I agree, I changed that based on the GA value. In Fig 1 we can see that the youngest donor is 5+1 PCW, which is 7+4 Gestational Age in days
* After discussion about dividing mouse litter to donors or keep in groups as listed in the publication and AE, we decided to keep it as listed in order to avoid increasing the complexity without providing any more metadata, and in order to keep identifiers aligned across publication and other archives.

# specimen
* how do we know all human scRNAseq specimens come from Addenbrookes? 
    > First trimester human embryonic tissue was collected from elective termination of pregnancy procedures at Addenbrookes Hospital
* do we have to fill in transplant organ for all specimens? I would fill this field with False, only if we have same true values in the dataset
* can we add the organ part for the leg that's imaged in 4 parts? it is all part of `C42-FLEG-0-FO-1` that is devided in 4 **imaged_**specimens 

# sequence file
* library names are derived from the AE submission


Updated also ENA accessions (run & experiment accessions listed in AE are not valid in ENA, but project linked contains other valid run & experiment accessions)

**Comment by arschat** [comment]
project was exported, but staging area contained json files from previous submission. It resulted in failure in validation, and removing old seq files' metadata and descriptors did not fix the error. The uuids that gave errors were appearing in links however, since there were previous biomaterial entities as well that we not used in current submission, we decided to clear staging area and re-export. We will wait for R42 to see if it passed validation. 

Writing down these to fill the [release retro slides](https://docs.google.com/presentation/d/1S3YRzpOo2ZUdgYGkWJBNpcqpnTKqpbBJQ8uByqRVcyU/edit#slide=id.g2ecb9257b67_0_0) when issue is fixed.

**Comment by arschat** [comment]
[verified in browser](https://explore.data.humancellatlas.org/projects/b176d756-62d8-4933-83a4-8b026380262f)
