### ISSUE TITLE
GSE218392 - MyocardialInfarctionAmruteCITE

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1275]
### Project short name:
MyocardialInfarctionAmruteCITE
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/12Lw3oIGJEzBqlcECprCUPleJr7T54_k_?usp=sharing)

### Published study links

* Paper: [Targeting the Immune-Fibrosis Axis in Myocardial Infarction and Heart Failure](https://doi.org/10.1101/2022.10.17.512579)

* Accessioned data: [GSE218392](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE218392) Super-series, found by looking up the title of the publication --> most likely the same [pre-print](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9900986/)
   * [GSE217494](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE217494) - human donors CITE-Seq
   * [GSE218391](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE218391) - human cell line scRNAseq - is it the experiment described in the paper? it's snRNAeq there
   * [GSE270788](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270788) - human donors multiome
   * [GSE270875](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270875) - mouse scRNA-seq on DRAQ5+/DAPI- cells from saline or Ang II/PE infused pumps at day 28
   * [GSE270904](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270904) - scRNA-seq on gated Fap+ and Fap- fibroblasts in Ang II/PE day 7 isotype treated and anti-IL1b mAb treated mice
   * [GSE270961](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270961) - scRNA-seq on DRAQ5+/DAPI- cells in Ang II/PE day 7 isotype treated and anti-IL1b mAb treated mice

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=660fc8b5-8fb8-4050-8c57-e6313195bc81)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
we have heart explanted to be donated for transplant and hearts explanted to be replaced 
the question "Was the specimen collected after extraction for organ transplantation?" could be yes for both, maybe we can rephrase it

**Comment by idazucchi** [comment]
I'm not sure what to do for multiome samples - are the dissociation and collection the same as CITE-seq?

**Comment by idazucchi** [comment]
I don't know what terms to use for 
Ischemic cardiomyopathy
Non-ischemic cardiomyopathy
[cardiomyopathy](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004994) is a bit too generic but I can't find good matches

graph valid!

**Comment by arschat** [comment]
Hi Ida! Very nice work in a very complex dataset. I have only a few minor comments.

### Project - publications
- Since there [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9900986/) second pre-print that's almost but not identical to the biorxiv, does adding another publication for this project makes sense?

### Donor Organism
- `Organ donation death type` is Donation after circulatory death (DCD) while in the publication is mentioned
    > Donor hearts were obtained from brain dead individuals with no known cardiac disease and normal LV function.
- Since that's a bionetwork project, you could also specify the `hardy scale` to 0 for the organ donors
- `known diseases`: In [this project](https://explore.data.humancellatlas.org/projects/85c0d6fa-f117-4d76-b01a-5d5e8f5f9188) the ICM is recorded as [myocardial ischemia](https://ontology.archive.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024644). Non-inschemic is a negative definition and it is highly unlikely that we will find an appropriate ontology, so cardiomyopathy seems a good fit
- `development_stage` maybe too picky but for all cell line donors we also know that's adult from the [NHCF product catalogue](https://bioscience.lonza.com/lonza_bs/GB/en/Primary-and-Stem-Cells/p/000000000000197234/NHCF-V-%E2%80%93-Human-Ventricular-Cardiac-Fibroblasts) and the [iHCF product catalogue](https://maxanim.com/abm-immortalized-human-cells/abm-immortalized-human-cardiac-fibroblasts-t0446/)
    > **NHCF_donor**: Cells are isolated from normal, adult heart tissue
    > **iHCF_donor**: Source Organ: Ventricles (Adult Heart)
