### ISSUE TITLE
GSE168191 - MultipotentCellRgenerateAlveoli

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1290]
### Project short name:
MultipotentCellRgenerateAlveoli
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1-oU4mErf9ElQoK6wiTKdPJKnEObZIabZ?usp=sharing)

### Published study links

* Paper: [Human distal airways contain a multipotent secretory cell that can regenerate alveoli](https://doi.org/10.1038/s41586-022-04552-0)

* Accessioned data:
   * [GSE168191](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168191) - 19 samples COPD+healthy
   * [GSE130076](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130076) - 1 sample HT280neg_Single cell

[ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=5f1a1aee-6c48-4dd4-a2c4-eb4ca6aadf74)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
### GSE130076 
only has one sample but no metadata is available for it so it's impossible to match it up the supplementary table (it could be Donor 7?) - I would rather include minimal metadata for now and amend it later once we get in touch with the contributors

I'm assuming it's a healthy donor since no information is given. I think in this context the distal sample described here is the same as peripheral sample

Cell selection protocol:
>For primary human cells, a single-cell suspension was generated as described above and AT2 cells were isolated using the MACS multisort kit, MACs LS columns and the following antibodies: anti-HT2-280 (mouse IgM, Terrace, TB-27AHT2-280, 1:50) and anti-mouse IgM microbeads (Miltenyi, 130-047-302, 1:200).

**Comment by idazucchi** [comment]
#### ontology
for distal/peripheral lung I'm using [pulmonary alveolar parenchyma](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008870)
for proximal lung I'm using [pulmonary alveolar parenchyma](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0008870)
please feel free to suggest better terms

**Comment by arschat** [comment]
Hi Ida! Well done wrangling this dataset! I have a few comments here.

### Project
- supplementary link, maybe avoid using a URL shortener for clarity reasons, and use "http://ec2-3-236-59-0.compute-1.amazonaws.com:3838/lungmap/" instead

### donor
- [GSE130076](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130076) includes all 6 healthy donors, and leaves only `Donor_7` marked as scRNA-seq but not referenced in Fig. 1 like other donors. The [GSE130076](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130076) donor is has `Source name` - `Distal lung epithelium` while it is referenced in the manuscript:
    > A new scRNA-seq dataset using only the **distal lung epithelium** was used to identify a cell-surface marker to isolate primary RAS cells (Extended Data Fig. 10a, b).
    
    It is not directly mentioned but since it's the only other "scRNA-seq dataset" used, I would assume that `HT280neg_Single cell` the extra `Donor_7` mentioned in the table.
- for FEV1 (L) and FEV1 %Predicted you could use the new fields `donor_organism.medical_tests.fev1_prebd` and `donor_organism.medical_tests.fev1_prebd_predicted_percent`
- `smoking_history` I would rather use another value instead of 0 for `smoking_history`. Do you think the 0 value is for non-smoker?

### cell suspension
- `selected_cell_type` the label of the ontology is `type II pneumocyte` however, in the OLS3 version's label is `pulmonary alveolar type 2 cell`. since validation is done on hcao though, there would not be a problem


### analysis protocol
- `alignment_software_version` in the Code availability section, Cellranger version is specified as v3.1.0

**Comment by idazucchi** [comment]
thanks for reviewing! 
I've updated the submission and I'm exporting

**Comment by idazucchi** [comment]
verified in browser
