### ISSUE TITLE
GSE133747 - MammalLungConnectomeRaredon

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1299]
### Project short name:
MammalLungConnectomeRaredon
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1jR4aLYp0I0eJgOcRBb0cnWuT5j_34xIq?usp=sharing)

### Published study links

* Paper: [Single-cell connectomic analysis of adult mammalian lungs](https://doi.org/10.1126/sciadv.aaw3851)

* Accessioned data: [GSE133747](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE133747)

[**Ingest**](https://contribute.data.humancellatlas.org/projects/detail?uuid=3627473e-b6d6-45c9-87b5-b9f12ce57a10)
### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Wrangling human samples only
Yale - The two fresh samples, since they are are described along with the animal ones and have the same identifier structure
>Human samples were acquired from healthy tissues excised from the distal margins of lobectomies and/or tissues rejected from transplant. 
It's impossible to know which sample is the lobectomy and which is transplanted so I'm putting `unknown` as is_living
Brigham and Women’s Hospital
>Human lung explants were obtained from rejected donor lung organs that underwent lung transplantation at the Brigham and Women’s Hospital or donor organs provided by the National Disease Research Interchange 
the remaining 12 samples are not from living donors

**Comment by arschat** [comment]
Hi Ida! I reviewed your dataset, and have only a couple of comments.

### Project
- you could fill the hca bionetwork tab for Lung v2.0 atlas (it seems that this atlas name is finalised)

### Donor
- We indeed do not know the donor's diseases that were adjacent to the specimen. I would leave it as healthy since that's how all tissues are described in the publication.

### Library prep
- `single nucleus` is filled in the NUCLEIC ACID SOURCE, however I think it's `single cell` (no mention of nucleus in paper or geo)

### Analysis protocol
- Alignment software & version can be filled with `STAR v2.6` as well as gene annotation version `v91` (although publication mentions only the genome version it was aligned, it also shows the ensembl version which is used for the gene annotation. we could therefore extract this info here as well)

### Analysis file
- Based on this [mapping](https://www.ensembl.org/info/website/archives/assembly.html) you could also specify that patch version is p10 for all the count matrices (mapped to ensembl version 91).

**Comment by idazucchi** [comment]
according to the tracker this dataset is not part of the lung list?

**Comment by idazucchi** [comment]
reviewed in browser
