### ISSUE TITLE
GSE185948 - CellularComplexityADPKD

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#1312]
### Project short name:
CellularComplexityADPKD
### Primary Wrangler:
Ida
### Secondary Wrangler:
Arsenios

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/1ufG_wZZl51KXCVm4mfNLCVCQGD-RBGzo?usp=drive_link)

### Published study links

* Paper: [Defining cellular complexity in human autosomal dominant polycystic kidney disease by multimodal single cell analysis](https://doi.org/10.1038/s41467-022-34255-z)

* Accessioned data: [GSE185948](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE185948)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=9bef1e81-e5d9-4ece-81cb-ab7449232021)

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [ ] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [ ] Are the analysis files suitable for CellxGene? If something is missing get in touch with the authors to request it
- [ ] Upload sheet to validate metadata
- [ ] Transfer raw files to ingest to validate data files
- [ ] Check linking using ingest graph validator
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by arschat** [comment]
Hi Ida, very nice job on completing this. I only have a few comments, otherwise dataset is good to go.

### Project
- you could add the atlas in `hca_bionetwork` module for Kidney v1.0
- `contributors.name` are not in the right format _first name,middle name initials,last name_ but in the way extracted from europe pmc api _first name middle name initials,,last name_
### Enrichment protocol
- If i understand correctly, the 5μm strainer was used to filter out anything that was bigger than nucleus, so it would be another maximum filter, and not a minimum filter.
### Sequence file
- Some rows have lane index while others do not, we could fill this for all files based on the filename

**Comment by arschat** [comment]
Verified in the [portal](https://explore.data.humancellatlas.org/projects/9bef1e81-e5d9-4ece-81cb-ab7449232021?catalog=dcp44)
