### ISSUE TITLE
Add extra metadata about the contributor matrices

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/hca-ebi-wrangler-central#133]
**Description of the task:**

As part of the DCP MVP we assembled a list of matrices for the datasets in the ticket #108 

The browser team have requested we add columns to the spreadsheet to allow the browser to understand how the matrices have been stratified.

column | expected values
-- | -- | 
species | [Human, Mouse]
stage | [Adult, Prenatal]
organ | name as specified in specimen_from_organism.organ
library | [10x, SS2, ...] (There may be other values here, essentially what is specified by the library_preparation_protocol method)

The columns above have been added to the `final_file_list` tab here: https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit#gid=671636652

@danielsotirhos can you confirm the expected values for each field? I have made some guesses above and filled out a small example for the tissue sensitivity project at the top of the spreadsheet.

Also adding the MVP schema doc that has information about how these fields are planning to be used: https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?ts=5f6a418a#heading=h.aohbnknu370j

**Acceptance criteria for the task:**

- [x] each file in the list has the four columns filled out

**Comment by rays22** [comment]
I have tried to use HCA ontology terms wherever I could.
``` 
    species:	donor_organism.genus_species.ontology_label
    stage:	donor_organism.development_stage.ontology_label
    organ:	specimen_from_organism.organ.ontology_label
    library:	library_preparation_protocol.library_construction_method.ontology_label
```

**Comment by rays22** [comment]
I have updated the `stage` column in
https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit#gid=671636652
based on the feedback we received today.
I have added explicit `species: stage` notation to disambiguate the species-stage relationships in the table.

**Comment by mshadbolt** [comment]
thanks @rays22. I went through and disambiguated the organs I think.

@danielsotiros are you able to take a look to see if that you will be able to parse through the list?

**Comment by danielsotirhos** [comment]
@mshadbolt I just ran the current spreadsheet through the adapter and was able to parse out all the values. Thanks!

**Comment by danielsotirhos** [comment]
Hi @mshadbolt . Can I ( dsotirho@ucsc.edu ) get edit access to the spreadsheet? I've requested edit access through the spreadsheet itself but I'm not sure who that is sent off to. I'd like to slightly modify the stratification values to avoid having to do extra processing while parsing.

I've also got one question on the current values. In the project `scRNAseqSystemicComparison` three files are listed with `prenatal` as the `stage` value. Is it correct to interpret this as `prenatal` for both `human` and `mouse`? I only ask because these three are the only rows without a qualifier in the `stage` column.

Thanks!
