### ISSUE TITLE
Cleanup of any wrangling data associated with HDCA project: single-cell transcriptomics

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#22]
We have been informed that the data and metadata submitted for the project should not be publicly accessible and asked to clean up the data from our wrangling spaces

This is the project https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

- [x] Spreadsheet and other metadata in the PROJECTS - IN PROGRESS folder [here](https://drive.google.com/drive/folders/1IIlfTiTrjd7wOoQXrWhvU9yNVktjpSAe)

- [x] Information about the project in the hca-data-wrangling repo under [this folder](https://github.com/HumanCellAtlas/hca-data-wrangling/tree/master/projects): At first sight it doesn't look like there's anything but if there was information written here we need to make sure to **delete it for every branch**

- [x] The following ticket that refer to this dataset: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/255

- [x] Spreadsheets in the mail: Check the wrangler mail and delete any copy, as well as identifying the date the spreadsheets were sent and checking with all the wranglers that were working in the project at that time
- [x] @zperova to delete her own possible personal copies in her google drive/computer.
- [x] @ESapenaVentura to delete his own possible personal copies in his google drive/computer

**Comment by lauraclarke** [comment]
@zperova I don't know what data we hold about this project on the wrangling side. Can you update this ticket with a list and let us know when it has all been removed

**Comment by ESapenaVentura** [comment]
I would like to clarify something first: Do we need to delete all data associated with this project? There were 3 different labs associated to the HDCA project.

Since @zperova works partial time, I will begin creating the list here of all possible locations and @zperova  can update it and move it to the ticket when possible:
- [ ] Spreadsheet and other metadata in the PROJECTS - IN PROGRESS folder [here](https://drive.google.com/drive/folders/1IIlfTiTrjd7wOoQXrWhvU9yNVktjpSAe)
- [ ] Information about the project in the hca-data-wrangling repo under [this folder](https://github.com/HumanCellAtlas/hca-data-wrangling/tree/master/projects): At first sight it doesn't look like there's anything but if there was information written here we need to make sure to **delete it for every branch**
- [ ] Check the following tickets that refer to this dataset (This list was made with a quick search of 'HDCA' and 'Sten', I might be missing something or referring to tickets that have nothing to do with the dataset):
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/255
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/244
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/263
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/120
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/83
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/56
   - [ ] https://github.com/HumanCellAtlas/hca-data-wrangling/issues/42
- [ ] Spreadsheets in the mail: Check the wrangler mail and delete any copy, as well as identifying the date the spreadsheets were sent and checking with all the wranglers that were working in the project at that time
- [ ] @zperova to delete her own possible personal copies in her google drive/computer.
- [ ] @ESapenaVentura to delete his own possible personal copies in his google drive/computer

**Comment by lauraclarke** [comment]
@zperova @ESapenaVentura Can I get an update on this issue?

**Comment by zperova** [comment]
@lauraclarke could I please clarify whether any mention of the project (such as PI name, technique, and type of tissue) needs to be deleted as well? These do not contain any personal information or data about the subjects, thus they should not be violating GDPR.

**Comment by lauraclarke** [comment]
My understanding is that is correct. This is about copies of the full metadata spreadsheet and data files not other emails/communications about this project

**Comment by zperova** [comment]
thank you @lauraclarke, I will update the list @ESapenaVentura put together and will contact Mats on whether we also need to remove the data and metadata we got from him for the same project.

**Comment by zperova** [comment]
Update: GDPR does not apply to ISS data, so it is only the 10x part we need to cleanup.

**Comment by ESapenaVentura** [comment]
Zina, is everything on the list updated? I have noticed you deleted the tickets I mentioned.

Happy to finish the task tomorrow if everything has been checked and you don't have capacity!

**Comment by zperova** [comment]
@ESapenaVentura sorry I misread, I thought you said you are doing it once I review it. I'd be very grateful if you finish this. I deleted the tickets that only mention the dataset but do not contain any metadata. Before deleting the ADUR ticket I'd address where we capture the necessary AUDR (also mentioned in my reply to the email sent by @lauraclarke on that yesterday). I also think it might be a good idea to double-check with Stanford (Jason, Jenny, Jennifer) in case they retained any spreadsheets of this dataset. thank you!

**Comment by lauraclarke** [comment]
Stanford was included in the initial email about cleanup. They said they wouldn't transfer any data to the new CZI seed network system and didn't have anything right now

**Comment by ESapenaVentura** [comment]
I will finish it tomorrow then! I'll check on the AUDR issue as well.

Thanks for the hard work @zperova !

**Comment by ESapenaVentura** [comment]
Without access to the spreadsheet, is there any need to actually delete the AUDR ticket?

I have revised the ticket and the only metadata specified in the ticket is:

- Id of 1 donor (which isn't really traceable, and we could substitute it for something you could only look if you had the spreadsheet (e.g. donor in row number X)
- Organ parts information
- Project title (Does this info fall under GDPR jurisdiction??)

But the latest spreadsheet already has the donor issues fixed, so maybe keeping the ticket and deleting the parts of the tickets that reference it is a better solution?

**Comment by ESapenaVentura** [comment]
I have searched extensively in the google group and I have deleted any email with a spreadsheet that had any information in it.

Emails with the s3 upload area have not been deleted as all DCP1 ingest s3 upload areas were deleted (I have tested and there is no data)

I have deleted my own personal copies of the spreadsheet.

We need the following people to confirm deletion of personal copies of the spreadsheet (Name begins with `linnarsson`):
- [ ] @rays22 : Personal copies on local storage/drive
- [ ] @mshadbolt: Personal copies on local storage/drive
- [ ] @ami-day : Personal copies on local storage/drive
- [ ] Mallory Freeberg: Personal copies on local storage/drive + Checking on personal email to see if they have a copy from the conversation around 19th February 2019
- [ ] Matt Greeen: Personal copies on local storage/drive + Checking on personal email to see if they have a copy from the conversation around 19th February 2019

**Comment by mshadbolt** [comment]
Possibly worth noting that anyone on the wrangler email list would also have any spreadsheets that were emailed to the list if they haven't deleted them from their inbox. Not sure if UCSC have been contacted?

**Comment by ami-day** [comment]
Oh, I didn't check that. I guess if I search for "linnarrson" I will find
them if I have any? otherwise I wouldn't know where to start trying to find
these emails

**Comment by mshadbolt** [comment]
@ami-day most of this correspondence probably happened before you joined so you are probably in the clear, I was more thinking about clay and UCSC wranglers. 

I know I am terrible at deleting old emails but maybe others have already done so.

**Comment by ESapenaVentura** [comment]
I specifically tagged @ami-day @rays22 and @mshadbolt because the spreadsheets were in a conversation prior to March 2019 (Even I didn't have the emails in my mail app) 

No, I have to contact UCSC - I need to go through the wrangling group and add everyone to the list

**Comment by zperova** [comment]
a quick note - the correct spelling is "linnarsson", double n and s, not r

**Comment by mshadbolt** [comment]
I checked and believe I have deleted all copies I have locally and in personal drive.

**Comment by rays22** [comment]
I have checked and I do not have any related emails or spreadsheets as local copies or on any personal drive.

**Comment by lauraclarke** [comment]
@ESapenaVentura @zperova Can this be considered finished? it would be great to close it if it is

**Comment by ESapenaVentura** [comment]
I just sent the email notifying the rest of the people about the deletion of personal copies.

I would consider this done.

Proceeding to close!
