### ISSUE TITLE
Assess HCA publication list, what can we wrangle now? why can't we wrangle the things we can't

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#223]
@Wkt8 did an excellent assessment of the HCA publication list which can be found here https://docs.google.com/spreadsheets/d/12IW-H_QAZ3n462iCxXND6TRO_8krMSfE1wDH9skcd9o/edit#gid=1720630627

There are about 12 publications that are unrestricted in terms of data release and don't contain data from living donors

For these we need either

1. start wrangling them to capture the raw data
2. Have a reason why we can't wrangle them

For all 42 of the datasets with primary data from human and mouse can we also know if we can get the contributor matrices?

This ticket will be done when

For any publication which isn't already in the DCP with unrestricted raw data that isn't from living European donors we have achieved either
- [x] They are in the wrangling queue
- [x] We have a clear statement as to why they can't be wrangled now and if they should be reviewed again in the future

For all publications with primary data that isn't already in the DCP
- [x] Have locations for matrix files and cell-type annotation which can be distributed in an unrestricted manner
or 
- [ ] Have a clear statement about why there are no matrix files and cell types and if this should be followed up in the future

**Comment by Wkt8** [comment]
I have added 5 publications not in the DCP, with unrestricted raw data that isn't from living European donors to the wrangling queue. They are now in the 'New Issues' column of the Dataset Wrangling Board. 

There are a remaining 7 datasets which we cannot wrangle due to managed access, mixed species, or specific issues with the dataset. 

For all publications with primary data that isn't already in the DCP: 
I have either added the locations for matrix files and cell-type annotation, or a statement about why there are no matrix files to the dataset tracker sheet, as a new column on the end of the tracker sheet. 

Finishing up:

- [ ] Find a good place to put the 'follow-up' tasks for the managed access data / data that hasn't yet been published, as there are a few of them, and set up a frequency for following up on them.

**Comment by Wkt8** [comment]
The HCA publications that need following-up to find the expression matrices as they have not yet been published are as follows. 

Sampling artifacts in single-cell genomics cohort studies
Single-cell atlas of a non-human primate reveals new pathogenic mechanisms of COVID-19
Single cell transcriptome atlas of immune cells in human small intestine and in celiac disease

Spreadsheet of analysis found here: 
https://drive.google.com/file/d/1UaYgJKrFYfhuTvrkb-RCKkSZs3As6j6t/view?usp=sharing 

Not quite sure where to put a 'follow-up' task, so am creating a calendar event and creating a followup email. 

Tasks completed.
