### ISSUE TITLE
GSE118184: Comparative Analysis and Refinement of Human PSC-Derived Kidney Organoid Differentiation with Single-Cell Transcriptomics

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#235]
**Primary Wrangler: Wei Kheng Teh**

**Secondary Wrangler: ** Ami

**Associated files:**
Project Link: https://contribute.data.humancellatlas.org/projects/detail?uuid=16ed4ad8-7319-46b2-8859-6fe1c1d73a82
Google Drive: https://drive.google.com/drive/folders/1d78TfAkb5Ek2-pyITv6Qf8708f8IFONu?usp=sharing

**Published study links**

Paper: https://pubmed.ncbi.nlm.nih.gov/30449713/ 

Accessioned data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118184 

**Key Events**

- [x] convert published metadata to HCA spreadsheet
- [x] manually curate dataset to meet HCA metadata standard
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production

**Comment by Wkt8** [comment]
Currently blocked by ingest-graph-validator issues, see [here](https://github.com/ebi-ait/hca-ebi-dev-team/issues/375 )

**Comment by Wkt8** [comment]
No longer blocked by ingest-graph-validator! Have validated in the ingest-ui and in the ingest-graph-validator and is now ready for secondary review.

**Comment by ami-day** [comment]
Hi @Wkt8. I've done a 1st secondary review.

It is a bit subjective how to model iPSC and organoid data using our schema but how you have done it makes sense to me. I think it would be useful for us all to discuss this layout and my latest iPSC data to compare in light of slight differences in experimental design. Then use them as a reference to look back to when curating similar projects.

I ended up with quite a few points to start with, but most are not major. I think it would be good if I review again after you have made changes which you agree with based on the below. The next time I will review by trying to import and validate in ingest.  

- [ ] Dissociation protocol: organoid_dissociation method should be enzymatic dissociation (TrypLE), not centrifugation.

- [ ] Differentiation protocol: I think what you wrote for the method, Directed Differentiation to Organoid, is a good option, given it's not in the example list. I checked the schema and an ontology label is not required.

- [ ] Differentiation protocol: might be good to simplify 'differentiation_protocol.protocol_core.protocol_description' by removing reagent details like catalog no., company and move to the differentiation media and small molecules field. Same with some other protocols e.g. Human_62_nuclei_dissociation

- [ ] You can remove the supplementary file tab because it's empty. I can't remember whether if this will cause an import or validation error in ingest, or not. Same with ipsc induction protocol.

- [ ] Library prep. tab: I think you can just keep the 1st sentence for this field 'library_preparation_protocol.protocol_core.protocol_description' for Drop-seq, if this is the standard/original Drop-seq publication method (?), also because you have added the link to the paper. For 10X, I would remove the part about sequencing. That should be captured in the Sequencing protocol tab.

- [ ] Library prep. tab: For single nucleus sequencing, 'library_preparation_protocol.nucleic_acid_source' should be single nucleus

- [ ] I would add 'Human_iPSC_BJFF6_dissociation' to the Organoid tab as opposed to the Cell suspension tab. I think it should be possible, using 'dissociation_protocol.protocol_core.protocol_id' as a field in the tab.

- [ ] Organoid tab: add 'yes' to organoid.embedded_in_matrigel

- [ ] Organoid tab: add 'matrigel' to organoid.growth_environment

- [ ] Cell line tab: add 'BJFF6 human iPSC line was reprogrammed by Sendai virus from human foreskin fibroblasts (Washington University Genome Engineering and iPSC Core). BJFF6 cells were maintained in 6-well plates coated with matrigel in Essential 8 medium.' to cell_line.biomaterial_core.biomaterial_description for iPSC line

- [ ] Cell line tab: maybe add Essential 8 medium (Thermo Fisher Scientific) to cell_line.growth_conditions.growth_medium?

- [ ] Cell line tab: add 'fibroblast' to cell_line.cell_type.text & ontology id and label

- [ ] Cell line tab: add 'Homo sapiens' to cell_line.genus_species.text & ontology id and label

- [ ] Cell suspension tab: I would add the differentiation day in the cell_suspension.timecourse.value field and fill the related fields. For a similar dataset, I wrote 'cell_suspension.timecourse.relevance' as 'the day at which the organoids/sample were used to generate single-cell RNA-Seq libraries.'

- [ ] Cell suspension tab: Maybe add the cell count in Supplementary table S1 as the estimated cell count

- [ ] General: where '||' is included, I think it needs to be without spaces e.g. protocol1||protocol2 rather than protocol1 || protocol2. I think how it is won't validate.

- [ ] The organoid images in the paper look amazing

- [ ] Looks like the expression matrix is available via GEO here: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE118184&format=file&file=GSE118184%5FTakasato%2EiPS%2Etimecourse%2Etxt%2Egz 

- [ ] Have you checked for and if needed, emailed the authors about obtaining cell type annotations?

Sorry to add so many comments! it's a really nice dataset and on it's way to being valid. We also have other primary kidney data from this same author in the portal (https://data.humancellatlas.org/explore/projects/027c51c6-0719-469f-a7f5-640fe57cbece?catalog=dcp2) (https://data.humancellatlas.org/explore/projects/577c946d-6de5-4b55-a854-cd3fde40bff2?catalog=dcp2)

**Comment by ami-day** [comment]
Just realised I added tick boxes instead of a list. That wasn't intentional!

**Comment by lauraclarke** [comment]
@Wkt8 am I correct in thinking this is waiting for an ontology term release?

**Comment by Wkt8** [comment]
Yes, that is correct. I am waiting for the ontology term release noted in this [ticket](https://github.com/EBISPOT/efo/issues/1017).

**Comment by Wkt8** [comment]
Ontology term released - will update and do a final check today!

**Comment by Wkt8** [comment]
This has been exported and the form completed to request for Broad import!

**Comment by Wkt8** [comment]
This has been exported to SCEA (the 10X portion) with the Dropseq portion unable to get through as it is composed of cell lines and organoids. Will wrangle the dropseq portion when it is able to be processed with our SCEA script!

**Comment by ofanobilbao** [comment]
@Wkt8 I have moved this into Finished as I believe that the DCP journey is complete. I have moved it into the Review/QA pipeline in the SCEA board. The SCEA board might need refining depending on all of the wrangler needs. Correct me if I'm wrong please. Thanks!
