### ISSUE TITLE
GSE134809: CrohnsTherapyResistance dataset

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#240]
**Dataset/group this task is for:**

GSE134809: CrohnsTherapyResistance
Google sheet: https://docs.google.com/spreadsheets/d/1_ahGFfIBDAQOhyJToR4SnUObNeCOYM-Q/edit#gid=1764134611
https://contribute.data.humancellatlas.org/projects/detail?uuid=992aad5e-7fab-46d9-a47d-df715e8cfd24
 
**Wrangler responsible for this dataset/lab:**

Ami

**Acceptance criteria for the task:**

- [x] fill metadata

- [x] add ontologies

- [x] validate with graph validator

- [x] validate in ingest staging

- [x] secondary review

- [x] upload to ingest prod.

- [ ] upload raw data to ingest prod.

**Comment by ami-day** [comment]
Added ontologies but need to enter new fastq file names.

**Comment by mshadbolt** [comment]
will take this on to secondary review

**Comment by mshadbolt** [comment]
review notes:
* i would put a link directly to the article, rather than the pubmed entry
* the ileum is part of the small intestine so i think i would use 'small intestine' for specimen.organ and 'ileum' for specimen.organ_parts
* on the specimen tab, there are some of the PBMC specimens that have 'colon' as organ
* for both the donors and specimens I think I would use the disease 'Crohn disease' MONDO:0005011 as the term used 'Crohn's colitis' is specific to the large intestine but these samples are from the small intestine and i think maybe safer to use the more general term in this case.
* Could put the cell viability method into the cell suspension tab Trypan Blue, >85%
* I think we preference using the prime specific ontology term, so would use 10X 3' v1 sequencing EFO:0009901
* I think the information in the library preparation protocol is incorrect for 10X v1 see https://teichlab.github.io/scg_lib_structs/methods_html/10xChromium3v1.html based on that I think it is:
    * read 1 - cDNA ~98bp
    * i7 - cell barcode ~14bp
    * i5 - sample index ~8bp
    * R2 - UMI ~10bp 
* Given the different read structure I might be tempted to run your script on the v1 fastq files to make sure we are matching the read files correctly as index1, index2, read1, read2 on the seq file tab. Though yeah if I had to I would guess like you have that R3 is the second index read. (or maybe you already checked it)
* The process id hasn't been filled in so the seq files won't get grouped correctly into subgraphs
* If the Experiment ID gets used for the process id there will be multiple sets of fastqs with the same lane index within an experiment (since there were the 4 10x sample indices spread across 4 lanes for some cell suspensions

**Comment by ami-day** [comment]
Thanks @mshadbolt I have made these changes.

**Comment by ami-day** [comment]
There is currently an issue on EC2 blocking fastq transfer for this dataset.

**Comment by ami-day** [comment]
Downloading the data to an hca-util upload area

**Comment by ami-day** [comment]
Requested from ncbi, not available yet.

**Comment by lauraclarke** [comment]
Will this block its available by Monday?

**Comment by rays22** [comment]
This project was exported for HCA Data Portal release 4 on 2021-03-19.

**Comment by ami-day** [comment]
I made updates to this project. I need to check they look ok.

**Comment by ami-day** [comment]
Submitted import form as part of export SOP.

**Comment by mshadbolt** [comment]
Analysis picked up some issues with this project and further review has noticed other issues:
* DNA sequence ontology does not continue for the full number of sequence files
* there are linking issues with rows 390 and 391, there has been a typo and for the index file of the run SRR9827719 the cell suspension SRX6584271 has been assigned instead to cell suspension SRX6584272
* The checksums column has SRX experiment accessions

They also pointed out that one experiment doesn't have index files, but I think this is because they aren't available from SRA so isn't a problem per se (https://github.com/DataBiosphere/azul/issues/2996#issuecomment-823558229)

**Comment by ami-day** [comment]
@mshadbolt Thanks for identifying the source of the issues here, have you had a chance to make any changes or can I go ahead and make these changes?

**Comment by lauraclarke** [comment]
Marion won't be online again before the deadline passes. It is probably safest to assume these changes haven't been made. That said given there is a linking issue I don't know how quickly this can be resolved.

**Comment by ami-day** [comment]
Ok, I'll make the changes and see if a dev is around to check it following re-export.

**Comment by ami-day** [comment]
We need to able to make bulk edits to the metadata to resolve 2 of the above issues, due to >500 records. The other option is to re-upload the spreadsheet with edits made, but then the project uuid will change. I brought this up on our operations channel since there may be a way for devs to do a baulk fix in the backend as a hack for now until we have a bulk update solution.

**Comment by ami-day** [comment]
@aaclan-ebi I have added an corrected version here: https://docs.google.com/spreadsheets/d/1tbAEK0-rXYNxd1T3-rrEOljsk92Z43Ia/edit#gid=1817708346 The changes I made are noted above in Marion's comment. If it's not clear please feel free to message me directly on slack and i'll get back asap. Thanks!

**Comment by ami-day** [comment]
@clairerye would like us to wait to make bulk updates possible in a sustainable way and avoid doing a hack for this dataset, as there are a few datasets which need bulk updates in the pipeline.

**Comment by ami-day** [comment]
This has been updated (bulk updates).

**Comment by ofanobilbao** [comment]
@ami-day was this dataset submitted to SCEA? If so, would the SCEA submission require update? Or can this ticket be closed?

**Comment by ami-day** [comment]
> @ami-day was this dataset submitted to SCEA? If so, would the SCEA submission require update? Or can this ticket be closed?

The updates I made are not relevant to the SCEA format, so this can be closed.

**Comment by ESapenaVentura** [comment]
Re-opening this dataset as this is relevant to ticket https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/354

**Comment by ami-day** [comment]
The incorrect matrix was added to the MultipleSclerosis project. It needs to be added to the Crohns Therapy project. This means the following 2 points need to be addressed:

- GEO matrix associated with Multiple Sclerosis project should be deleted from hca data portal

- The GEO matrix associated with Crohn's therapy GEO accession which was incorrectly added to the MS project should be added instead to the Crohns therapy project (updated in ingest)

**Comment by ofanobilbao** [comment]
I believe this Project (as curated originally by Ami) was deleted in favour of a version curated by UCSC back when we removed existing duplicates. So the updates might need input from UCSC

**Comment by ami-day** [comment]
I will close this ticket, as the project is a UCSC project.
