### ISSUE TITLE
GSE138266_SingleCellsMultipleSclerosis dataset

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#241]
**Dataset/group this task is for:**

GSE138266_SingleCellsMultipleSclerosis
https://docs.google.com/spreadsheets/d/1AnlN069mq8UK6arLQW-pqtmW17fNckTD/edit#gid=1504906292

**Wrangler responsible for this dataset/lab:**

Ami

**Acceptance criteria for the task:**

- [x] fill metadata

- [x] add ontologies

- [x] validate with graph validator

- [x] validate in ingest staging

- [x] secondary review

- [x] upload to ingest prod.

- [ ] upload raw data to ingest prod.

**Comment by ami-day** [comment]
This is stalled while I wait for a new collection method ontology term to be added.
Request is here: https://github.com/HumanCellAtlas/ontology/issues/75

**Comment by lauraclarke** [comment]
Given updates are about to be possible, is this something which needs to wait? how long before the next ontology release?

**Comment by ami-day** [comment]
@lauraclarke I'm not sure when the next ontology release is, I'll ask Paula

**Comment by lauraclarke** [comment]
Great, because if it is more than a month away, it might be worth considering if moving forward without the ontology term is the right thing to do

**Comment by lauraclarke** [comment]
If it is more than a couple of weeks, it would be good to consider releasing while we wait

**Comment by ami-day** [comment]
Paola got back and said the next release date will be 18th Feb. She also said they will now be updating HCAO around the 18th-22nd of every month, since EFO is updated monthly. I think it makes sense to wait until then?

**Comment by ami-day** [comment]
Added new ontology term (lumbar puncture)

**Comment by ami-day** [comment]
Need to request files from NCBI aws service.

**Comment by ami-day** [comment]
Uploading fastq files to hca-util upload area.

**Comment by ami-day** [comment]
Need to convert bulk sequencing files from sra object to fastq.

**Comment by ami-day** [comment]
All metadata is ready now and data is uploaded to an hca-util upload area.

**Comment by mshadbolt** [comment]
First up, it seems to me this has living european donors so we wouldn't be able to export it for now. But I continued with reviewing anyways

review notes:
* There are few more non-NIH funders named in the 'acknowledgements section
* The methods section specifies 'All patients were of Caucasian ethnicity'
* I am a bit torn on the library_prep.method. I think using the SmartSeq2 term will make pipelines see it as analysable, not sure if it is worth flagging it to them or asking about it. One option could be to use the parent term 'Smart-like'
*I am not sure if it is correct or not that a single run and single experiment has been broken into multiple process IDs. I think maybe because a single library was split over two flow cells and they have been split based on that. Wanted to flag it in case it wasn't intentional. If they do all get grouped the lane indices will need to be adjusted (so many fq files!)
* the DNA sequence ontology stops around row 46-563 on the sequence file tab
* I thought that it would be good to put TFH as the selected cell type on the bulk samples but the term isn't in our ontology, not really sure why https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002038

**Comment by ami-day** [comment]
Thanks for reviewing @mshadbolt , I'll pick this back up when I've finished wrangling/export of the projects for the April release. Looks like we we could add the matrix files in the May release if it should be managed access.

**Comment by ami-day** [comment]
We can't export gdpr tagged datasets currently. Moving this ticket to the stalled column.

**Comment by ami-day** [comment]
Using this dataset as a test for the schema updates where we only upload a matrix file, not the raw data.

**Comment by ami-day** [comment]
> Thanks for reviewing @mshadbolt , I'll pick this back up when I've finished wrangling/export of the projects for the April release. Looks like we we could add the matrix files in the May release if it should be managed access.

Ok have now made these updates. Now need to follow the SOP on exporting processed data only (i.e. not the fastq files).

**Comment by ami-day** [comment]
I have clicked "export" metadata and data after uploading the metadata and syncing the files indicated in the Analysis Protocol and Analysis File tabs. This was also a test to see if exporting works on datasets without raw sequencing files due to GDPR. The current status is "exporting".

**Comment by ami-day** [comment]
Submitted export form on 25/05/2021.
