### ISSUE TITLE
AneurysmalHumanAorticTissue

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#244]
**Dataset/group this task is for:**

AneurysmalHumanAorticTissue
https://docs.google.com/spreadsheets/d/1EI5edBlJcZbDUAmtU4XbKLOARTpoJVQY/edit#gid=57639059

**Wrangler responsible for this dataset/lab:**
Ami

**Acceptance criteria for the task:**

- [x]  fill metadata
- [x]  add ontologies
- [x]  validate with graph validator
- [x]  validate in ingest staging
- [x]  secondary review
- [x]  upload to ingest prod.
- [x]  upload raw data to ingest prod.
- [x] Obtain expression matrix
- [x] Obtain cell type annotations

**Comment by ami-day** [comment]
Emailed the authors to ask about the 10X technology version. Waiting to hear back.

**Comment by ami-day** [comment]
Authors did not get back about 10X tech version. Have removed the library construction method and barcode lengths, offsets from the library prep. tab. We should still submit this without the construction method.

**Comment by ami-day** [comment]
It won't validate in staging.
Currently we can't add no construction method, or just 10X sequencing. It requires both a method and also barcode info because '3 prime tag' is indicated: https://staging.contribute.data.humancellatlas.org/submissions/detail?id=60394499f29f510eee57258b
We need to be able to 1. add no construction method or 2. add 10X sequencing without either an end bias or a version or both.

**Comment by ami-day** [comment]
Authors got back with the 10X versions.

**Comment by ami-day** [comment]
Graph validator issue on EC2. So not validated by that.

**Comment by lauraclarke** [comment]
This seems like a sufficiently complex graph that getting the graph validator running seems important. Have you filed a ticket, reached out to @amnonkhen about the issues you are facing with the validator. I know bugs have been fixed recently but I don't know if EC2 has the most recent version or not

**Comment by ami-day** [comment]
I thought this was the on-going graph validator issue...I'll ask Amnon about it.

**Comment by ami-day** [comment]
Uploading the fastqs to hca-util upload area.

**Comment by lauraclarke** [comment]
Even if it is an ongoing issue, if it is blocking you from running the SOP, then chasing up where the fix is in the pipeline is a an important and valid thing to do

**Comment by ami-day** [comment]
Sorted it now. It's now ready for 2ndary review.

**Comment by mshadbolt** [comment]
picking this up for secondary review

**Comment by mshadbolt** [comment]
- Could also add Scott LeMaire's email as corresponding contributor as listed in the article slemaire@bcm.edu
- could add ORCID ids (we could probably add to the geo-to-hca script to add these from the pubmed api)
    -  Hong Lu - 0000-0002-0577-2558
    - Alan Daugherty 0000-0003-2093-3775
    - Ying Shen 0000-0003-4119-115X
    - Scott LeMaire 0000-0002-8736-4266
- For the publication, I would link directly to the article rather than pubmed entry e.g. https://doi.org/10.1161/circulationaha.120.046528
- There are additional funder grants listed in the 'sources of funding' section of the paper which aren't in the spreadsheet
- There is a lot of donor metadata listed in a table in the paper that hasn't been incorporated into the spreadsheet e.g
    - additional info that could be put in the description about the donor, e.g. ATAA with root aneurysm, lung donor, etc. 
    - ethnicity
    - smoking status
    - various diseases including hypertension, diabetes and others
- I would want a more specific term for the collection method, I have a feeling this info might be in supplementals.
- For the organ I think I would put 'blood vessel' since I don't see the aorta as part of the heart itself, but maybe this needs a broader discussion amongst wranglers
- For the organ part, they specifically mention 'ascending aortic tissue' so i think i'd be inclined to annotate with UBERON:0001496 - ascending aorta
- maybe worth putting the aortic diameter in the specimen descriptions? I guess it is important if they listed it
- some donors have additional aortic related conditions e.g. bicuspid valve, valve regurgitation... not sure if they belong on  specimen or donor though, they should be listed somewhere
- I think if we list FACs we should provide at least one marker, I would assume in this case it would have been DAPI for live cells? But I can't find anything in the paper that refers to this

I saved a copy. of the pdf of the paper into the project's folder on google drive. [also online here but i think you'll need to be on vpn](https://ovidsp.dc2.ovid.com/ovid-b/ovidweb.cgi?&S=GJIBFPLCEDEBOLEAIPPJCGOGDHLAAA00&Link+Set=jb.search.31%7c1%7csl_10&Counter5=TOC_article%7c00003017-202010060-00010%7covft%7covftdb%7covftw#107)

very annoying that all the supplementary material is locked behind a paywall, i think we would get better information about the methods from there. Not sure if it is worth chasing or not.

**Comment by ami-day** [comment]
This is not blocked by a graph validator error. I have run the spreadsheet through the graph validator, and it passes the tests

**Comment by ami-day** [comment]
Thanks @mshadbolt. I agree with most of what you have noted, and made the changs (https://docs.google.com/spreadsheets/d/1EI5edBlJcZbDUAmtU4XbKLOARTpoJVQY/edit#gid=1266802430). Just need to find the additional disease ontology terms.

Some things which I haven't changed and why:

- Donor ethnicity: all donors except 1 are labelled as 'Non-Hispanic'. This is not specific enough for an ontology label to be added. I don't think it's worth adding all the ethnicities except 'Hispanic'.
- The smoking status field expects the number of cigarettes smoked a day and for how long. The smoking status provided in the paper is not this specific. It says 'past', 'current' or 'never'.
- Unfortunately the collection method is not described in enough detail for a more specific ontology label to be chosen. The supplements which potentially have more information are locked behind a paywall.
- FACS: I found this info. in the GEO metadata file. However, it is not more specific than this. I don't want to assume it is DAPI, so I added 'Live cell marker' in the marker field.

Agree it's annoying it is behind a paywall, especially as the publication contains primary human data which seems very valuable and not that easy to get hold of. I'm not sure there is anything we can do about this. @lauraclarke is there anything we can do when we can't get access to e.g. supplements behind a paywall, even with vpn? Enrique had a solution for the paper itself so I was able to get this. But the supplements are still not available using his method :( Tbh, the metadata as it is with these changes still seems very worth adding to DCP, and it might be better to move ahead and get this exported at the end of this month.

**Comment by lauraclarke** [comment]
@ami-day you could email the authors, generally, people are accommodating for this sort of thing if you explain the paywall issue, especially if you flag you want to add the data to the HCA

**Comment by ami-day** [comment]
It currently validates in ingest staging.

**Comment by ami-day** [comment]
The authors got back with the supplementary file (yay!). So I was able to add more detail about the dissociation protocol and enrichment protocol(s). Unfortunately, it does not provide any other information about the collection protocol so will email back again.

**Comment by lauraclarke** [comment]
from the recent email, can we specify surgical resection? what do we say for the CBTM samples?

**Comment by ami-day** [comment]
Yea that's what I have already specified, and am syncing the raw data files to ingest now.

**Comment by mshadbolt** [comment]
@ami-day  if you take a look at the paper I downloaded it does have specific ethnicities, they are labeled as 'race' in the metadata table but these are equivalent to the terms we would usually use for ethnicity, i.e. white, black latino on page 1376, or page 3 of the pdf

I think it would still be valuable to put the smoking status in the metadata in the 'smoking history' field, this field is a free text field, so while there is a preferred format I think it is useful to put any information we have available in that field

**Comment by ami-day** [comment]
Ok, will make these changes.

**Comment by ami-day** [comment]
Synced the fastq to ingest, but the validation following this is being quite slow.

**Comment by ami-day** [comment]
2 files missing in ingest prod., re-downloading them.

**Comment by rays22** [comment]
This project was exported for HCA Data Portal release 4 on 2021-03-19.

**Comment by ami-day** [comment]
Converted with scea id: E-HCAD-36
