### ISSUE TITLE
FoetalLungPeng

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#274]
**Primary Wrangler:**
Wei Kheng Teh

**Secondary Wrangler:**
Ida 

**Associated files:**
Link to paper: https://www.biorxiv.org/content/10.1101/2022.01.11.474933v1.full
Google Drive: https://drive.google.com/drive/folders/19zWssnTCxFEIqj1AqZDRNWFrGrOlIz8m
Link to Ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=0b53d1ad-bc5f-4030-818b-b12c7ddf5b6c&project=2fe3c60b-ac1a-4c61-9b59-f6556c0fce63

**Key Events**

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [x] Receive T&C form filled out by at least 1 representative of group/project
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata
- [ ] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by Wkt8** [comment]
Waiting to get additional metadata from HDBR.

**Comment by Wkt8** [comment]
Peng has mentioned that there are additional donors that he would like to add to this project, and he expects it to be in the DCP around August. Am waiting on him to send us additional information on the new donors.

**Comment by Wkt8** [comment]
Waiting on Rasa to reply to emails regarding some discrepancies between metadata they have sent us and metadata in the ArrayExpress accessions.

**Comment by Wkt8** [comment]
Wrangled scRNA, scATAC-seq, VDJ, and organoid data. 

Still waiting on some metadata from Peng on the VISIUM donor metadata.
Need to email HDBR to get some metadata for scATAC-seq donors.

**Comment by idazucchi** [comment]
almost done with archiving Visium data 
almost done with ATAC-seq data
the Visum data will not be in release 12 but the rest of the data will be

**Comment by Wkt8** [comment]
We are now archiving this all in Annotare - and they have to be split up into different technologies, which has added a lot more work.

**Comment by ofanobilbao** [comment]
It would be useful if he could move the files from HCA-util to annotare. @Wkt8 to create a ticket in operations

**Comment by ami-day** [comment]
There were some issues with the uploaded fastqs, Wei is looking into this

**Comment by Wkt8** [comment]
I have had to split Peng's dataset into four different ArrayExpress submissions: 
- scRNA / VDJ / GEX
- Organoid
- ATAC-seq
- Visium

These have all been submitted to ArrayExpress and will have accessions to send to Peng. 

The export to the DCP has not been done yet because Peng is still uncertain about the date for that to go public. The spreadsheet will be in the brokering drive. It probably will not have Visium data added to it yet due to the metadata schema change not being complete which allows imaging (probe and channel) to be optional. 

Remaining actions:
- check that Peng is happy with the accessions
- complete the DCP curation (with Visium) after the metadata schema change is accepted. We could then also add the ArrayExpress accessions for the biomaterials. 
- confirm with Peng a release date for the DCP curation, THEN push the dataset to be exported to the DCP
- potentially cellxgene wrangling of their processed data? 

Files are available in the hca-util upload area with uuid 4777804d-1b93-4bbf-955f-1c5083e2c504

**Comment by Wkt8** [comment]
@idazucchi to sec review

**Comment by idazucchi** [comment]
Hello! I'm done with the secondary review.
There is so much going on in this dataset! It's mostly good, but I have some comments
Let me know if you have any question

### Project
- you could add the visualisation portal link in the supplementary links section 
- the grant `MR/S035907/1` is repeated
- you are not listed as contributor, you really should be

### Donor 
- there is no donor description
- aren’t `HDBR1915, HDBR2174, HDBR-N13393` HDBR donors? You could fill in the HDBR accession field
- you could fill in the gestational age for `HDBR1915, HDBR2174, HDBR-N13393`, from the Fetal_lung tab `CS23, 8pcw, 8pcw`
- the developmental stage for `HDBR1915, HDBR2174, HDBR-N13393` should match their gestational age
- since the donors are fetal you should fill in gestational age instead
- you could fill in known disease as `normal`
- donor `HDBR15415` for visium seems to be missing?

### Collection protocol
- barker protocol: is it fetal donors rather than pediatrics donor?

### Specimen from donor
- interesting that you applied the dissociation method for the distal/proximal specimens
- you can remove the specimens `WSSS_F_LNG8713181specimen, WSSS_F_LNG8713189specimen, WSSS_F_LNG8713191specimen, WSSS_F_LNG8713180specimen, WSSS_F_LNG8713188specimen, WSSS_F_LNG8713190specimen`, they are orphans
- you could fill in known disease as `normal` 
- Whole lung
  - Is the organ part needed for the whole lung specimens? If yes maybe change whole-lung to be lung, if this is the field that gets picked up by the browser so that we don’t end up with a weird filter
  - should `WSSS8012016specimen, WSSS8011222specimen` have `barker_lab_collection_protocol`?
  - I would remove `5891STDY9030810specimen` and pool the specimen at the cell suspension level
- are there other ontology terms for distal and proximal lung? 
- for specimen `15415-LNG--FO-2_specimen` the donor should be `HDBR15415`

### Imaging preparation
- move the bit about freezing samples in OCT from the collection protocol to here?

### Imaging protocol
- the protocol is nameless
- register permeabilisation times, maybe in the imaged specimen tab as deviation from protocol? I thought we had a field for that specifically but I can’t find it


### Differentiation
- for `organoid_lentiviral_induction` you could add the doi `10.1101/2021.06.30.450501`, the differentiation medium and small molecules

### Enrichment
- the markers field for `MACS_depletion` is not formatted correctly
- the markers field for `CD326MACS_optional_4b` is empty
- you could add a mechanical dissociation protocol for whole-lung dawei 5’

### Cell suspension
- for organoid and scRNA CS you could add the biosample and Insdc sample accession
- the species is missing
- the description is all right but you need to remove the formula
- `5891STDY9030810_CS` should have as input specimens `5891STDY9030806_8specimen||5891STDY9030807_9specimen`
- you could add the cell counts from tab `scRNA and ATAC-seq CS`

### Library
- the libraries have no name
- for bcr/tcr should the library construction method be 10x 5’ v1 or the immune profiling ones?

### Sequencing
- the protocols have no description

### Sequence file
- for organoids and scRNA: you could add the experiment and run accessions
- for all ATAC-seq: I2 files should have index2 as read index
- for `SIGAA10, SIGAB10, SIGAC10, SIGAE6, SIGAF6, SIGAG12, SIGAG6, SIGAH10, SIGAH12, SIGAH4` are these sequenced with the novaSeq6000? they are not in the list in tab `Fetal_Lung`
- you could fill out the process id to group together the fastq files

**Comment by Wkt8** [comment]
Have made updates from Ida's secondary review, and am waiting on Peng to give an updated h5ad analysis_files

**Comment by Wkt8** [comment]
This is in graph-valid state. Can be exported.

**Comment by Wkt8** [comment]
Exporting triggered. Once it has been confirmed that the project has exported, I will fill in the DCP Import Requests form.

**Comment by ke4** [comment]
@ke4 and @jacobwindsor to investigate it

**Comment by Wkt8** [comment]
Triggered exporting again.

**Comment by amnonkhen** [comment]
@ke4 and @amnonkhen monitored the exported and found that it finished

**Comment by Wkt8** [comment]
Exported! Import Request for Production form submitted.
