### ISSUE TITLE
Upgrade the version of fastq_utils on the ec2 (WranglerTools)

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#291]
Upgrade the version of `fastq_utils` on the ec2 (WranglerTools: tool.archive.data.humancellatlas.org) at `/home/ubuntu/fastq_utils/` to the latest version (0.24.1)

**Comment by MightyAx** [comment]
I think this is done:
```
> ~/fastq_utils/bin/fastq_info
fastq_utils 0.24.1
```
@mshadbolt can you confirm?

**Comment by mshadbolt** [comment]
confirmed thanks!

**Comment by lauraclarke** [comment]
@mshadbolt does this mean you are stored for finishing validation of https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/227

thanks

**Comment by mshadbolt** [comment]
no, the problem is that the version of `fastq_utils` that the upload service uses is still the old version. So I have manually validated all the files using the new version, so I know they are valid, but ingest thinks they are not, so I can't export. The two options are to set all the files to valid because we know they are, or to upgrade the version that the upload service uses and retrigger validation. I am still not sure what is best. 

I asked for the ec2 version to be upgraded so that wranglers are able to use the latest version when they are validating files manually.

**Comment by lauraclarke** [comment]
Ah, that was a nuance I had missed. Is there a ticket for changing the one used by the upload service?
