### ISSUE TITLE
compare_tracker_with_nxn_sheet.py fails to find new publications

### ISSUE THREAD

**Issue by rays22** [ebi-ait/hca-ebi-wrangler-central#299]
### Description of the bug
There are some new entries in the [Single cell studies database](https://docs.google.com/spreadsheets/d/1En7-UV0k0laDiIfjFkdn7dggyR7jIk3WH8QgXaMOZF0/)
, yet the [compare_tracker_with_nxn_sheet.py](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/compare_tracker_with_nxn_sheet.py) script reports that

> No new datasets found

### Expected behaviour
The script is expected to find and report any new publications in the [Single cell studies database](https://docs.google.com/spreadsheets/d/1En7-UV0k0laDiIfjFkdn7dggyR7jIk3WH8QgXaMOZF0/).

### Script version
The script version that I used has the timestamp:

```
Last time updated:
2021-02-11T09:29:00.962945Z
```

I would like to note that the timestamp is not updated after running the script with any of the allowed options (`-c` or `-d`).

### On what system was the bug detected?
* Python version: 3.6.9
* Operating system:
Kernel: 5.4.0-70-generic x86_64 bits: 64 gcc: 7.5.0
Distro: Ubuntu 18.04.5 LTS

**Comment by ESapenaVentura** [comment]
The timestamp bit is a little bit weird, so you ran it and it didn't update the timestamp?

About the other part: I have found a bug. To get the table, it was comparing the reformatted titles against non-reformatted titles so that was leading to nothing being added.

I don't know how did that slip through, maybe when we refactored the code to include the -d option

I will create a PR against master with the fix

**Comment by ESapenaVentura** [comment]
The fix is now in master

I just changed L212 from:

full_unregistered_table = [row for row in second_unregistered_table if row[v_title_index] in unregistered_titles]

to

full_unregistered_table = [row for row in second_unregistered_table if **reformat_title(**row[v_title_index]**)** in unregistered_titles]

So I figured out we wouldn't need a PR
