### ISSUE TITLE
slowness in ingest 

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#336]
reported by Parisa on 19/5, noticed by Alegría as well.

[ ] slowness in ingest ui
[ ] errors in core log
[ ] intermitent responsiveness

_please add references to sloack/email_

_please rename ticket as necessary_

**Comment by aaclan-ebi** [comment]
Timeline of events based on core logs:
18:52 - a submission with 1145 assays was set to Exported. Prior to that exporter has a lot of retries logs due to connection errors to Core. Core was already a bit unresponsive.
19:28 (8:28pm UK) - a submission containing a lot of linked entities was created https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/60a566de46c1727e2e855ce3/submissionManifest  — the importer and validator were probably was sending 20K~ requests to core
22:01(11:01 pm) a submission was created 60a58aae46c1727e2e8573b9 — (deleted after few minutes)
22:05 a submission was deleted
22:06 a submission was created https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/60a58bfd46c1727e2e8573ba/submissionManifest
22:07 core pod was restarted

Ingest core was probably on high load and received a lot of requests before it was automatically restarted.

**Comment by aaclan-ebi** [comment]
I don't know yet how to prevent this from happening again. There were really a lot of requests coming to Core. We can think of ways like increasing instances of ingest core. But we need to do load testing to see our limits and how we should scale core. I am still uncertain what the long term solution should be.

**Comment by aaclan-ebi** [comment]
We notice that core restarted again last 25th May. This could be causing the slowness and causing the core pod to be out of memory and restart. I've filed a ticket in the product dev board https://github.com/ebi-ait/dcp-ingest-central/issues/332

**Comment by ami-day** [comment]
Alegria has a ticket for this already elsewhere.
