### ISSUE TITLE
IntestinalSpaceTime

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#339]
### Project short name:
IntestinalSpaceTime

### Primary Wrangler:
Wei Kheng Teh

### Secondary Wrangler:
@ESapenaVentura 

### Associated files:
Project: https://contribute.data.humancellatlas.org/submissions/detail?uuid=25320b69-7c36-405e-8fc8-6edce70f1f65&project=fde199d2-a841-4ed1-aa65-b9e0af8969b1 
* Google Drive: https://drive.google.com/drive/folders/1NcWHBfl2JAhA4xbnwZHwQRFW3KeJyumK

### Key Events

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [ ] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [x] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by Wkt8** [comment]
Am currently focusing on this as the contributor has gotten back to us with answers to my questions.

**Comment by Wkt8** [comment]
Waiting for E-MTAB-9532 to become public again

**Comment by Wkt8** [comment]
E-MTAB-9532 is public! Picking up wrangling.

**Comment by Wkt8** [comment]
Ready for secondary review. 
I have had trouble determining which tabs to use for the image files. 
I have used the following experimental design of 
Donor -> specimen -> Cell suspension -> sequencing protocol + library prep protocol + imaging protocol + analysis protocol -> analysis file 

Please let me know your thoughts!

![Screenshot 2021-09-20 at 14.25.27.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/5c26539b-e8cf-45b2-bda5-c1c00d2a0518)

**Comment by ESapenaVentura** [comment]
Taking the secondary reviewer role for this dataset!

**Comment by ESapenaVentura** [comment]
Hi Wei! I have reviewed your dataset, overall I have some comments and a suggestion for the visium:

## Review

### Project
Missing “estimated_cell_count"

### Project - Contributors
Added “No” to all missing values on corresponding contributor

### Donor organism
Changed embryo’s age to “gestational age”. Happy to discuss about it, but Age in that field is measured since birth, which I think it’s not applicable for this scenario :)

I’d suggest some other IDs, slashes in the IDs can be problematic when processing!


### Specimen from organism
I am missing the “imaged specimen” for the visium tissues, I’d suggest

### Dissociation protocol
Feels like “HumanFetalMechanical”’s first part would be better for a collection protocol? Happy to hear thoughts!

### Cell suspension
I wouldn’t put “visium” in cell suspension, it is a slide, not a dissociated cell suspension

## Visium

Continuing with the imaging bit, I have prepared an "alternative spreadsheet” so you can see how I envision this experiment! If you could take a look it would be great. It's under the same folder!

Just as an overview, I didn't fill all the details in the spreadsheet but I envisioned the graph as something like this:

![visium_model.jpg](https://images.zenhubusercontent.com/5ca5f897027e3e7234ac788c/f6cc07eb-1ac2-4cf9-8da1-f61326fe7120)

Let me know what you think!

**Comment by ofanobilbao** [comment]
@Wkt8 I found the peer reviewed paper for this today: https://doi.org/10.1038/s41586-021-03852-1

**Comment by gabsie** [comment]
close to secondary review now (woop!) VISIUM!!!!
