### ISSUE TITLE
Wrangling of new dataset: HumanAdiposeTissue GSE128890

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#35]
**Dataset/group this task is for:**

GSE128890

**Wrangler responsible for this dataset/lab:**

A wrangler working on operations this sprint

**Description of the task:**

- [x] Curated metadata spreadsheet (please see all comments in this ticket below): https://drive.google.com/drive/folders/1dOTCQ1TAoQm4Pm0VjUM1lxfXryWYL89h

- [x] Secondary review of dataset (@mshadbolt)

- [x] Validate the dataset by uploading to ingest

- [x] Validate the dataset with graph validator?

- [x] Add to list of datasets 'Complete' for MVP: https://docs.google.com/spreadsheets/d/1DfRFfZpZEmWU6aubKwIZ4D0lfm038IW0fmHRigS8yBU/edit#gid=552473761

**Comment by ami-day** [comment]
Came across an issue identifying whether the single human sample is derived "from the abdominal subcutaneous adipose tissue of a 31 y.o. human female" as it states in the GEO soft file, or whether tissue from 8 human donors was pooled as implicitly suggested in the publication. Will email contributing author.

**Comment by ami-day** [comment]
Asked Patrick Searle this:
"One more question I had is about cell type selection using FACS. In the methods the following markers are used to enrich for human stromal vascular cells: CD26, ICAM1, CD45, CD31, CD142. Which of these markers, if any, is a positive selection marker? or are they all used for enrichment of SVCs by negative selection?"

Reply:
"For the SVC sequencing, we excluded cells expressing CD45 and CD31 (Lineage-).   The other markers were used as positive selection markers for sorting cells in downstream validation/functional analysis (CD26, ICAM1, CD142)."

**Comment by ami-day** [comment]
asked Patrick Searle this:
"the metadata file downloaded from the GEO database (accession: GSE128890) suggests there is just 1 Human abdominal subcutaneous adipose tissue sample which is derived from a 31 y.o. female (id: GSM3717979). However, in the publication methods section the collection of 8 Human adipose samples is described. It would be great to know whether the 8 adipose tissues were pooled prior to single cell RNA sequencing, or whether the sequencing data is available for only 1 of these donors."

Reply:
"The sequencing data is only available for 1 donor.  We did validation and follow up by other methods in a larger panel."

**Comment by ami-day** [comment]
The complete metadata sheet based on the publication, GEO metadata and email exchange with Patrick Searle can be found here: https://docs.google.com/spreadsheets/d/1wxbHjaF7Jmleg_UnokdwU1zeKsbiHmbVD61KdUuGEKU/edit#gid=563050045

This metadata sheet needs:

- Secondary review

- Validation with the graph validator

- Transfer of raw fastq from the public archives to ingest UI

**Comment by ami-day** [comment]
Ami to add remaining ontologies first

**Comment by mshadbolt** [comment]
Secondary review:
Project - contributors
* Data curator role isn't present for Ami Day
* multiple authors don't have orcid filled in even though they are available from the paper

Collection protocol
* The collection protocol for the two mice strains seems pretty much the same so it could be combined into one protocol to simplify

Specimen from organism
* I think for organ part the term `UBERON:0014455:subcutaneous abdominal adipose tissue` might suit better for the human specimens
* in the collection protocol for the mice they mention 'white adipose depots' and am wondering if it is worth using the `white adipose tissue - UBERON:0001347` term perhaps inguinal fat pad||axillary fat pad||white adipose tissue? though maybe not important to be that important with the tissue typeas well as the locations? I think I would definitely change the 'inguinal part of abdomen' to the 'inguinal fat pad' though.

Enrichment protocol
* Is there any difference between the protocols that were used for size selection for human vs mouse cells? could potentially collapse into one if no difference

Sequence file
Are we sure that the four sets of I1, R1, R2 from cell suspension SRX5692097 should be analysed separately? i.e. do we know that these are cell suspensions that were split into libraries rather than a single library being split? Just need to confirm this to ensure the process id is grouping the right set of files together and ideally copy this into the library preparation id column.

I think for the other two cell suspensions that they should have all the same proces id as they are the same cell suspension sequenced on different lanes. but maybe I have misunderstood the structure of the experiment.

**Comment by ami-day** [comment]
Thanks @mshadbolt I have made the suggested changes.

For the last point about the process ids: I re-read the methods and there is no specification about whether cell suspensions were divided into technical replicates before library preparation or whether a single library preparation was divided into technical sequencing run replicates. I decided to replace the run accessions in the process ids column with the experiment accessions, as I would think the same experiment accession indicates the runs are technical replicates.

**Comment by ESapenaVentura** [comment]
@ami-day this was included in the export so I am guessing we can close the ticket now?

**Comment by ami-day** [comment]
This project has been exported, so closing this ticket.

**Comment by ami-day** [comment]
Preparing for SCEA with ID E-HCAD-20

**Comment by mshadbolt** [comment]
I think this ticket should be in finished, it was exported as part of MVP and is in the browser here:
https://data.humancellatlas.org/explore/projects/42d4f8d4-5422-4b78-adae-e7c3c2ef511c?catalog=dcp2
