### ISSUE TITLE
Create Dataset Suitability Assessment SOP

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#36]
Description of the task:

This ticket is for the creation of a dataset suitability assessment SOP in relation to the current dataset tracker sheet. The current process requires reflecting on by the team and potentially editing/updating.

Link to related tracker sheet: https://docs.google.com/spreadsheets/d/1rm5NZQjE-9rZ2YmK_HwjW-LgvFTTLs7Q6MzHbhPftRE/edit#gid=0

**Comment by ami-day** [comment]
Here is my first basic version which lists the reasoning I used when previously assessing dataset suitability. It would be great if more than 1 person could check for any errors, particularly in terms of the supported technology types. Feedback and direct updates to this document are very welcome: https://docs.google.com/document/d/1fPVk_Oz7dFhBvNQXJfWXqBXd6k1fjpuUkCmpWbEgeLk/edit

**Comment by ESapenaVentura** [comment]
Hi @ami-day , good job with the document, just a couple of notes:

- Can you add a `purpose of the document` or some kind of contextualisation at the beginning? This might seem obvious for us because we've been involved, but any new wrangler joining the team in the future might need some guidance.

- I like dividing the document by steps and sub-steps (e.g. assess data, assess this specific thing about data), but I think the technology thing is a little bit misleading. In my opinion (happy to hear other @ebi-ait/hca-wranglers ), a dataset is unsuitable in terms of technology if our schema can't capture the proper information, not if the pipelines team can process it. The pipelines team being able to process it would be more of a prioritisation issue, not suitability. e.g. We can currently capture 10xV1 but the pipelines team is not able to process it. This dataset is suitable, but shouldn't be prioritised for the atlas.

Otherwise, good job capturing the points!

**Comment by ami-day** [comment]
Thanks for your comments @ESapenaVentura, making relevant updates now

**Comment by ami-day** [comment]
Done.
