### ISSUE TITLE
GSE117211 (organoids): kidney micro-organoids

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#378]
**Dataset/group this task is for:**

Barbara Treutlin, Melissa Little

**Wrangler responsible for this dataset/lab:**

Ami

**Publication:**

Kumar SV, Er PX, Lawlor KT, Motazedian A et al. Kidney micro-organoids in suspension culture as a scalable source of human pluripotent stem cell-derived kidney cells. Development 2019 Mar 7;146(5). PMID: 30846463

**Google Sheet:**
https://docs.google.com/spreadsheets/d/1O9YaUq5y8AhMtPCJMml97aRameq_gigs/edit#gid=1957877223

**Acceptance criteria for the task:**

- [x] curate metadata
- [x] add ontologies
- [ ] validate with graph validator
- [x] secondary review
- [ ] validate in ingest staging
- [ ] upload to ingest production

**Comment by ami-day** [comment]
Note for 2ndary reviewer: I have contacted Melissa to get more information about the cell line that was used e.g. was it bought from a commercial provider as an iPSC line or fibroblast line and what is the catalog number, etc.

**Comment by Wkt8** [comment]
Hi Ami! I found a few minor errors (some typos and things) but overall it looks great! I liked the organoid_differentiation steps in particular.

Project Tab:
- The project description is the same as the project title - maybe add the abstract instead? 

Project - Funders Tab
- remove 'the' from the National Health and Medical Research Council of Australia'

Differentiation Protocol Tab:
- All of the steps are called organoid_differentation instead of organoid_differentiation (but that's a minor error!) 
- For organoid_differentation_step1, the current retail name is MEF conditional media, and the manufacturer is Thermo Fisher Scientific. 
	- I believe that this isn't quite correct. Thermo Fisher Scientific is the manufacturer for the other reagent in the step (E8 media with Revitacell). I would recommend adding E8 media with Revitacell to the Differentiation media and 'retail name' columns, or removing Thermo Fisher Scientific as the manufacturer. 

Library Preparation Protocol Tab:
- I couldn't find them specifying that 3' was used anywhere in the literature (They mention Chromium 10x v2, but not 3' or 5'). It makes sense to be 3', but wanted to double check, especially since they mention paried-end sequencing.

Sequencing Protocol Tab:
- It is currently 'no' for paired end. However, according to the GEO page and the paper, they mention that they sequenced it as 100bp paired end sequencing. ("These libraries were sequenced simultaneously for UMIs and cDNA fragments using paired-end reads.") and ('Extraction protocol' https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3273570) 
- We also have the comment in the spreadsheet 'If 3' 10x v2 was used, enter no.' I'm not sure why this comment is here? From the 10x genomics website 3' 10x v2 appears to be able to perform paired end sequencing. (https://support.10xgenomics.com/single-cell-gene-expression/index/doc/technical-note-chromium-single-cell-3-v2-libraries-sequencing-metrics-for-illumina-sequencers) 

Analysis File Tab: 
- There was a typo in the programmatic name! This is my fault as I made the typo in the template previously. The template is fixed, so for the next project maybe get a fresh copy of the template? In this, File Source is currently "analysis_file.file._core.file_source" and it should be "analysis_file.file_core.file_source" and the source should be 'GEO'

Analysis Protocol Tab:
- Potentially add 'alignment' and 'cell filtering' into the 'Derivation Process' column

**Comment by ami-day** [comment]
Thanks for the review @Wkt8 !

- In terms of the 10X v2 method, I had found that the end bias was 3' based on the umi and cell barcode lengths which are described here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3273570

- For 10X 3' or 5' data, we standardly enter paired end is 'no' in the hca metadata spreadsheet because 1 read contains only the umi and cell barcode reads, whereas only read 2 contains the cDNA.

- other than the above I have made your recommended changes, thanks!
-

**Comment by ami-day** [comment]
Downloading the fastq files

**Comment by ami-day** [comment]
Uploaded the fastq files and matrix to ingest prod. Jacob is currently working on an ingest issue which seemed to be triggered when an extra incorrect fastq file was uploaded then removed. We can submit it once the issue is fixed.

**Comment by ami-day** [comment]
Exported and submitted import form.

**Comment by ofanobilbao** [comment]
@ami-day will this be brokered to SCEA or it can be closed?

**Comment by ami-day** [comment]
> @ami-day will this be brokered to SCEA or it can be closed?

It can be closed, it's not really suitable for SCEA. Btw, when I move a ticket to the finished column in this board, is there a way keep it in the finished column AND move it queued for wrangling in the SCEA board? Otherwise you will keep having to ask this question every time I move a dataset to finished.

**Comment by ami-day** [comment]
Right ok I see. So from now on, can we assume a dataset ticket can be closed if the "scea" label is not selected? and I will make sure I label future datasets that are suitable with this label.
