### ISSUE TITLE
No CGMs in DCP9 release

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#420]
**Description of the issue**

As per what was discussed in the [slack channel](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1630713676022700), CGMs are not showing up for a lot of projects. This is likely to happen because the `genus_species` field is not filled.

 - [x] [ad04c8e7-9b7d-4cce-b8e9-01e31da10b94](https://contribute.data.humancellatlas.org/projects/detail?uuid=ad04c8e7-9b7d-4cce-b8e9-01e31da10b94) (Rachel) **GEO USED AS CHECKSUM**
 - [x] [b9484e4e-dc40-4e38-9b85-4cecf5b8c068](https://contribute.data.humancellatlas.org/projects/detail?uuid=b9484e4e-dc40-4e38-9b85-4cecf5b8c068) (Rachel)  **GEO USED AS CHECKSUM**
 - [ ] #460
 - [x] [56e73ccb-7ae9-4fae-a738-acfb69936d7a](https://contribute.data.humancellatlas.org/projects/detail?uuid=56e73ccb-7ae9-4fae-a738-acfb69936d7a) (Rachel)
 - [x] [8dacb243-e918-4bd2-bb9a-aac6dc424161](https://contribute.data.humancellatlas.org/projects/detail?uuid=8dacb243-e918-4bd2-bb9a-aac6dc424161) (Rachel)
 - [x] [da2747fa-2921-42e0-afd4-39ef57b2b88b](https://contribute.data.humancellatlas.org/projects/detail?uuid=da2747fa-2921-42e0-afd4-39ef57b2b88b) (Rachel)  **GEO USED AS CHECKSUM**
 - [x] [dd7f2436-0c56-4709-bd17-e526bba4cc15](https://contribute.data.humancellatlas.org/projects/detail?uuid=dd7f2436-0c56-4709-bd17-e526bba4cc15) (Rachel)  **GEO USED AS CHECKSUM**
 - [x] [34cba5e9-ecb1-4d81-bf08-48987cd63073](https://contribute.data.humancellatlas.org/projects/detail?uuid=34cba5e9-ecb1-4d81-bf08-48987cd63073) (Rachel)  **GEO USED AS CHECKSUM**
 - [x] [4af795f7-3e1d-4341-b867-4ac0982b9efd](https://contribute.data.humancellatlas.org/projects/detail?uuid=4af795f7-3e1d-4341-b867-4ac0982b9efd) (Rachel)  **GEO USED AS CHECKSUM**
 - [x] [8999b456-6fa6-438b-ab17-b62b1d8ec0c3](https://contribute.data.humancellatlas.org/projects/detail?uuid=8999b456-6fa6-438b-ab17-b62b1d8ec0c3) (Will)  **GEO USED AS CHECKSUM**
 - [x] [79b13a2a-9ca1-42a4-97bd-70208a11bea6](https://contribute.data.humancellatlas.org/projects/detail?uuid=79b13a2a-9ca1-42a4-97bd-70208a11bea6) (Will) **NO ANALYSIS FILE METADATA**
 - [x] [d7845650-f6b1-4b1c-b2fe-c0795416ba7b](https://contribute.data.humancellatlas.org/projects/detail?uuid=d7845650-f6b1-4b1c-b2fe-c0795416ba7b) (Wei) **SPECIMEN NOT LINKED TO CELL SUSPENSION**
 - [ ] #459
 - [ ] #458

**Acceptance criteria**:
- [ ] Exact reason has been determined for each dataset and the ticket has been updated
- [ ] Datasets have been corrected and exported

**Comment by ESapenaVentura** [comment]
@Wkt8  asked about fields used for indexing matrix files

**Comment by ESapenaVentura** [comment]
`d7845650-f6b1-4b1c-b2fe-c0795416ba7b` dataset is being fixed at the moment

**Comment by Wkt8** [comment]
Have exported an update (d7845650-f6b1-4b1c-b2fe-c0795416ba7b) as an update to existing metadata for release 10 (sep 27th). This should fix the problem.

**Comment by willrockout** [comment]
`79b13a2a-9ca1-42a4-97bd-70208a11bea6` Doesn't have any CGMs so its good

**Comment by willrockout** [comment]
@ESapenaVentura As with the other ticket I've listed below the breakdown of our datasets current status:

Complete Status/Needs kicking:

1. ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
2. 34cba5e9-ecb1-4d81-bf08-48987cd63073
3. 56e73ccb-7ae9-4fae-a738-acfb69936d7a
4. 8dacb243-e918-4bd2-bb9a-aac6dc424161
5. da2747fa-2921-42e0-afd4-39ef57b2b88b
6. dd7f2436-0c56-4709-bd17-e526bba4cc15
7. 4af795f7-3e1d-4341-b867-4ac0982b9efd

Exported:

1. 8999b456-6fa6-438b-ab17-b62b1d8ec0c3

Needs new files description ontology:

1. b9484e4e-dc40-4e38-9b85-4cecf5b8c068

Other problems currently working on:

1. 9bab0f03-a725-4a13-9ab1-196e46cd80ed

**Comment by jacobwindsor** [comment]
@willrockout the following projects are now in valid state and are ready to export with the only metadata option: 

```
ad04c8e7-9b7d-4cce-b8e9-01e31da10b94
34cba5e9-ecb1-4d81-bf08-48987cd63073
56e73ccb-7ae9-4fae-a738-acfb69936d7a
8dacb243-e918-4bd2-bb9a-aac6dc424161
da2747fa-2921-42e0-afd4-39ef57b2b88b
dd7f2436-0c56-4709-bd17-e526bba4cc15
4af795f7-3e1d-4341-b867-4ac0982b9efd
```

**Comment by rachadele** [comment]
I'm not able to access 8dacb243-e918-4bd2-bb9a-aac6dc42416. Also, could we have the status for b9484e4e-dc40-4e38-9b85-4cecf5b8c068 changed to valid as well?

**Comment by ESapenaVentura** [comment]
@rachadele 8dacb243-e918-4bd2-bb9a-aac6dc42416 does not exist, are you guys sure it's the proper UUID?

**Comment by jacobwindsor** [comment]
@rachadele I believe you mean 8dacb243-e918-4bd2-bb9a-aac6dc424161

**Comment by jacobwindsor** [comment]
@rachadele b9484e4e-dc40-4e38-9b85-4cecf5b8c068 is now in "valid" state

**Comment by rachadele** [comment]
@jacobwindsor @ESapenaVentura yes, sorry that was a typo! thank you!

**Comment by ami-day** [comment]
As listed above, the species, organ and organ part for this project are not showing up properly:
**uuid:** e57dc176-ab98-446b-90c2-89e0842152fd
**hca portal link:** https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22project%22,%22terms%22:%5B%22KidneyOrganoidsPlasticity%22%5D%7D%5D

It looks from the spreadsheet that this is likely because:

- A cell line is used as the input biomaterial in the organoid tab
- An organoid sample is used as the input biomaterial in the cell suspension tab
- There is no donor organism
- There is no specimen from organism

While this is intended based on the experimental design, it looks like there could be an issue with how the organ and species labels are retrieved for this type of experimental design. @hannes-ucsc do you know why this might be? I think you are probably the best person to ask?

**Comment by hannes-ucsc** [comment]
https://humancellatlas.slack.com/archives/C9XD6L0AD/p1630016648010200

**Comment by ofanobilbao** [comment]
@willrockout and @rachadele can you, please, confirm if you are done with your datasets? If you could tick the boxes and confirm that would be great.

**Comment by Wkt8** [comment]
@ami-day this is related to this conversation in slack (https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1630486450020300?thread_ts=1630016648.010200&cid=C9XD6L0AD) about how the browser obtains the value for genus_species from donor_organism or specimen_from_organism - they currently do not obtain it from organoid.genus_species 

This ticket was made for fixing this issue: https://github.com/HumanCellAtlas/metadata-schema/issues/1415

**Comment by hannes-ucsc** [comment]
Azul only considers `donor_organism.genus_species`. You can fix this issue without fixing HumanCellAtlas/metadata-schema#1415.

**Comment by willrockout** [comment]
@jacobwindsor Can you kick  9bab0f03-a725-4a13-9ab1-196e46cd80ed? Once that has been re-submitted everything will be done from our side. @ofanobilbao for some reason, I'm not able to check the boxes.

**Comment by ofanobilbao** [comment]
Thanks for the update @willrockout. I have checked the boxes, with the exception of 9bab0f03-a725-4a13-9ab1-196e46cd80ed that needs kicking. @aaclan-ebi could you, please, kick this so that it can be re-submitted?

**Comment by amnonkhen** [comment]
@ESapenaVentura to update new tickets with proper names and actions

**Comment by aaclan-ebi** [comment]
@ofanobilbao @willrockout , the submission for project `9bab0f03-a725-4a13-9ab1-196e46cd80ed` is now Exported. 


Dev notes:
"Kicking" is just the term we use when we do the workaround to set a 'Complete' submission back to Valid and make it submittable again. At the moment, only Exported -> Valid transition is allowed. This happens when you edit metadata and it's revalidated.

Steps:
1. Force set submission to be valid: do a PUT method to `commitValid` link in submission envelope - need a token.
2.  Redeploy state tracker using `kubectl delete pod pod-name`  K8 should just launch a new pod --- this is needed so that when you click submit, the submission will be set successfully to the next state
3.  Before you click submit button, select  “Export only metadata….” else it’s exporting is going to fail, because the submission upload area is already cleaned up in Ingest

For future implementation: we should think about how the exporter will determine only the metadata which changed and only propagate those changes. And think of a better way to indicate that data files are no longer in the staging area upon export. This may be covered when we fully implement DCP2 specs for updates.

**Comment by ami-day** [comment]
We have separated the 2 pending tickets so this ticket can be moved to done.
