### ISSUE TITLE
20f37aaf-caa1-40e6-9123-be6ce8feb2d6: "DopaminergicNeuronDifferentiation" (New): ami@ebi.ac.uk

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#504]

**Comment by ami-day** [comment]
Looks ok to me, except I think we need to discuss how we represent "anatomical entity" for datasets which are iPSCs or organoids derived from reprogrammed cells. E.g. the anatomical entity is showing as "skin of body", because skin cells were reprogrammed to generate the iPSCS, which were then differentiated to neurons, and so the "model organ" is shown as "brain", which is correct. I am just wondering if we should not display the anatomical entity when there is a model organ which is the relevant organ. @ESapenaVentura @Wkt8 any thoughts?
