### ISSUE TITLE
SCP259 - RewiringHumanColon

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#536]
### Project short name:
HumanColonRewiringUlcerativeColitis
### Primary Wrangler:
Irene
### Associated files

* Google Drive: https://drive.google.com/drive/folders/1A8okIFou6pr8KOr_SVLhLI982tyu_5Dn

### Published study links

* Paper: 10.1016/j.cell.2019.06.029

* Accessioned data: [SCP259](https://singlecell.broadinstitute.org/single_cell/study/SCP259/intra-and-inter-cellular-rewiring-of-the-human-colon-during-ulcerative-colitis)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by aaclan-ebi** [comment]
The authors replied back. @ipediez to continue on this.

**Comment by ipediez** [comment]
Only missing to upload the files, then ready for secondary review

**Comment by ami-day** [comment]
Tagging myself as secondary reviewer

**Comment by Wkt8** [comment]
Completed secondary review. Feel free to poke or call me on slack! Overall the modelling of it looked good, but the paper itself had some weird discrepancies (N110 vs N897, etc.).

Donor Organism Tab:
There is a discrepancy here with N110 vs. N897 in the supplementary file. In the Supplementary file, N897 is used as the donor organism ID in the 'Subject Metadata' tab, but N110 is used as the ID in the 'Sample_Metadata' tab. I think this actually shouldn't be a problem as long as you use the donor organism ID consistently (which you have). Just wanted to bring it to your attention. 

The two protocols in the 'Enrichment Protocol' tab should actually be dissociation protocols 

Likewise, the protocol in the 'Dissociation Protocol' tab should be an enrichment protocol (size exclusion) with a maximum size of 40uM. 

Something is wrong with the number of specimen from organisms. I believe that there are doubles of some samples (e.g. there are 5 specimen from organisms for N110:
N110_Epi_A
N110_LP_A
N110_LP_B
N110_A
N110_B

Whereas there are only 3 cell suspensions for N110 in the cell suspension tab. Similar for the other subject IDs, e.g. N46. 

In the Cell Suspension tab: The Enrichment Protocol IDs are not filled in.
Dissociation Protocol IDs only have 1 protocol being used. 

Sequencing Protocol Tab there is a typo for 
'sp_Hi-Seq' in the Sequencing Protocol Description (sampes -> samples) 
- I couldn't find the information on the model number of the sequencing instruments (only found NextSeq and Hi-Seq) but i'm guessing you got it from one of the other supplementaries? 

Analysis File 
'File Source' should be 'SCP' instead of 'Publication'?

**Comment by prabh-t** [comment]
@ipediez corrected instructions from @wei. to be completed today.

**Comment by Wkt8** [comment]
Semi-blocked by the issue where submissions are being unlinked from the project. Ticket [here](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/612)
