### ISSUE TITLE
Single-cell RNA sequencing identifies celltype-specific cis-eQTLs and co-expression QTLs

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#578]
Primary wrangler
Ami

Secondary wrangler
Ida

Paper:
Single-cell RNA sequencing identifies celltype-specific cis-eQTLs and co-expression QTLs
https://www.nature.com/articles/s41588-018-0089-9#Sec2

**Google Sheet:**
https://docs.google.com/spreadsheets/d/1rxkVPdmzIQolyiQA4t08FV-P6o9i37tFpyNu5eDIXIE/edit#gid=1549964870

**Ingest:**
https://contribute.data.humancellatlas.org/projects/detail?uuid=974df02f-fc85-4773-bbc5-a772baad95ef

**Comment by ami-day** [comment]
I'm putting this dataset in the stalled column because I need to contact the corresponding authors with some questions about the donor metadata and data access

**Comment by ami-day** [comment]
I have emailed them.

**Comment by ami-day** [comment]
Their data should be here: https://eqtlgen.org/sc/datasets/vanderwijst2018.html
Though the link is not working atm, their website is under maintenance.

**Comment by ami-day** [comment]
The authors gave me a new working link.

**Comment by idazucchi** [comment]
Hello!
I've finished reviewing. Overall it looks good, I have some comments:

### Donor
- there is no mention of donors with disease in the paper so I would fill out the known disease field for all donors as `normal`

### Collection protocol
- publication doi: the doi points to a publication describing the cohort, maybe you can move it to the supplementary materials?
- you could add the Vacutainer in the retail kit field 


### Specimen
- is it worth it to put blood for organ part as well? I'm not sure if we want this field filled for blood/ if the browser team expects it to be filled
- like the donors, there is no known disease so I would mark all specimens as normal

### Cell suspension
- the cell viability was assessed via trypan blue staining so you could fill in the `cell viability method`
- you can fill in `selected cell type` with peripheral blood mononuclear cell
- the authors mention that they pooled together samples from different donor with a cell count of 1,750 cells/donor. Since there's no sequence files it makes sense to model the cell suspension of each donor separately like you did. You could enter 1750 as `estimated cell count` for each donor


### Library preparation protocol
- you could fill `retail kit` with Single Cell 3′ Library & Gel Bead kit version 2 (120237) and i7 Multiplex kit (120262)

### Analysis protocol
- for analysis_protocol_gene_expression:
  - the computational method field is filled out but I think that information should be part of derivation process
- for analysis_protocol_cell_types
   - you could fill in the derivation process field

### Analysis file
- for cell_barcodes.zip I would change the content description to Molecular property identifier because the content of the file is similar to the CellRanger barcode file

**Comment by ami-day** [comment]
Thanks @idazucchi , I have made most of these changes.

**Comment by ESapenaVentura** [comment]
Data wrangler is set up as contributor (Missing the data curator ontology), and it appears as if it's the first author. Needs update

**Comment by ami-day** [comment]
Updated with my role as data curator: https://contribute.data.humancellatlas.org/projects/detail?uuid=40272c3b-4697-4bd4-ba3f-82fa96b9bf71&tab=upload
the status is still in "exporting" state though.

**Comment by ami-day** [comment]
Submitted the update.

**Comment by ami-day** [comment]
exported.

**Comment by ami-day** [comment]
Looks as expected in data portal.
