### ISSUE TITLE
ClonalArchitecture

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#582]
### Project short name:
ClonalArchitecture
### Primary Wrangler:
@ESapenaVentura 
### Secondary Wrangler:
TBD

### Associated files:

* Google Drive: https://drive.google.com/drive/u/0/folders/1_4bBKAi2RF2oPQI0K-1JAl58pyFYGOIb
* Preprint: https://www.biorxiv.org/content/10.1101/2021.04.28.441762v2

### Key Events

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [ ] Receive T&C form filled out by at least 1 representative of group/project
- [ ] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator & Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by ESapenaVentura** [comment]
Asked for a deadline for the dataset and to fill out the consent form - Waiting on the reply

**Comment by Wkt8** [comment]
Cecilia asked if we could archive to ArrayExpress - which is not part of our usual process (it's very manual) - and we have informed them as such. 

We now have tools like the direct archiving script which should speed up archiving to ENA / BioSamples. We should archive to them if possible - unless contributors have a specific issue with it.

**Comment by prabh-t** [comment]
Enrique is working on this.

**Comment by ESapenaVentura** [comment]
Asked for a sequencing run --> sequencing instrument map

**Comment by ofanobilbao** [comment]
@ESapenaVentura might move this to secondary review

**Comment by ESapenaVentura** [comment]
Dataset is ready for secondary review

For the reviewer, just a couple of small notes:

- Green tabs: I think I got most of the metadata available
- Yellow tabs: I am pretty sure I am missing something (e.g. sequencing protocols and their linkings to the files), so please be very aware when reviewing this!

**Comment by Wkt8** [comment]
Still missing some information from Cecilia.

**Comment by ami-day** [comment]
Hi @ESapenaVentura this looks good to me! I am highlighting mostly nitty gritty details, and also I need to ask you on slack about the experiment design..the extra sample types and pooling isn't clear to me from the preprint.

**General**

- Multiple ontology fields are missing. I think this is because the latest metadata file got corrupted and you plan to add these soon.

- Some of the protocol descriptions are in the format of instructions, unlike the past tense. I think it would be good to aim to keep the protocol descriptions consistent in format within and between projects.

**Project**

- PRJEB51634 can be added to the field project.insdc_study_accessions

**Collection Method**

- other_organ_collection description: Is the location they provide for each organ type included in the organ part metadata in the specimen from organism tab? It looks like some regional info. is missing and could be useful e.g. left lower lobe of the lung, right lobe of the liver.

- other_organ_collection: I think include "via/from the Cambridge Biorepository for Translational Medicine (CBTM)".

- Maybe rename the method from "other_organ_collection" to "solid_tissue_collection" or "solid_tissue_collection_from_organs".

**Donor organism**

- Is the BMI not indicated because it is given as a range of values in the preprint (which I think the hca metadata schema might not support just yet)?

- For this kind of study, the days in hospital is probably useful as a time-course value and unit (provided in the preprint donor metadata table).

- Can Smoking be added as Y/N/unknown? (provided in the donor table). It doesn't follow the example format, but I seem to remember filling this before as only "smoker" or "non-smoker". TBD based on donor metadata schema.

**Specimen from organism**

- The disease field is not filled.

**Dissociation protocol**

- macs_dissociation is a joint mechanical/enzymatic dissociation method. It isn't  magnetic affinity cell sorting. It should be 2 protocol types: mechanical and enzymatic.

- The following is missing from the beginning of the blood_enzymatic_dissociation description: "Bone marrow aspirates and blood samples were diluted 1:1 with PBS and layered directly onto ficoll for mononuclear cell isolation." The included description isn't clear when this piece of information missing.

- After the first 2 dissociation protocols, I don't see the descriptions for the following protocols in the paper. They seem to be alternative methods to the macs_dissociation method. Where did you get this information?

**Enrichment protocol**

- 70_um_strainer: 70um should be the maximum size selected as opposed to minimum size selected

- After the first 2 dissociation protocols, I don't see the descriptions for the following protocols in the paper. They seem to be alternative methods to the macs_dissociation method. Where did you get this information?

**Cell suspension**

- About the pooling of specimens "taken from mixed tissues" and the combination of protocols for some specimens: I will message you on slack, assuming you got this from a public db or the authors as I don't see it in the paper!

**Library preparation protocol**

**Sequencing protocol**

- Cellranger software (version 3.0.2, 10x Genomics Inc.) could be added.

**Sequence file**

- The sequencing protocol ids are missing.

**Analysis file**

- Some fields are missing. I think maybe they had been included in the latest corrupted file you mentioned? examples: content description, library prep protocol, sequencing protocol.

It will be a really nice study to add this next data release :)

**Comment by ofanobilbao** [comment]
Cecilia is very busy to send what we need. Might be worth sending an email to a contact in Sanger for the sequencing instrument mapping. @Wkt8 to provide email to @ESapenaVentura

**Comment by Wkt8** [comment]
Could try to email Elena Prigmore (ep2@sanger.ac.uk)

**Comment by ofanobilbao** [comment]
@ESapenaVentura there is now a peer reviewed publication for this project. It might answer or provide the information you need.

https://www.science.org/doi/10.1126/science.abl5197

**Comment by ofanobilbao** [comment]
@ESapenaVentura 

Seems to have been published in DCP by UCSC.

https://contribute.data.humancellatlas.org/projects/detail?uuid=04e4292c-f62f-4098-ae9b-fd69ae002a90&tab=project

The pre-print is not captured anywhere though. I think they might have edited your Ingest entry for it. Cause for whatever reason is not picking up the DOI. I believe they have added posteriorly. We might need to file a bug for that as it should not be like that.

This ticket can probably be closed

**Comment by ofanobilbao** [comment]
Closing as it was already pushed to DCP
