### ISSUE TITLE
GSE144024,OEP001507 - Decoding Human Megakaryocyte Development

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#592]
### Project short name:
MegakaryocyteDevelopment
### Primary Wrangler:
Ida
### Associated files

* Google Drive: [MegakaryocyteDevelopment](https://drive.google.com/drive/folders/1jWxHLTOMdjakQvGMgE8rZcFDjbhecKjn)

### Published study links

* Paper: https://doi.org/10.1016/j.stem.2020.11.006

* Accessioned data:  [GSE144024](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144024)
                                    [OEP001507](https://www.biosino.org/node/project/detail/OEP001507)

**Ingest:**
https://contribute.data.humancellatlas.org/projects/detail?uuid=a9f5323a-ce71-471c-9caf-04cc118fd1d7&tab=project

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
I've red the paper, I'll start wrangling it on Tuesday

**Comment by idazucchi** [comment]
I've started to fill in the spreadsheet for the data in GEO while I figure out exactly what data is in Node.

**Node**
I have problems with downloading files from Node for this dataset:

1. Download via https breaks off every ~30min
2. Download via ftp is not possible because the link for any file is ”ftps://www.biosino.org:2122”’ which doesn’t point to anything
I emailed the support team from node to check the source of these issues.

I will probably email the authors to clarify a few things about the SmartSeq2 data in Node:
- there are 7 donors, 3 YK and 4 FL but no way to match up donor and files
- Since it's SmartSeq2 I'm expecting there to be several smaller fastq files, one for each well. Instead I have either 2 or 4 files per donor in the range of 10GB

**Comment by idazucchi** [comment]
I emailed again the support team from Node, hopefully they will be able to help me download the files.

I emailed the authors asking for clarifications. They might also be able to help with the files (?)

**Comment by idazucchi** [comment]
**Node**
The support team replied with instructions to download the data via ftp. It could be worthwhile to save them in our documentation because I didn't find them anywhere in Node
Interestingly there is a size limit of 2 GB on https download.

I started downloading the files in the EC2

**Authors**
They replied and pointed out a new paper that I've added to ingest since it was off our radar
Still waiting for the clarifications

**Comment by idazucchi** [comment]
Still waiting for a reply:
I don't know if the file in node are multiplexed and who their donors are

**Comment by idazucchi** [comment]
I emailed the authors again, hopefully they will answer.
For now I'll move the dataset to stalled because I can't move forward until I know the donors for the fastq files from Node

**Comment by idazucchi** [comment]
The authors have replied but I'm still unsure of how to match up the samples they provided info about and their donors
I've tried to set up a meeting, hopefully that will clear things up

**Comment by idazucchi** [comment]
I've opened a ticket in the dev board (will move to ops) for a metadata validation issue enocuntered while uploading the submission. 
The submission is otherwise fine and it passed graph validation so I will move this to secondary review.

There has been a bit of comunication with the authors, and that is the source of some information that is not available anywhere else. These are the threads:
- https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/tvxZPscWB1o/m/pS87H0piAQAJ
- https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/XmPF1WRsO2g/m/NX7KMkSIAQAJ

**Comment by ami-day** [comment]
Hi @idazucchi , it looks good, here are my comments:

**Project**

- I think you have pasted some notes into the Project Description field instead of the project description.
- I reordered some of the project accession fields and estimated cell count as they were in the wrong columns
- I added the project inside accession (PRJ…).

**Project - Contributors**

- emails are missing
- curator (you) is missing
- the contributor (yes/no) is missing
- person role (data curator) is missing

**Project - Publication**

- I changed the HCA publication? to "no" instead of "false"

**Cell line**

- I'm not sure about the organ being "yolk sac". I think this could be organ="uterus" and organ part="yolk sac"
- I think that the cell line tissue field might be better left blank as opposed to "embryo"
- For the differentiated cell lines, I think the organ model should be blood as opposed to hematopoietic system

**Specimen from organism**

- I think the organ should be "liver" as opposed to "fetal liver"

**Dissociation protocol**

- There is no dissociation step in the description, maybe add: “Cells were dissociated." at the end of the paragraph and then addd “enzymatic dissociation” as the method text and ontology, as that is almost always how cell lines are dissociated during tissue culture.

**Cell suspension**

-  there are some extra spaces between ids and “||” in the enrichment protocol id column, I think it might cause problems when validating

**Library preparation protocol**

- I didn't see the 10X version in the publication methods. Did you get this from the author of GEO? It looks like you entered v2.

**Sequencing protocol**

- I think for Smart-seq2 sequencing protocol the method should be "full length single cell RNA sequencing" as opposed to "tag based single cell RNA sequencing". A cell barcode is mentioned, but I think that is likely illumina library prep. indices which can be used to label each well (cell) in a well plate. I might be wrong though as they do say they used a modified protocol.
- Some of the analysis protocol is in the sequencing protocol descriptions (e.g. alignment). I would remove that part.

**Analysis protocol**

- The Smart-seq2 analysis protocol is missing. Are there no matrices available for the Smart-seq data?

**Supplementary file**

-  I think this file: SS2_before_and_after_QC_meta.data.xlsx should be in the analysis file tab and linked to a Smart-seq analysis protocol.

**Comment by idazucchi** [comment]
I've applied the changes, I'm waiting for the metadata to be valid

**Comment by idazucchi** [comment]
running graph validation
