### ISSUE TITLE
Investigate files stuck in metadata validation

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#621]
**Dataset this task is for:**

HumanBCellsTonsils [#593](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/593)

**Wrangler responsible for this dataset:**

Ida

**Description of the task:**

There are 4 fastq files that are stuck on validating metadata since 24/1/22 6PM [submisssion](https://contribute.data.humancellatlas.org/submissions/detail?uuid=73e4e3b7-5bbc-4720-9c80-8edbd6bdd8ee&project=24d0dbbc-54eb-4904-8141-934d26f1c936)
HFH5VBGX7_BCP003_MBC_S2_L003_I1_001.fastq.gz
H2MJFBGXB_BCP008_IgMneg_MBC_S2_L002_R2_001.fastq.gz
H2MJFBGXB_BCP008_IgMneg_MBC_S2_L003_R2_001.fastq.gz
H5F2WBGX9_BCP006_Total_S9_L001_R1_001.fastq.gz

- Find out why the validation process is stuck
- Restart the metadata validation

**Acceptance criteria for the task:**

- [ ] files passed metadata validation

**Comment by Wkt8** [comment]
@jacobwindsor could you please investigate?

**Comment by jacobwindsor** [comment]
Looking back on the errors, it seems each of these files is stuck in validating for a slightly different reason

- 61eec1d07701fb51a5c3c2cb and 61eec1e07701fb51a5c3c3aa are stuck because they were already validating when valdiation requested
- 61eec1d37701fb51a5c3c342 and 61eec1d37701fb51a5c3c345 are stuck because the transition to Valid failed -> core retruned an error since it believe the current state to be DRAFT not VALIDATING

In all cases, it seems that the documents did validate but the updating of the state failed. I have manually updated the state and will investigate further why this has happened.

I have also found [this strange occurrence in the logs](https://monitoring.ingest.archive.data.humancellatlas.org/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bcontainer%3D%5C%22ingest-validator%5C%22%7D%20%7C~%20%5C%22InvalidFormatException%5C%22%22%7D%5D) which I am investigating

**Comment by jacobwindsor** [comment]
I have made this PR to fix one of the bugs I found in the logs https://github.com/ebi-ait/ingest-core/pull/111

**Comment by jacobwindsor** [comment]
The PR has been merged. I'm not 100% sure that this PR will stop the issue happening again but let's monitor and see if this occurs again before I dive further into it
