### ISSUE TITLE
LitSuggest data curation

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#629]
### Description

I've been testing the LitSuggest tool from NCBI as a discovery tool for new datasets to include in the HCA. This tool performs a weekly selection of published literature available at PubMed, that needs to be manually curated. 

### Documents

- [LitSuggest weekly digest (Jan 10 2022 to Jan 16 2022)](https://www.ncbi.nlm.nih.gov/research/litsuggest/project/619bc7d1ae6862544ac15c53/job/61e58cd999d23f36b6d144ce?type=positive&page=6)
- [Curated spreadsheet](https://docs.google.com/spreadsheets/d/16S2lvFCw0QBzohYY7e78XYP_tvxjYe0F3B-iUaCgCDo/edit?usp=sharing)

### To do

- [ ] Curate the list of positive literature of the weekly digest from Jan 10 2022 to Jan 16 2022 (70/340)

**Comment by Wkt8** [comment]
The LitSuggest tool was fed eligible and non-eligible from Ingest in order to train a specific network - it then searches through pubmed and provides a weekly digest of what it thinks is eligible and non-eligible. 

Irene is curating what it thinks is eligible, and checking if it is or is not, and then will probably feed back into LitSuggest to further increase it's accuracy. 

Help with curating the LitSuggest weekly digest would be great.

**Comment by Wkt8** [comment]
Irene working through it with 5 - 10 datasets a day.

**Comment by ESapenaVentura** [comment]
@ipediez created a poll to have a discussion about NLP and how this litsuggest curation works

**Comment by ofanobilbao** [comment]
Rather than Stalled, no-one is actively working on this. Either we move it to the Backlog or we close it. But being in stalled does not make sense to me. It's simply not being worked on. @gabsie any thoughts?

**Comment by idazucchi** [comment]
at this point in time our wrangling is very dependent on what the bionetworks select for the atlas so we are not focusing on discovering more datasets
I'm closing this ticket since it's not needed
