### ISSUE TITLE
myocardialInfarction- Kuppe

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#661]
### Project short name:
~~HumanmyocardialInfractionSpatialMap~~ myocardialInfarction
### Primary Wrangler:
@ESapenaVentura 
### Secondary Wrangler:
Ida

### Associated files:

* Google Drive: https://drive.google.com/drive/folders/1Zq2Ci5XLQVCsdEhqJ9SSSZJkPq0q3Zy3
* Ingest project: https://contribute.data.humancellatlas.org/projects/detail?uuid=e9f36305-d857-44a3-93f0-df4e6007dc97&tab=project

### Key Events

- [x] Send initial instructions about contributing, including questionnaire and T&Cs
- [x] Receive project questionnaire
- [x] Assign the Primary Wrangler
- [x] Receive T&C form filled out by at least 1 representative of group/project
- [x] Send custom metadata template spreadsheet, how-to guide and directions for submitting data, matrix and cell annotation files.
- [x] Receive spreadsheet (to a sufficient standard to submit dataset) 
- [x] Receive data, matrix and cell annotation files (to a sufficient standard to submit dataset)
- [x] Curate metadata spreadsheet with ontologies
- [x] Upload sheet to validate metadata
- [x] Run graph validator & Check linking
- [x] Validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Get final approval of submission from the contributor including release date, metadata spreadsheet and data files 
- [ ] Submit to production and inform ingest-devs the project is ready for archiving
- [x] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

### Please track the below as well as the key events:
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by ofanobilbao** [comment]
Enrique has reached out to them and they finally came back to him. They will have a meeting to move this forward

**Comment by idazucchi** [comment]
@ESapenaVentura will set up a meeting this week

**Comment by Wkt8** [comment]
Enrique had a productive meeting with contributors yesterday. Got lots of metadata (ATAC-seq, Visium, 10X) and contributors seemed very responsive. 

Archiving is not needed (managed access) but they have agreed to send a metadata table with the metadata of the donors in the project (differs from the preprint). 

- [ ] Enrique to curate
- [ ] Enrique to send back a pre-filled spreadsheet with the data spreadsheet guide 
- [ ] Continue wrangling 

Dataset is still in early stages so will probably not make it into Release 15 (also due to them wanting to hold off on data becoming public).

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to answer email

**Comment by prabh-t** [comment]
Enrique has finished curating the metadata. Dataset contains living donors. Waiting for contributors. Not ready for secondary wrangling yet.

**Comment by gabsie** [comment]
Gabs - to formulate reply according tp what Tony advised.

**Comment by ofanobilbao** [comment]
@gabsie to handle this

**Comment by ami-day** [comment]
enrique has sent an email, waiting to hear back

**Comment by ESapenaVentura** [comment]
On our side, most has been done.

I have stripped the donor metadata completely and we are going to discuss about modelling issues at the demo meeting today.

Now waiting for the files to be uploaded

**Comment by ESapenaVentura** [comment]
I can confirm there is no issue uploading a spreadsheet without donor information to ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=1835a039-b9c4-4055-8308-498b009a063f&project=e9f36305-d857-44a3-93f0-df4e6007dc97

**Comment by gabsie** [comment]
perfect! now then we are waiting for Hannes to say what happens further down the pipe.

**Comment by ESapenaVentura** [comment]
Ready for secondary review!

The project metadata is not updated in ingest because of the error [here](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/789), so please review from spreadsheet

**Comment by idazucchi** [comment]
Hi Enrique!
I'm done with the secondary review. The dataset looks great, there are just some minor things

### Donor
- we can include the disease for the specimen but not for the donor? what is the rationale? I’m curious 
- there is no donor description, is this to avoid including identifying information?
- [x] I checked, there is no identifying information for the donors


### Collection protocol
- I think this bit might be either imaging preparation or preparation for other techniques, I would exclude it from the description
> Tissues were dounced in liquid nitrogen and 7-10^3 pieces were embedded in O.C.T. compound (Tissue-Tek) and frozen on dryice. 10 µm cryo tissue sections were HE stained and the appropriate tissue regions selected for further processing.
- I would suggest surgical resection for the ontology term

### Dissociation protocol
- mechanical dissociation might be more appropriate for the ontology term


### Cell suspension
- Would it make sense to move the enrichment step to select the nuclei to the analysis file tab?

### Imaged specimen
- donors P21, P22, P23 don't have an imaged specimen, they might not be part of the experiment. This is just a memo to remove the donors and specimen if no files show up 

### Library preparation
- for visium isn’t the nucleic acid source bulk cell rather than single cell?

### Sequencing
- for visium do we have a sequencing method term we agreed on to use? if not we should, so we could add it to the cheatsheet

### Analysis protocol
- you could fill in the computational methods field

**Comment by ESapenaVentura** [comment]
Hi Ida! I have applied most of the corrections, I have a couple of things I'd like to comment/discuss:
- Dissociation protocol: they used lysis buffer so it sounds to me more like enzymatic dissociation, but happy to discuss further!
- Cell suspension: not sure I understand the request
- Library preparation: Happy to put that, it's a little bit of in a gray area (I think the resolution is ~10 cells)
- Sequencing: I actually should not have that term there, I will change it for tag-based single cell RNA sequencing (Again, not really single cell but close enough)

Many thanks!

I will let you know when the new spreadsheet with the rest of the files' metadata is ready

**Comment by idazucchi** [comment]
Hello!
- Dissociation protocol: you are right, I overlooked the lysis buffer, but I think we need to add also the mechanical dissociation term because they used a douncer to homogenise the tissue
- Library preparation: I agree that visium is a gray area because of the resolution, do we want to dicuss it and agree on single cell/ bulk cell? Maybe in a wrangler call?

**Comment by ESapenaVentura** [comment]
Uploaded to ingest, graph valid!

About the last coments:
- I think this is another gray area as well. If we had the ability to put more than one method, I would definitively input the 2 methods, but I feel like the "big part" about this dissociation is that they use the buffer to lyse the cells, and the douncer is mostly to separate what remains and filter
- Library preparation: I think we should stick with single cell, just because it is considered within the "single cell technologies" domain

**Comment by idazucchi** [comment]
Hi Enrique!
I reviewed the file tabs and the analysis protocol tab, they look great!
I only have two minor comments:
- analysis methods: the computational methods are not filled in
- analysis file: the visium rds files have [gene expression matrix](https://ontology.archive.data.humancellatlas.org/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_3112) as a descriptor. Is this to indicate that they are normalised matrices? It looks like a term for microarray so I’m not sure it applies

**Comment by Wkt8** [comment]
Ingest state is 'Exporting' but downstream components have said that they have the data and have validated it on their end.

**Comment by ESapenaVentura** [comment]
Actually there is a problem with the description, contains references. Will correct and re-export

**Comment by ESapenaVentura** [comment]
Updates requested by kuppe are almost done.

Need to delete an ingest-graph-validator test that blocks the submission 

PR here: https://github.com/ebi-ait/ingest-graph-validator/pull/74

**Comment by ESapenaVentura** [comment]
Update blocked until the HCAO deployment

**Comment by gabsie** [comment]
This might need a workaround. Set to graph-valid and see what happens

**Comment by ESapenaVentura** [comment]
Currently stuck in exporting

**Comment by ofanobilbao** [comment]
Exported by Amnon on 27/06/2022

**Comment by ESapenaVentura** [comment]
Checked in the data browser - Once it's live, I will email kuppe for them to check

**Comment by ESapenaVentura** [comment]
Moved to verify in data browser - Updates were made, but they didn't make it to R18 for some reason

Current thread of conversation with Hannes on slack [here](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1658915484833189)

**Comment by MightyAx** [comment]
Azul won't pickup changes in the contributor order, waiting on Azul team to fix importing of non-content item order changes.

**Comment by ESapenaVentura** [comment]
https://github.com/DataBiosphere/azul/issues/4364 for the ticket in azul

**Comment by ESapenaVentura** [comment]
Updated email as requested by contributor

**Comment by MightyAx** [comment]
Some metadata only actions are actually only there to support the data transfer so should not be sent in a pure "Metadata only export"

As an operational task we can delete these.

**Comment by arschat** [comment]
Re-opened to update donor metadata, since [publication](https://www.nature.com/articles/s41586-022-05060-x) and donor metadata is now published.

**Comment by idazucchi** [comment]
verified in browser
