### ISSUE TITLE
DorsolateralCortexSpatial - Maynard

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#663]
### Project short name:
DorsolateralCortexSpatial
### Primary Wrangler:
Ida 
### Secondary Wrangler:
TBD

### Associated files

* Google Drive [folder](https://drive.google.com/drive/folders/1N2-LUlas38VLgLazZa-U-skMyBkKsguz)

### Published study links

* Paper: https://www.nature.com/articles/s41593-020-00787-0#data-availability

* Accessioned data: http://research.libd.org/globus (Non-accessioned)

* Ingest URL: https://contribute.data.humancellatlas.org/projects/detail?uuid=7b393e4d-65bc-4c03-b402-aae769299329

### Key Events

- [ ] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ESapenaVentura** [comment]
All the files are in globus - Before picking this dataset, please ensure you know how to access the data files

**Comment by idazucchi** [comment]
Do we have access to [globus-to-aws:s3](https://www.globus.org/connectors/s3) service through the EBI? I'm not sure

**Comment by idazucchi** [comment]
A few notes:
All the files are in Globus, I wrote a document to explain how to download the data but for the secondary review purpose it can be useful to read the first bit.
Should I integrate the guide in our documentation?

About the files:
The data in globus is organised in folders so the files didn't need to have unique names, and they didn't. I have renamed them by using the folder name as a prefix.
The fastq files are split up every 500.000 reads, since we have no size constraint I've concatenated them together, one file per read type and lane id

**Comment by Wkt8** [comment]
Wei to sec review it

**Comment by Wkt8** [comment]
Looks really really good! Well done on wrangling it so clearly and straightforwardly. Just a few things: 

Specimen:
Can add "cryopreservation in dry ice (dead tissue)" to preservation method because this is effectively fresh-frozen and not FFPE 

Collection Protocol: 
Add doi of the publication which was referenced '10.1016/j.biopsych.2006.06.019' 

Imaged Specimen:
I like the keeping of information of which is replicate 1 / 2 and which come from the different sample 300um back

Library Preparation Protocol:
Spatial barcode information should be added 

Analysis_protocol:
Don't use '||' in text because hannes gets annoyed because components use that for something else. Computation_method is a string dtype, so use ';' instead of '||' 

Analysis_file:
Could potentially add process ID in the process ID tab for analysis_files

**Comment by Wkt8** [comment]
I will verify this in the Data Portal.
