### ISSUE TITLE
Submission stuck in metadata validating

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#702]
Current datasets affected by this issue:

Files took a while to validate (large submission)
- [x] Wei - https://contribute.data.humancellatlas.org/submissions/detail?uuid=8afbcfb8-58cf-4cf3-9377-d6922209d5a5&project=fde199d2-a841-4ed1-aa65-b9e0af8969b1

File(s) stuck in validating
- [x] Ami -  https://contribute.data.humancellatlas.org/submissions/detail?uuid=0f0c06d8-18ec-427b-92b3-9c68986bed63&project=0777b9ef-91f3-468b-9dea-db477437aa1a
- [x] Irene - https://contribute.data.humancellatlas.org/submissions/detail?uuid=9b984263-527f-4fcd-a5a1-c59cd1b91aa3&project=fa3f460f-4fb9-4ced-b548-8ba6a8ecae3f
- [x] Wei - https://contribute.data.humancellatlas.org/submissions/detail?uuid=9e880501-55f3-442d-9908-efae1dac9be9&project=957261f7-2bd6-4358-a6ed-24ee080d5cfc

Original description by Irene:
The submission [6239dd61b06b223527d22d9d](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6239dd61b06b223527d22d9d) (uuid `9b984263-527f-4fcd-a5a1-c59cd1b91aa3` - Irene's submission above) is metadata validating since 23/03 at 14h. Everything looks fine from the UI, but it should be already metadata valid. 

I uploaded the spreadsheet in the morning, got it metadata valid, and applied graph validation in around 2-3 hours. It got a graph error: I forgot to use a sequencing protocol, that was unlinked. That was harder to fix than just deleting the submission and re-submit. That's why I know it should have finished the metadata validation step by now.

**Comment by prabh-t** [comment]
From Slack:
17:41 We managed to unstuck one submission that was stuck in Validating. It was because one file was still validating and after checking the file validation log in the aws batch job, we found the file validated ok but somehow the validationJob status was not received and processed correctly in ingest. We couldn't see anything in the ingest logs and assuming at this point it might be the upload service call to ingest to update this may have failed but we need to look further to confirm.
17:41 This submission is stuck https://contribute.data.humancellatlas.org/submissions/detail?uuid=0f0c06d8-18ec-427b-92b3-9c68986bed63&project=0777b9ef-91f3-468b-9dea-db477437aa1a

That's Ami's submission in the description above.

**Comment by ESapenaVentura** [comment]
moving to "In progress"

**Comment by ESapenaVentura** [comment]
Can we move the other 2 submissions too?

**Comment by prabh-t** [comment]
From Slack:
10.:17
Irene's submission is now also unblocked. It had the same issue as Ami's submission (see my previous comment). Writing down the steps to investigate and how to unblock if this is to occur again.

**Comment by prabh-t** [comment]
From Slack:
10:37
Checked Wei's submission which became unstuck by itself. This is a large submission containing 500+ files and over 2.5T.
It was submitted at 2022-03-23 10:58 and the submission state went into "metadata valid" at 2022-03-23 14:07.
It took about 3hrs to validate the files which I'd think is expected for the submission size, so the state would only get to valid after all file validation jobs are complete. Please bear this in mind for large submission.

**Comment by prabh-t** [comment]
steps to investigate https://github.com/ebi-ait/hca-ebi-dev-team/pull/481

**Comment by ipediez** [comment]
Added to the list the dataset that's stuck now for Wei

**Comment by prabh-t** [comment]
@Wkt8 Submission - AdultLungElo is now unblocked.
