### ISSUE TITLE
SARS-CoV-2 Receptor ACE2 Is an Interferon-Stimulated Gene in Human Airway Epithelial Cells and Is Detected in Specific Cell Subsets across Tissues

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#716]
### Project short name:
CovidCellTypes

### Primary Wrangler:
Ami

### Secondary Wrangler:
Irene 

### Associated files

**Google Drive**
https://docs.google.com/spreadsheets/d/1WiPlkBzBZBrCu4SbOt2uGCe0vIxE-bGHvB5WKrI_Rdo/edit#gid=817397388

**Google Sheet**
https://docs.google.com/spreadsheets/d/1WiPlkBzBZBrCu4SbOt2uGCe0vIxE-bGHvB5WKrI_Rdo/edit#gid=1646211853

* **Ingest**: Updated link to project with submission --> [project](https://contribute.data.humancellatlas.org/projects/detail?uuid=0b299140-25b5-4861-a69f-7651ff3f46cf)
### Published study links

* Paper: https://doi.org/10.1016/j.cell.2020.04.035

**NOTE:** in the paper supplementary files, they note the analysis of already published datasets from a previous study. We didn't have that study in ingest, so I have added it as a separate project using the paper doi:
Ingest:
~~https://contribute.data.humancellatlas.org/projects/detail?uuid=326b36bd-0975-475f-983b-56ddb8f73a4d&tab=project~~
Paper:
https://www.nature.com/articles/s41586-018-0449-8#Sec2

* Accessioned data: mouse (GSE148829), other (https://singlecell.broadinstitute.org/single_cell?scpbr=the-alexandria-project)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [ ] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [x] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by gabsie** [comment]
@ipediez will review today

**Comment by ipediez** [comment]
Project
- Estimated cell count is missing. From Table S9 I took the information of the unpublished results and "This study" results, and summed up the cells stated there. You could check this and add the total number of cells as estimated cell count.
	- Human Adult Inferior Turnibate Scraping (SeqWell1 and 3): 10.111 cells
	- Mouse nasal mucosa (seqWell 3): 11.738 cells
	- Human ileal small intestine (10x v2 3'): 22.220 cells
	- Human lung (seqWell 3): 1.637 cells
	- I haven't found the information for Mouse_cell_line_donor and Human_cell_line_donor.
- Don't forget to update the information in Ingest about the project, as you have much more information in the spreadsheet😉 

Donor
- For the mice receiving IFNa or saline solution, add the timecourse information. This would be a time course value and unit of 12 hours, and the relevance would be something like "sacrifice after treatment with 200ng of IFNa" or "sacrifice after treatment with saline solution", respectively. 

Specimen from organism
- Although it is gonna work in ingest and it is gonna link correctly the biomaterials, you have entered cell suspension IDs on the specimen_from_organism.biomaterial_core.biomaterial_id column. It would be better to add a new column cell_line.biomaterial_core.biomaterial_id and input there the cell lines. You can easily do this by copying the first column at the Cell line tab and inserting it at the Cell suspension tab. You can do this to make the modelling more ordered, or just leave it as it is.

**Comment by ami-day** [comment]
Thanks @ipediez really good points! The last one was a mistake, i would usually model it as you said re: the cell line and specimen ids in the cell suspension tab.

**Comment by ami-day** [comment]
I checked the cell count estimates by comparing to the GEO matrix cell counts. The values pretty much correspond, with some discrepancy as expected because of quality filtering of the data post cell sorting and library preparation.

The cell counts you were unable to find makes sense because they are bulk samples that were sequenced, hence no single-cell estimates.

Here is a table just fyi of the cell counts. I have entered 33,844 as the total cell count in the project tab.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ami/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ami/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



GEO   matrix cell counts |  
-- | --
  |  
file name | GEO matrix cell count
GSM4487943_Mouse_Nasal_IFNa_NS12_dge.txt.gz | 1603
GSM4487938_Mouse_Nasal_IFNa_NH11_dge.txt.gz | 1799
GSM4487941_Mouse_Nasal_IFNa_NH22_dge.txt.gz | 1467
GSM4487940_Mouse_Nasal_IFNa_NH21_dge.txt.gz | 1321
GSM4487939_Mouse_Nasal_IFNa_NH12_dge.txt.gz | 1744
GSM4487942_Mouse_Nasal_IFNa_NS11_dge.txt.gz | 1696
GSM4487944_Mouse_Nasal_IFNa_NS21_dge.txt.gz | 1453
GSM4487945_Mouse_Nasal_IFNa_NS22_dge.txt.gz | 1590
GSE148829_BEAS_Basal_Pops_TPM.txt.gz   (human) | bulk
GSE148829_Human1_Basal_Pops_TPM.txt.gz | bulk
GSE148829_Human2_Basal_Pops_TPM.txt.gz | bulk
Human Nasal   ISSS | 8313
GSE148829_Human_Ileum_absorptiveAndCryptentero_dge.csv.gz | 11856
GSE148829_Human_lung_epithelial_cell_raw_counts.txt.gz | 1002
Mouse basal   stim | bulk
  |  
Summary: publication versus   GEO cell counts |  
  |  
from supplementary table &   publication (Irene's estimate) | from GEO matrix cell count
Human Adult Inferior Turnibate Scraping (SeqWell1 and 3): 10.111 cells | 8313
Mouse nasal   mucosa (seqWell 3): 11.738 cells | 12673
Human ileal   small intestine (10x v2 3'): 22.220 cells | 11856
Human lung   (seqWell 3): 1.637 cells | 1002
  |  
  | SUM
  | 33844



</body>

</html>

**Comment by ami-day** [comment]
Going forward, I have decided that when the matrices are available, I will always use the matrix cell count (now I have a script to calculate this quickly direct from a gzip file). This is because I incorrectly way overestimated a project count recently, due to misreading individual sample counts in the paper. When various technologies arenused, it's easy to do. I find the matrix column count for me at least will be less error prone!

**Comment by ami-day** [comment]
synced the data

**Comment by ami-day** [comment]
graph validating

**Comment by ami-day** [comment]
Submitted to HCA DCP.

**Comment by ami-day** [comment]
exported to hca dcp.

**Comment by ESapenaVentura** [comment]
- This project is repeated 3 times in ingest
  - Actual project is not the one indicated in ingest but this one https://contribute.data.humancellatlas.org/projects/detail?uuid=0b299140-25b5-4861-a69f-7651ff3f46cf&tab=project
  - Please delete the other 2, transfer the metadata (technology, organ etc) to the project that contains the submission and tick the "isInCatalogue" flag
- The supplementary links are not formatted correctly (Long string separated by `;` instead of array of strings)

**Comment by ami-day** [comment]
Re-submitted.

**Comment by ami-day** [comment]
It seems to have got stuck in exporting: https://contribute.data.humancellatlas.org/projects/detail?uuid=0b299140-25b5-4861-a69f-7651ff3f46cf&tab=upload

**Comment by Wkt8** [comment]
Check if the dataset has been fully exported, if it has, then to set it back to valid to allow for further update. 
needs looking into and creating a bug ticket for why the state tracker is failing to properly capture states of datasets.

**Comment by ESapenaVentura** [comment]
SOP [here](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions.html#problem-submission-stuck-in-exporting)

**Comment by Wkt8** [comment]
There's not a further update that needs to be done for this dataset - if it is fully exported, set the state to exported, and then this can be moved to done.

**Comment by ami-day** [comment]
Already created the ticket, it is in the Operations board

**Comment by ESapenaVentura** [comment]
One export job was aborted due to a connection error:
```
2022-07-25 12:39:15	
{"log":"2022-07-25 11:39:15,689 - exporter.terra.terra_listener - ERROR - submission_uuid:302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0 - export_job_id:62de808a5cc3b03957ee841d - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n","stream":"stderr","time":"2022-07-25T11:39:15.693895467Z"}
2022-07-25 12:39:15	
{"log":"2022-07-25 11:39:15,686 - exporter.terra.terra_listener - ERROR - submission_uuid:302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0 - export_job_id:62de808a5cc3b03957ee841d - Rejecting export experiment: ExperimentMessage(process_id='626122b94770e410d1f2089a', process_uuid='9f502e93-ba47-44dc-ba90-224d753677e3', submission_uuid='302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0', experiment_index=73, total=82, job_id='62de808a5cc3b03957ee841d') due to error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n","stream":"stderr","time":"2022-07-25T11:39:15.686507103Z"}
```

**Comment by MightyAx** [comment]
the project link above no longer exists

**Comment by ami-day** [comment]
It is still stuck in exporting: https://contribute.data.humancellatlas.org/projects/detail?uuid=0b299140-25b5-4861-a69f-7651ff3f46cf&tab=upload

**Comment by MightyAx** [comment]
This was really old so was a bit harder to fine but we just need to retry this message
```
Rejecting export experiment: ExperimentMessage(process_id='626122b94770e410d1f2089a', process_uuid='9f502e93-ba47-44dc-ba90-224d753677e3', submission_uuid='302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0', experiment_index=73, total=82, job_id='62de808a5cc3b03957ee841d')
```

I published this message again using the rabbit admin interface, the export succeeded and the project has been set to exported (even after a month of waiting)
```
{"exportJobId":"62de808a5cc3b03957ee841d","documentId":"626122b94770e410d1f2089a","documentUuid":"9f502e93-ba47-44dc-ba90-224d753677e3","callbackLink":"/processes/626122b94770e410d1f2089a","documentType":"process","envelopeId":"626122334770e410d1f2034c","envelopeUuid":"302c1f08-dc2d-4653-8a43-e8ff5ac5d9f0","projectId":"626122464770e410d1f2034e","projectUuid":"0b299140-25b5-4861-a69f-7651ff3f46cf","index":73,"total":82,"context":null}
```

**Comment by ami-day** [comment]
Ok submitted import form for update.

**Comment by ami-day** [comment]
looks ok
