### ISSUE TITLE
Unassigned in process projects at Ingest

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/hca-ebi-wrangler-central#754]
We've got two projects marked as in progress at Ingest, with no one assigned. We should check if they are ours, to try to trace back their actual status. 

## Completed when

All the wranglers have checked this two projects:

- https://contribute.data.humancellatlas.org/projects/detail?uuid=dcbb50d1-9acf-4f70-9fda-b1f63a948c49
- https://contribute.data.humancellatlas.org/projects/detail?uuid=53d20bca-5654-4223-be31-4ac0e7899a73

- [x] Enrique
- [ ] Ami
- [x] Wei
- [x] Ida
- [x] Irene

**Comment by idazucchi** [comment]
I did a small bit of investigation and I think that:
- project 1 is an hca publication. There was some communcation (see [here](https://groups.google.com/a/data.humancellatlas.org/g/wrangler-team/c/c5hGp9F-GTA/m/3gfaYTs4AQAJ)) with the authors about the preprint but nothing came of it because the data was managed access. @ESapenaVentura can you confirm this? 
We might get back to them and see it they have cell count matrices available. If there are matricess I can open a new ticket in queued for wrangling
- project 2 looks like it has no data available and I couldn't find any email about it, so it might be in progress by accident

**Comment by yusra-haider** [comment]
@ami-day to check the two projects

**Comment by idazucchi** [comment]
@idazucchi change status in ingest
