### ISSUE TITLE
Dataset set stuck in graph validation more than once

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#757]
This dataset has got stuck in "graph validating" step twice, and is currently still stuck:
https://contribute.data.humancellatlas.org/projects/detail?uuid=61515820-5bb8-45d0-8d12-f0850222ecf0&tab=upload

Wrangling Board Ticket: #317

**Comment by jacobwindsor** [comment]
I've tried this a few times and think I have found the issue.

Whenever this is ran in prod, it causes ingest-core container to crash. However, when I run this locally it does not crash. I suspect this is because too many requests are made to core causing it to crash. The problem does not arise when ran outside of the cluster as the latency of querying from outside the cluster rate limits the requests. I have added rate limiting to the hydration of ingest-graph-validation and hope this will solve the issue. I will test when it has deployed. Fingers crossed

**Comment by jacobwindsor** [comment]
The above didn't work but it is running successfully outside of the cluster. I will continue to let this run and force the submission to graph valid if it's successful. This will unblock @ami-day and then I can continue investigating the cause later on

**Comment by jacobwindsor** [comment]
Graph validation is still running! Not sure i'll be able to see the result before I get back

**Comment by Wkt8** [comment]
Still in the graph validation state.

**Comment by jacobwindsor** [comment]
@MightyAx to add, if it is valid, you will need to force the submission into graph valid. The graph validator running on EC2 won't change the state fo the submission itself

**Comment by MightyAx** [comment]
Yep, I can see that the EC2 version has finished importing so we just have to wait for it to validate.
```
22-05-04 15:04:14 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 114086 edges
22-05-04 15:04:14 [ingest_graph_validator.utils] - INFO: [get_edges] took [1942058] ms
```

**Comment by MightyAx** [comment]
Hydration (aka Importing the project) finished after 9 hours:
```
22-05-04 21:56:05 [ingest_graph_validator.hydrators.hydrator] - INFO: hydration finished
```

Validation started with
```
ingest-graph-validator action test graph_test_set
```

**Comment by MightyAx** [comment]
Hi @ami-day,
Two Errors detected in graph validation, the following two protocols aren't linked to any other entity:

1. [imaging_preparation_protocol_rnascope1](https://api.ingest.archive.data.humancellatlas.org/protocols/626051856357205eb7bbca1b)
2. [imaging_protocol_dsp_roi_selection_covid_Ab](https://api.ingest.archive.data.humancellatlas.org/protocols/626051866357205eb7bbca24)

I've pushed the submission to graph invalid, and added the errors to the offending protocols so that you can easily find them [in the UI](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9c4eea83-8939-4232-9568-d31eea06718d) and make any changes required.

Once you are ready to try graph validation again, please let me know.

**Comment by MightyAx** [comment]
Ami deleted the orphaned protocols, and I have begun validating the submission on the EC2.
:fingers-crossed: At some point tomorrow we should be ready to set this to graph valid.

**Comment by MightyAx** [comment]
Validation was successful and no validation errors were raised.
```
22-05-05 14:17:27 [ingest_graph_validator.hydrators.hydrator] - INFO: Started ingest hydrator for for submission [9c4eea83-8939-4232-9568-d31eea06718d]
22-05-05 14:17:27 [ingest_graph_validator.hydrators.hydrator] - INFO: Found project for submission 61515820-5bb8-45d0-8d12-f0850222ecf0
22-05-05 14:17:27 [ingest_graph_validator.hydrators.hydrator] - INFO: Found submission for project with uuid 9c4eea83-8939-4232-9568-d31eea06718d
22-05-05 15:49:32 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 15746 nodes
22-05-05 15:49:32 [ingest_graph_validator.utils] - INFO: [get_nodes] took [597] ms
22-05-05 16:24:50 [ingest_graph_validator.hydrators.hydrator] - INFO: imported 114086 edges
22-05-05 16:24:50 [ingest_graph_validator.utils] - INFO: [get_edges] took [2118393] ms
22-05-05 23:23:21 [ingest_graph_validator.hydrators.hydrator] - INFO: hydration finished

22-05-06 09:45:46 [ingest_graph_validator.actions.test_action] - INFO: loading tests
22-05-06 09:45:46 [ingest_graph_validator.actions.test_action] - INFO: loaded [16] test queries
22-05-06 09:45:46 [ingest_graph_validator.actions.test_action] - INFO: running tests
22-05-06 09:45:47 [ingest_graph_validator.actions.test_action] - INFO: All tests finished
```
I've marked the [submission](https://contribute.data.humancellatlas.org/submissions/detail?uuid=9c4eea83-8939-4232-9568-d31eea06718d&project=61515820-5bb8-45d0-8d12-f0850222ecf0) as graph valid.

@ami-day please continue with the submission as usual, thank you for your patience.

**Comment by yusra-haider** [comment]
@MightyAx manually updated this to be graph validated. @ami-day can continue with this

**Comment by MightyAx** [comment]
The Dataset is now exporting 🥳
