### ISSUE TITLE
Profiling of transcribed cis-regulatory elements in single cells

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/hca-ebi-wrangler-central#785]
### Project short name: 
ProfilingCisRegulatoryElements

### Primary Wrangler:

Ami

### Associated files

* Google Drive:
https://drive.google.com/drive/folders/1xi-IlF1Ot0XslaGKKJXc4HnjtnTtkFWL

https://docs.google.com/spreadsheets/d/1Fq1JFdMn2uYoVevQSweCHlfcnKwEXEIz/edit#gid=1305288377

### Published study links

* Paper: [Profiling of transcribed cis-regulatory elements in single cells](https://www.biorxiv.org/content/10.1101/2021.04.04.438388v2)

* Accessioned data:
   - [E-MTAB-10385](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10385/)
   - [E-MTAB-10378](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10378/)
   - [E-MTAB-10381](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10381/)
   - [E-MTAB-10382](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10382/)
   - [E-MTAB-10383](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10383/)
   - [E-MTAB-10384](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10384/)

[Ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=34da2c5f-8011-48af-a7fd-ad2f56ec10f4)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Thanks @idazucchi , I am making/have made most of the suggested changes. The changes I decided not to make or to modify are as follows:

- human_neonatal_foreskin and human_fibroblasts are missing the collection protocol

There is no collection protocol or dissociation protocol available, as the cell lines were bought from a cell link bank (and that info. is not available). It is ok to not included these for purchased cell lines.

- why is human_fibroblast_donor an embryo? I would expect this to be some fibroblast containing tissue since it’s induced stem cells not hESC

Embryo is the closest organ model, because it is an induced pluripotent stem cell line. So, the cells have been reprogrammed and in an embryonic stem cell like state, as opposed to mature adult skin cells.

- DMFB has no associated protocol, you could add a dissociation protocol

Same point as above (cell line collection protocol)

- library_preperation_protocol_sc-end5-rand isn’t the library preparation method 10x v2?

The "rand" in the name stands for random primer. 10X v2 alternatively makes use of a poly-dT primer and 3 prime or 5 prime tag.

- Based on the information in ArrayExpress for E-MTAB-10378 I would make a new library protocol for PBMCs, with total RNA for input molecule and oligodT primer 10x v2 5’

In the ArrayExpress file, the primer is poly-dT. This targets polyA RNA. They also included polyA in the file, I think as the Material type.

- The computational methods field should contain the names of the software used for the analysis.

I found the software within each description and added it to the computational method column.

**Comment by ami-day** [comment]
bam files are downloading.

**Comment by ami-day** [comment]
f19e8e8c-4215-4ba3-993f-256edb6b6546

**Comment by ami-day** [comment]
Some of the data is still downloading

**Comment by ami-day** [comment]
Exported.

**Comment by Wkt8** [comment]
This is present in the DCP in the Data Portal and this has || in the computational_method field to split between multiple fields, and they should not be there because '||' should only be used for fields which are arrays.

**Comment by ami-day** [comment]
> This is present in the DCP in the Data Portal and this has || in the computational_method field to split between multiple fields, and they should not be there because '||' should only be used for fields which are arrays.

Updating this to re-submit.

**Comment by ami-day** [comment]
Graph validating

**Comment by ami-day** [comment]
Graph invalid

**Comment by ami-day** [comment]
Resubmitted, now Exporting.

**Comment by MightyAx** [comment]
2 of the jobs for the submission are stuck, one is:
```
Verifying upload of blob prod/34da2c5f-8011-48af-a7fd-ad2f56ec10f4/metadata/analysis_protocol/b1791056-fc78-474e-ba3f-1d99dc8d04f1_2022-05-24T10:29:38.396000Z.json
```

Which I can is already on the terra staging bucket

**Comment by MightyAx** [comment]
After restarting the exporter job is still waiting for this file:
`prod/34da2c5f-8011-48af-a7fd-ad2f56ec10f4/metadata/analysis_protocol/b1791056-fc78-474e-ba3f-1d99dc8d04f1_2022-05-24T10:29:38.396000Z.json`

**Comment by MightyAx** [comment]
I've tried setting the file metadata manually to:
export_completed: True

hopefully this should unblock the export

**Comment by ami-day** [comment]
Submitted import form.

**Comment by MightyAx** [comment]
Ingest has reported this submission as exported, removing from operations board
