### ISSUE TITLE
GSE129455 - PancreaticDuctalAdenocarcinomaFibroblasts

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#828]
### Project short name: 
PancreaticDuctalAdenocarcinomaFibroblasts
### Primary Wrangler:
Ida

### Associated files

* Google Drive: [folder](https://drive.google.com/drive/folders/178jQRG4LuQrHG30Gw_Py_N2rRluV9mol)

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=da9d6f24-3bdf-4eaa-9e3f-f47ce2a65b36

### Published study links

* Paper: [Cross-Species Single-Cell Analysis of Pancreatic Ductal Adenocarcinoma Reveals Antigen-Presenting Cancer-Associated Fibroblasts](https://doi.org/10.1158/2159-8290.CD-19-0094)

* Accessioned data: [GSE129455](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129455)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Transfer raw files to ingest to validate data files
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by Wkt8** [comment]
Secondary Review Notes: 

Add yourself as a curator :) 

Should project cell count be reduced to only the mouse cell counts? (11260 cells) As the human cells were not wrangled / represented. 

I couldn't see where you got the information for the mouse strain from "C57BL/6J" - can you confirm? 

The enrichment protocol for 'fibroblast_selection' is a bit confusing i think because part of the steps happen for both the 'viable' population and the 'fibroblast-enriched' population? I believe it's the final step which is sorting for DAPI-, CD3- and EpCAM-negative cells that happens only for 'fibroblast-enriched' but the earlier incubation, quenching, spinning, resuspension, etc. happens for both cell populations. 

I would recommend one of two options:
1. Include the 'fibroblast_selection' protocol in the process for the 'viable' cell suspensions as well, perhaps renaming it to 'FACS_sorting' 
2. Split the 'fibroblast_selection' protocol into three bits: 

Staining and selection:
After a 3 minute incubation on ice, the ACK was quenched with 2% FBS/PBS. Cells were spun down, resuspended in PBS supplemented with 0.5% BSA and 2 mM EDTA and blocked with anti-mouse CD16/CD32 Fc Block for 15 minutes at 4°C. Staining of mouse tissue for flow sorting was performed with the following antibodies: CD45-AF647, CD31-AF647, and EpCAM-AF647, for 30 minutes at 4°C. Prior to sorting, DAPI was added to the cell suspension. Cells were sorted using a BD FACSAria Fusion instrument.

Viable_selection
Following exclusion of debris, 50,000-100,000 DAPI-negative cells were collected from each sample (for ‘all viable cell’ fraction).

fibroblast_selection
Then sorting for DAPI-, CD45-, CD31- and EpCAM-negative cells was performed (for ‘fibroblast-enriched’ fraction). Both fractions were collected in 20% FBS/PBS.

I think it should be CellRanger (v1.3) that was actually used for creating fastqs, although 1.2.0 was used for aligning but.. either should be fine as that's a value judgement there. 

Computational_method is 'Cellranger ;' can remove the semi-colon?

**Comment by idazucchi** [comment]
I've updated the cell count to reflect only the mouse cells sequenced
The mouse strain comes from GEO samples

**Enrichment protocol**
I've split the enrichment protocol in two:
1. `viable cells` : Preparation for FACS (quenching + blocking) + DAPI staining and FACS sorting
1. `fibroblasts` : antibodies staining and FACS sorting

The `viable cells` is applied to all cell suspensions, `fibroblasts` only to the four fibroblasts cell suspensions
