### ISSUE TITLE
EGAS00001004388 - DevelopmentalOriginsNeuroblastoma

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#830]
### Project short name: 
DevelopmentalOriginsNeuroblastoma
### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida

### Associated files

* Google Drive:

https://drive.google.com/drive/folders/1Yu5AoZz0GdLfX0RBrqe2ObeKtxW6gPAC

**With primary data** **MAIN VERSION TO BE SUBMITTED**
https://docs.google.com/spreadsheets/d/1B2gP1FmAXd7smUDULK6Iq4o-I3jrtp0CkoYclTGHoyw/edit#gid=1720350199

**Without primary data**
https://docs.google.com/spreadsheets/d/1wJX75dTushLSDebCyQ5kwRuch_Ez3880483_qMEly4E/edit#gid=1227909870

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=c8e6c5d9-fcde-4845-bead-ff96999e3051

### Published study links

* Paper: [Single-cell transcriptomic analyses provide insights into the developmental origins of neuroblastoma](https://doi.org/10.1038/s41588-021-00806-1)

* Accessioned data: 
  - EGAS00001004388
  - [GSE163431](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE163431)

**Notes:**

The data availability is confusing. It says the counts file are for: "31 single-cell transcriptomes of neuroblastomas and normal human developing adrenal glands at various stages of embryonic and fetal development". Assuming this means (1) neuroblastoma samples from the donors listed in Supplementary 8 (<18 months or >18 months old) and (2) embryonic and fetal adrenal samples. There is no metadata available at all for embryonic and fetal donors or samples. Hence, I will not include these donors in the curated spreadsheet. It is also unclear which of the processed counts files correspond to the neuroblastoma patient ids - I have contacted the authors to ask about this.

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Moving this to stalled. There is too much missing metadata to be able to curate this to the HCA standard. I have contacted the authors, if they get back I will move forward with the dataset. If not, it should be marked as ineligible.

**Comment by ami-day** [comment]
Response from the authors:

"In our study, we have two data sets. The neuroblastoma data set is derived from neuroblastoma patients aged >0 months and does not contain any fetal or embryonic donors. The adrenal gland data set originates from healthy embryonic and fetal donors."

Because the publication does not provide any metadata or information about the healthy human embryonic and fetal donors (healthy adrenal gland data), I have excluded this from the metadata spreadsheet. This is because we cannot ask for additional metadata about living european donors (privacy restrictions). I have however downloaded the gene expression counts for the neuroblastoma patients, and the linked patient ids.

Also: the authors say FACS was used to sort single cells (i.e. not doublets, multiplets). No antibodies against cell surface markers or live staining dyes were used.

**Comment by ami-day** [comment]
'''
000b810a-f3d5-48c1-9e63-63154df9ccfb
'''

**Comment by ami-day** [comment]
Creating a copy - primary data will be removed, since we cannot ask for additional metadata OR data files from a contributor if it is not already public (living European donors).

**Comment by ami-day** [comment]
Graph validating

**Comment by Wkt8** [comment]
Discuss later on slack or set up a meeting with wranglers to discuss 'organ' term

**Comment by ami-day** [comment]
Graph valid

**Comment by idazucchi** [comment]
Hi Ami, I'm donw with the secondary review!
I think that the adrenal gland data is eligible. The donor metdata is in supplementary table 1 and the cell barcodes are the same as supplementary table 3 so the cell count matrix can be analysed without problems

### Donor
- you can describe the clinical subtype in the genotype field
- the age range doesn't match the dev stage, can you change the age range or the developmental stage so that they match up?
- you can remove the untreated primary tumor from the treatments field because they underwent no treatment and specify metastasis/primary in the specimen description
- `neuroblastoma_cell_line_2_donor` descrption has a typo, says olf rather than old
- `neuroblastoma_cell_line_3_donor` is white 6 years old female according to the cell line supplier's website

### Specimen
- based on Tony's suggestion we can inidcate if a specimen is primary or metastasis site in the description field and use the organ field to represent the sampling site rather than the nervosus system
- you can describe the clinical subtype in the genotype field
- you can fill in the preservation method

### Cell line
- you can add the supplier for cell line 1 and 3
- the cell lines were tested for mycoplasma, you could add that in the `mycoplasma testing result` field 
- you can add the publication information 
- `neuroblastoma_cell_line_2` is MYC knockdown, you can add that in the genotype section

### Cell suspension
- for the cell lines: you can add the SRS sample identifiers 

### Enrichment protocol
- is the FACS protocol needed? it's not enriching for anything, it's more part of the library prep

### Sequencing
- add one more protocol for the HiSeq 4000 for the neuroblastoma patients
>Libraries were sequenced on an Illumina HiSeq 4000 or NovaSeq 6000 sequencing platform

### Sequence file
- for cell suspensions `GSM4979214, GSM4979213 ` the sequencing protocol should be `sequencing_protocol_3`
- the files with `library_preparation_protocol_MARS-Seq` should have sequencing protocol `sequencing_protocol_2`

### Analysis file
- `Neuroblastoma_sc_Jansky.rds` should have sequencing protocol `sequencing_protocol_2` and the new sequecning protocol with  HiSeq 4000
- for cell suspensions `GSM4979214, GSM4979213 ` the sequencing protocol should be `sequencing_protocol_3`
- `GSE163430_SK-N-AS_counts.tsv.gz` should have sequencing protocol `sequencing_protocol_2`

**Comment by ami-day** [comment]
Getting an error importing the updated submission in ingest prod.

**Comment by MightyAx** [comment]
Some notes from testing this on staging:
You may want to either add the following files to the project metadata or delete them from the upload area: `000b810a-f3d5-48c1-9e63-63154df9ccfb` 

- GSE163428_SK-N-BE_2_C_counts.tsv
- GSM4979213_IMR575-shMYCN_kd_filtered_counts.tsv
- GSM4979214_IMR575-shMYCN_ctrl_filtered_counts.tsv
- GSE163430_SK-N-AS_counts.tsv

Otherwise they will be added to the project as draft files that you have to delete, and possibly exported to the terra staging area.

**Comment by ami-day** [comment]
Thanks @MightyAx for looking into this. I think in thr the updated submission the issue you mention above will be resolved. I will check once it has been successfully imported.

**Comment by MightyAx** [comment]
if you make a new project (and delete the existing one) you will be able to import the spreadsheet. I tested this on staging yesterday with your project.

**Comment by MightyAx** [comment]
Production has been updated, @ami-day you should now be able to import sucessfully.

**Comment by ami-day** [comment]
Reimport was successful.

**Comment by ami-day** [comment]
exported and submitted import form.

**Comment by ESapenaVentura** [comment]
@MightyAx to investigate if this has actually been exported

**Comment by ESapenaVentura** [comment]
Has not been exported

```
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c8e6c5d9-fcde-4845-bead-ff96999e3051/
CommandException: One or more URLs matched no objects.
```

**Comment by MightyAx** [comment]
waiting on issue: ebi-ait/hca-ebi-wrangler-central#926

**Comment by MightyAx** [comment]
Issue resolved, Exporting.

**Comment by ami-day** [comment]
Looks good.
