### ISSUE TITLE
E-MTAB-8119 - SingleCellPathologicalAngiogenesis

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#831]
### Project short name: 
SingleCellPathologicalAngiogenesis
### Primary Wrangler:
Ami

### Secondary Wrangler:
Ida 

### Associated files

* Google Drive:

https://drive.google.com/drive/folders/1K5yj5xx3NEO6Yfb-YiZz5moaF8-TcUnj

https://docs.google.com/spreadsheets/d/1mzNFqbpM_mJG-3bD2zPIFvOeLUPyqSxC/edit#gid=1846491666

### Link to Ingest
https://contribute.data.humancellatlas.org/submissions/detail?uuid=19590dcf-7239-4b9d-8370-9b04d260ba3b&project=4c73d1e4-bad2-4a22-a0ba-55abbdbdcc3d

### Published study links

* Paper: [Single-Cell RNA Sequencing Maps Endothelial Metabolic Plasticity in Pathological Angiogenesis](https://doi.org/10.1016/j.cmet.2020.03.009)

* Accessioned data: [E-MTAB-8119](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-8119)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [x] Check linking using ingest graph validator
- [x] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by ami-day** [comment]
Requested new ontology term: "choroidal neovascularization" under "eye disorder" (MONDO).

**Comment by ami-day** [comment]
Moving to stalled until the new disease ontology term becomes available.

**Comment by ami-day** [comment]
Downloading data files

**Comment by Wkt8** [comment]
Ami to upload and sync data files + graph validation then one of the wranglers to pick up for secondary review.

**Comment by ami-day** [comment]
Data files are uploading

**Comment by ami-day** [comment]
473e4480-0e4d-4160-a6ee-3ba3cc642b65

**Comment by ami-day** [comment]
Data files synced and graph is valid.

**Comment by idazucchi** [comment]
Hi Ami! I'm done with the secondary review

### Project
- the cell count should be mouse + human —> 1,670+28,337= 30,007
- please add the visualisation portal link in the supplementary links section

### Donor
Based on this I would add 30 mouse donors, 15 healthy ones and 15 disease model donors, which get pooled together at the cell suspension stage
>[the Murine Choroid Endothelial Cell Isolation] procedure was repeated for 3 independent replicate experiments, and 3 additional experiments were performed to obtain reference samples of ECs isolated from healthy choroid of control mice without laser injury (referred to as healthy CECs; n = 2 eyes/mouse and n = 6 mice per experimental group).

- you could improve the description of the donors by swapping the acronyms CEC and CNV with choroidal Endothelial cell and choroidal neovascularization
- you could use `Choroidal neovascularization` for the disease model mice to reflect the condition they model
- you could model the eye lesion procedure with the timecourse fields, 7 days after the procedure

### Collection protocol
- if you model the eye lesion procedure with the timecourse you can use the same collection protocol for all mice
- the info about how the mice were kept is not really part of the collection protocol. the following is more accurate
> mice were euthanized by cervical dislocation and the eyes were enucleated.

### Specimen from organism
Similarly to the donors I would add 15 healthy specimens and 15 disease model specimens
- you could use `Choroidal neovascularization` for the disease model mice to reflect the condition they model
- you can add `optic choroid` as organ part


### Dissection protocol
- the human and mouse enzymatic dissociation protocol are essentially the same, if you want you can use the same one for both human and mouse

### Enrichment protocol
- the human and mouse MACS enrichment protocol are identical, if you want you can use the same one for both human and mouse

### Sequence file
- the files for`ERR9750949` are missing 

### Analysis protocol
- since there are both raw and normalised files it would be more accurate to have a Raw matrix generation protocol for mouse and human
human raw
> Sequencing reads were mapped to the human genome (build GRCh38) using CellRanger software (10x Genomics, version 2.1.1).

mouse raw
>Sequencing reads were mapped to the mouse genome (build mm10) using CellRanger software (10x Genomics, version 2.1.1). Data from MACS-enriched samples were aggregated using Cell Ranger 

Normalisation protocol
> the raw unfiltered matrix was further processed using R. The following quality control steps were applied: (i) genes expressed by < 50 cells or with a row mean of < 0.01 were not considered; (ii) cells that had either fewer than 201 (low quality cells) or over 6,000 expressed genes (possible doublets), or over 5% of unique molecular identifiers (UMIs) derived from the mitochondrial genome were removed. The data of the remaining cells were natural-log transformed using log1p and normalized using the Seurat package (Satija et al., 2015).
- there is no batch correction protocol for the batch corrected file


### Analysis file
- some mouse files have human cell suspensions linked and some human files have mouse cell suspensions associated to them 
- `Batch_corrected_data_mouse_Metadata.csv` is missing the source
- you could add the cell count for the matrices

**Comment by ami-day** [comment]
Thanks @idazucchi , I have made most of the suggested changes. I think the number of mouse donors is actually 18 with CNV and 18 healthy, I changed the linking to reflect this.

**Comment by ami-day** [comment]
Submitted/Exporting.

**Comment by ami-day** [comment]
Exported, submitted import form.
