### ISSUE TITLE
GSE63473 - Highly Parallel Genome-wide Expression Profiling of Individual Cells Using Nanoliter Droplets

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/hca-ebi-wrangler-central#835]
### Project short name: 
HighlyParallelExpressionProfiling

### Primary Wrangler:
Ami

### Secondary Wrangler:
@idazucchi 

### Associated files

* Google Drive:

https://docs.google.com/spreadsheets/d/1CEmql6BM-4QGICFB3ItStxwhjsu0omZu/edit#gid=1951407909
[folder](https://drive.google.com/drive/folders/1f6uAY7wCCVBj64uVKMbPzNUrppSWu3gN)

### Link to Ingest
* https://contribute.data.humancellatlas.org/projects/detail?uuid=3c9d586e-bd26-4b46-8690-3faaa18ccf38

### Published study links

* Paper: https://doi.org/10.1016/j.cell.2015.05.002

* Accessioned data: [GSE63473](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63473)

### Key Events

- [x] Convert published metadata to HCA spreadsheet
- [x] Manually curate dataset to meet HCA metadata standard
- [x] Collect any matrix and cell-type annotation files
- [x] Upload sheet to validate metadata
- [ ] Check linking using ingest graph validator
- [ ] Transfer raw files to ingest to validate data files
- [x] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Submit dataset to Production 
- [ ] Complete the Export SOP
- [ ] Convert project data to SCEA format following the SCEA conversion SOP if appropriate

**Comment by idazucchi** [comment]
Hi Ami! I'm done with the secondary review. The dataset is all right, I have just some suggestion and a couple missing ontologies to point out.

### Project
- the contributor metadata is not formatted correctly
- the is paper is not an official HCA publication


### Donor
- the age should be 14 days for all mice
- I think the developmental stage should be infant because mice become adult at 21 days
- the ontology terms are missing for mouse strain, genus species and disease

### Specimen
- you can add the insdc sample accessions

### Dissociation
- I would split the dissociation protocol into enzymatic and mechanical dissociation
- the dissociation method ontology term is missing

### Enrichment protocol
- the enrichment method ontology term is missing

### Cell suspension
- `genus species` should be mus musculus
- the genus species ontology term is missing

### Library preparation 
- the ontology terms for `library construction method` and `input nucleic acid molecule` are missing

### Sequencing protocol
- you could add bcl2fastq2’s version

### Analysis protocol
- I would split the protocol in two: one to merge the 7 raw matrices (GSE63472_P14Retina_merged_digital_expression.txt.gz), one to normalise the matrix (GSE63472_P14Retina_logDGE.txt.gz)

### Analysis file
- please list the single files in the `.tar` so that each one can be described accurately
- you could add cell count estimate for the cell count matrices

**Comment by ami-day** [comment]
Submitted and filled import form.

**Comment by ami-day** [comment]
Looks fine in data browser.
