### ISSUE TITLE
GSE52583 High throughput quantitative whole transcriptome analysis of distal mouse lung epithelial cells from various developmental stages (E14.5, E16.5, E18.5 and adult)

### ISSUE THREAD

**Issue by lauraclarke** [ebi-ait/hca-ebi-wrangler-central#85]
**Primary Wrangler:**
Marion
**Secondary Wrangler:**
TBD

**Associated files:**

Google Drive: [Folder](https://drive.google.com/drive/folders/1LH36GunA7YA0jQ1o_rNPdKWqeD3rd0_y)

s3 bucket: TBC

Geo page:

Paper:

**Key Events**

- [x] Assign the Primary Wrangler
- [ ] Fill spreadsheet (to a sufficient standard to submit dataset)
- [ ] Get CellType annotation (To a sufficient standard to submit to SCEA)
- [ ] Upload data (to a sufficient standard to submit dataset)
- [ ] Curate metadata spreadsheet with ontologies
- [ ] Upload sheet to validate metadata (most likely in staging)
- [ ] Check linking
- [ ] Validate data files
- [ ] Ask the Secondary Wrangler for an end-to-end review of the project. Ask the Expertise Wrangler to review specific tabs if needed
- [ ] Get final approval of submission from SCEA
- [ ] Submit dataset to Production?

**Please track the below as well as the key events:**
1. Track date first spreadsheet received and final spreadsheet sent by editing ticket to include
date next to event.
1. Track spreadsheet iterations by placing asterisks next to receive spreadsheet event.
1. Track any metadata issues/tickets made for dataset with a bulleted list of links under
received spreadsheet event. Links should be to the ticket in the metadata repo.

**Comment by lauraclarke** [comment]
This is copied from https://github.com/HumanCellAtlas/hca-data-wrangling/issues/447

It is confirmed that SCEA can accept SMARTER C1 data

**Comment by ami-day** [comment]
@lauraclarke From what I remember, we had a discussion about this dataset between the wranglers, and we decided to not move forward with wrangling this dataset for HCA. We agreed it was unsuitable for the HCA, due to the samples being obtained from genetically-modified mice. Also, the organ type is the Lung, for which (I believe) primary human tissue is not so challenging to get hold of that experimental designs involving mouse samples are necessary. We didn't have a stringent way of determining dataset suitability at this point, so this particular dataset made it in to the ZenHub board and then from what I remember @mshadbolt didn't continue with it due to unsuitability. Does this sound accurate to you, @mshadbolt, I may have remembered incorrectly ? If it is suitable for SCEA (I will ask Anja when we meet with her next week) then I'll move this ticket to the SCEA Zenhub column, and if not, I will close this ticket.

**Comment by mshadbolt** [comment]
i think it is best to close it, we can reopen it in future if we decide something different.
