### ISSUE TITLE
Data Curator Ontology Term not found in HCAO

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/hca-ebi-wrangler-central#880]
The 'Data Curator' ontology term in OLS (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009737) which we normally use to describe wranglers in the project.contributors tab is no longer present in the HCAO (https://ontology.archive.data.humancellatlas.org/search?q=data+curator)

This means we cannot currently export any projects using the data curator ontology term. 

**Acceptance criteria for the task:**
- [x] Data Curator ontology term is back in HCAO
- [x] Identified what other terms are not present in HCAO
- [x] Those terms are also added back into HCAO 
- [x] https://contribute.data.humancellatlas.org/submissions/detail?uuid=5b8676e2-c01b-4e19-b9cf-e14088ff46f9&project=425c2759-db66-4c93-a358-a562c069b1f1 has been exported

**Comment by MightyAx** [comment]
@Wkt8 to contact ontology team to resolve this issue

**Comment by idazucchi** [comment]
@Wkt8 and I did some investigation on the HCAO release and why the terms for data curator. It looks like it’s two problems in one:
- in EFO the terms for contributor role have been moved from organisation role to role —> this means that our schema validation is failing because the contributor role terms are no longer under the parent indicated in the schema
- role in HCAO does not match role in OLS —> maybe this did not get imported correctly with HCAO 1.0.41, Wei is checking on this with Bradley and Zoe

Can we address the new parent term situation with a hotfix schema PR once the terms are available again in HCAO?
_Clarification_:
The terms under role have maintained their ids and the data already ingested shouldn't be affected

**Comment by ESapenaVentura** [comment]
The terms are back into EFO's slim - Just under a different term. Deployed to prod.

We need the schema update to fix this issue

**Comment by ESapenaVentura** [comment]
Metadata schema update: https://github.com/HumanCellAtlas/metadata-schema/pull/1484

**Comment by gabsie** [comment]
MERGE ITTTTTT as it's approved @ESapenaVentura

**Comment by ESapenaVentura** [comment]
@Wkt8 the project is ready to be updated! instructions on how to update the validation:
- Download spreadsheet from submission
- Make the changes you need to do in that spreadsheet (Or a very small one, like adding a "_" to the end of the description of a biomaterial) so that it revalidates everything
- in the schemas tab in the spreadsheet, change the project version to 17.0.0

**Comment by Wkt8** [comment]
Project has been updated.
Changed from metadata invalid --> metadata valid
Graph validation occurred.
Exported with metadata only.
Import form filled out.

**Comment by MightyAx** [comment]
One last thing for this ticket will be resolved with #883
