### ISSUE TITLE
dataset problem - scHumanBrainVasculature

### ISSUE THREAD

**Issue by rachadele** [ebi-ait/hca-ebi-wrangler-central#973]
- project uuid - 79351583-b212-44ba-b473-731bdcddb407

- [link to ingest UI](https://contribute.data.humancellatlas.org/projects/detail?uuid=79351583-b212-44ba-b473-731bdcddb407)

**Relevant People**
- Wrangler: Rachel Schwartz

I'm seeing graph errors for dissociation, enrichment, library prep and sequencing protocol. Everything in the spreadsheet looks correct to me; could someone help me figure out what's causing them?
I have attached the excel sheet for review :)

[GSE173731 - scHumanBrainVasculature (5).xlsx](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/10044346/GSE173731.-.scHumanBrainVasculature.5.xlsx)

**Comment by ESapenaVentura** [comment]
Hi Rachel, 

There are some linking problems in the spreadsheet:
- The main problem is that there are 2 empty columns in the "cell suspension" tab, which need to be deleted. The ingest importer assumes that when there is an empty column, the sheet has finished so that's why it's not picking up the connection between the cell suspensions and the specimens (thus creating the orphaned protocols)
- Also, without looking super deep into it, I have noticed "donor 14" is not used anywhere, which is an issue as well!

Please fix the spreadsheet and let me know if there are further errors :)

**Comment by rachadele** [comment]
thanks enrique!
